services:
    web-server:
        build:
            context: ./web-server
            dockerfile: Dockerfile
        restart: unless-stopped
        volumes:
            - ./web:/app/web:ro
        ports:
            - "8080:3000"
        environment:
            - NODE_ENV=development
            - API_BASE_URL=http://apache:80
        depends_on:
            - apache

    apache:
        build:
            context: .
            dockerfile: Dockerfile-apache
        restart: unless-stopped
        volumes:
            - ./public_html:/var/www/html
            - ./Payload:/app/payload
        ports:
            - 80:80
        logging:
            options:
                max-size: "10m"
    runner:
        build:
            context: .
            dockerfile: Dockerfile-dind
        restart: unless-stopped
        volumes:
            - ./runner:/app
            - node_modules:/app/node_modules
            - /var/run/docker.sock:/var/run/docker.sock
            - ./public_html/runs:/phppayload
            - runs:/runs
        ports:
            - 127.0.0.1:3000:3000
        command: npm run dev
        # command: tail -f /dev/null #idle container

    mysql:
        image: mysql:8.0
        restart: unless-stopped
        environment:
            - TZ=America/Sao_Paulo
            - MYSQL_DATABASE=${MYSQL_DATABASE}
            - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
        volumes:
            - mysql:/var/lib/mysql
            - .:/app
        ports:
            - 127.0.0.1:${MYSQL_PORT}:3306
volumes:
    node_modules:
    mysql:
    runs:
        name: gladcode_tmp_run