/*
 promise-polyfill 3.1.0 */
var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(e){var k=0;return function(){return k<e.length?{done:!1,value:e[k++]}:{done:!0}}};$jscomp.arrayIterator=function(e){return{next:$jscomp.arrayIteratorImpl(e)}};$jscomp.makeIterator=function(e){var k="undefined"!=typeof Symbol&&Symbol.iterator&&e[Symbol.iterator];return k?k.call(e):$jscomp.arrayIterator(e)};
$jscomp.getGlobal=function(e){return"undefined"!=typeof window&&window===e?e:"undefined"!=typeof global&&null!=global?global:e};$jscomp.global=$jscomp.getGlobal(this);$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(e,k,h){e!=Array.prototype&&e!=Object.prototype&&(e[k]=h.value)};
$jscomp.polyfill=function(e,k,h,m){if(k){h=$jscomp.global;e=e.split(".");for(m=0;m<e.length-1;m++){var d=e[m];d in h||(h[d]={});h=h[d]}e=e[e.length-1];m=h[e];k=k(m);k!=m&&null!=k&&$jscomp.defineProperty(h,e,{configurable:!0,writable:!0,value:k})}};$jscomp.FORCE_POLYFILL_PROMISE=!1;
$jscomp.polyfill("Promise",function(e){function k(){this.batch_=null}function h(g){return g instanceof d?g:new d(function(d,e){d(g)})}if(e&&!$jscomp.FORCE_POLYFILL_PROMISE)return e;k.prototype.asyncExecute=function(g){if(null==this.batch_){this.batch_=[];var d=this;this.asyncExecuteFunction(function(){d.executeBatch_()})}this.batch_.push(g)};var m=$jscomp.global.setTimeout;k.prototype.asyncExecuteFunction=function(g){m(g,0)};k.prototype.executeBatch_=function(){for(;this.batch_&&this.batch_.length;){var g=
this.batch_;this.batch_=[];for(var d=0;d<g.length;++d){var e=g[d];g[d]=null;try{e()}catch(w){this.asyncThrow_(w)}}}this.batch_=null};k.prototype.asyncThrow_=function(d){this.asyncExecuteFunction(function(){throw d;})};var d=function(d){this.state_=0;this.result_=void 0;this.onSettledCallbacks_=[];var g=this.createResolveAndReject_();try{d(g.resolve,g.reject)}catch(t){g.reject(t)}};d.prototype.createResolveAndReject_=function(){function d(d){return function(g){h||(h=!0,d.call(e,g))}}var e=this,h=!1;
return{resolve:d(this.resolveTo_),reject:d(this.reject_)}};d.prototype.resolveTo_=function(g){if(g===this)this.reject_(new TypeError("A Promise cannot resolve to itself"));else if(g instanceof d)this.settleSameAsPromise_(g);else{a:switch(typeof g){case "object":var e=null!=g;break a;case "function":e=!0;break a;default:e=!1}e?this.resolveToNonPromiseObj_(g):this.fulfill_(g)}};d.prototype.resolveToNonPromiseObj_=function(d){var g=void 0;try{g=d.then}catch(t){this.reject_(t);return}"function"==typeof g?
this.settleSameAsThenable_(g,d):this.fulfill_(d)};d.prototype.reject_=function(d){this.settle_(2,d)};d.prototype.fulfill_=function(d){this.settle_(1,d)};d.prototype.settle_=function(d,e){if(0!=this.state_)throw Error("Cannot settle("+d+", "+e+"): Promise already settled in state"+this.state_);this.state_=d;this.result_=e;this.executeOnSettledCallbacks_()};d.prototype.executeOnSettledCallbacks_=function(){if(null!=this.onSettledCallbacks_){for(var d=0;d<this.onSettledCallbacks_.length;++d)p.asyncExecute(this.onSettledCallbacks_[d]);
this.onSettledCallbacks_=null}};var p=new k;d.prototype.settleSameAsPromise_=function(d){var e=this.createResolveAndReject_();d.callWhenSettled_(e.resolve,e.reject)};d.prototype.settleSameAsThenable_=function(d,e){var g=this.createResolveAndReject_();try{d.call(e,g.resolve,g.reject)}catch(w){g.reject(w)}};d.prototype.then=function(e,h){function g(d,e){return"function"==typeof d?function(e){try{k(d(e))}catch(z){m(z)}}:e}var k,m,p=new d(function(d,e){k=d;m=e});this.callWhenSettled_(g(e,k),g(h,m));return p};
d.prototype.catch=function(d){return this.then(void 0,d)};d.prototype.callWhenSettled_=function(d,e){function g(){switch(h.state_){case 1:d(h.result_);break;case 2:e(h.result_);break;default:throw Error("Unexpected state: "+h.state_);}}var h=this;null==this.onSettledCallbacks_?p.asyncExecute(g):this.onSettledCallbacks_.push(g)};d.resolve=h;d.reject=function(e){return new d(function(d,g){g(e)})};d.race=function(e){return new d(function(d,g){for(var k=$jscomp.makeIterator(e),m=k.next();!m.done;m=k.next())h(m.value).callWhenSettled_(d,
g)})};d.all=function(e){var g=$jscomp.makeIterator(e),k=g.next();return k.done?h([]):new d(function(d,e){function m(e){return function(g){p[e]=g;t--;0==t&&d(p)}}var p=[],t=0;do p.push(void 0),t++,h(k.value).callWhenSettled_(m(p.length-1),e),k=g.next();while(!k.done)})};return d},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(e){return e?e:function(e,h,m){var d=this.length||0;0>h&&(h=Math.max(0,d+h));if(null==m||m>d)m=d;m=Number(m);0>m&&(m=Math.max(0,d+m));for(h=Number(h||0);h<m;h++)this[h]=e;return this}},"es6","es3");
(function(e,k){"function"===typeof define&&define.amd?define(["exports"],k):"object"===typeof exports&&"string"!==typeof exports.nodeName?k(exports):k(e.commonJsStrict={})})(this,function(e){function k(a){if(a in P)return a;for(var b=a[0].toUpperCase()+a.slice(1),c=Q.length;c--;)if(a=Q[c]+b,a in P)return a}function h(a,b){a=a||{};for(var c in b)b[c]&&b[c].constructor&&b[c].constructor===Object?(a[c]=a[c]||{},h(a[c],b[c])):a[c]=b[c];return a}function m(a){if("createEvent"in document){var b=document.createEvent("HTMLEvents");
b.initEvent("change",!1,!0);a.dispatchEvent(b)}else a.fireEvent("onchange")}function d(a,b,c){if("string"===typeof b){var f=b;b={};b[f]=c}for(var l in b)a.style[l]=b[l]}function p(a,b){a.classList?a.classList.add(b):a.className+=" "+b}function g(a,b){var c=new Image;c.style.opacity=0;return new Promise(function(f){function l(){c.style.opacity=1;setTimeout(function(){f(c)},1)}c.removeAttribute("crossOrigin");a.match(/^https?:\/\/|^\/\//)&&c.setAttribute("crossOrigin","anonymous");c.onload=function(){b?
EXIF.getData(c,function(){l()}):l()};c.src=a})}function N(a,b){var c=a.naturalWidth,f=a.naturalHeight;(a=b||t(a))&&5<=a&&(a=c,c=f,f=a);return{width:c,height:f}}function t(a){return a.exifdata?a.exifdata.Orientation:1}function w(a,b,c){var f=b.width,l=b.height,d=a.getContext("2d");a.width=b.width;a.height=b.height;d.save();switch(c){case 2:d.translate(f,0);d.scale(-1,1);break;case 3:d.translate(f,l);d.rotate(180*Math.PI/180);break;case 4:d.translate(0,l);d.scale(1,-1);break;case 5:a.width=l;a.height=
f;d.rotate(90*Math.PI/180);d.scale(1,-1);break;case 6:a.width=l;a.height=f;d.rotate(90*Math.PI/180);d.translate(0,-l);break;case 7:a.width=l;a.height=f;d.rotate(-90*Math.PI/180);d.translate(-f,l);d.scale(1,-1);break;case 8:a.width=l,a.height=f,d.translate(0,f),d.rotate(-90*Math.PI/180)}d.drawImage(b,0,0,f,l);d.restore()}function U(){function a(a){if(void 0===a.button||0===a.button)if(a.preventDefault(),!e){var d=f.elements.overlay.getBoundingClientRect();e=!0;H=a.pageX;g=a.pageY;n=-1!==a.currentTarget.className.indexOf("vertical")?
"v":"h";h=d.width;k=d.height;a.touches&&(a=a.touches[0],H=a.pageX,g=a.pageY);window.addEventListener("mousemove",b);window.addEventListener("touchmove",b);window.addEventListener("mouseup",c);window.addEventListener("touchend",c);document.body.style[B]="none"}}function b(a){var c=a.pageX,b=a.pageY;a.preventDefault();a.touches&&(b=a.touches[0],c=b.pageX,b=b.pageY);a=c-H;var r=b-g,I=f.options.viewport.height+r,e=f.options.viewport.width+a;"v"===n&&50<=I&&I<=k?(d(l,{height:I+"px"}),f.options.boundary.height+=
r,d(f.elements.boundary,{height:f.options.boundary.height+"px"}),f.options.viewport.height+=r,d(f.elements.viewport,{height:f.options.viewport.height+"px"})):"h"===n&&50<=e&&e<=h&&(d(l,{width:e+"px"}),f.options.boundary.width+=a,d(f.elements.boundary,{width:f.options.boundary.width+"px"}),f.options.viewport.width+=a,d(f.elements.viewport,{width:f.options.viewport.width+"px"}));F.call(f);K.call(f);z.call(f);C.call(f);g=b;H=c}function c(){e=!1;window.removeEventListener("mousemove",b);window.removeEventListener("touchmove",
b);window.removeEventListener("mouseup",c);window.removeEventListener("touchend",c);document.body.style[B]=""}var f=this,l=document.createElement("div"),e=!1,n,H,g,h,k;p(l,"cr-resizer");d(l,{width:this.options.viewport.width+"px",height:this.options.viewport.height+"px"});if(this.options.resizeControls.height){var m=document.createElement("div");p(m,"cr-resizer-vertical");l.appendChild(m)}if(this.options.resizeControls.width){var r=document.createElement("div");p(r,"cr-resizer-horisontal");l.appendChild(r)}m&&
(m.addEventListener("mousedown",a),m.addEventListener("touchstart",a));r&&(r.addEventListener("mousedown",a),r.addEventListener("touchstart",a));this.elements.boundary.appendChild(l)}function A(a){if(this.options.enableZoom){var b=this.elements.zoomer;a=x(a,4);b.value=Math.max(b.min,Math.min(b.max,a))}}function V(){function a(){O.call(c,{value:parseFloat(d.value),origin:new G(c.elements.preview),viewportRect:c.elements.viewport.getBoundingClientRect(),transform:q.parse(c.elements.preview)})}function b(b){if("ctrl"===
c.options.mouseWheelZoom&&!0!==b.ctrlKey)return 0;var f=c._currentZoom+(b.wheelDelta?b.wheelDelta/1200:b.deltaY?b.deltaY/1060:b.detail?b.detail/-60:0)*c._currentZoom;b.preventDefault();A.call(c,f);a.call(c)}var c=this,f=c.elements.zoomerWrap=document.createElement("div"),d=c.elements.zoomer=document.createElement("input");p(f,"cr-slider-wrap");p(d,"cr-slider");d.type="range";d.step="0.0001";d.value=1;d.style.display=c.options.showZoomer?"":"none";d.setAttribute("aria-label","zoom");c.element.appendChild(f);
f.appendChild(d);c._currentZoom=1;c.elements.zoomer.addEventListener("input",a);c.elements.zoomer.addEventListener("change",a);c.options.mouseWheelZoom&&(c.elements.boundary.addEventListener("mousewheel",b),c.elements.boundary.addEventListener("DOMMouseScroll",b))}function O(a){function b(){var a={};a[u]=f.toString();a[E]=e.toString();d(c.elements.preview,a)}var c=this,f=a?a.transform:q.parse(c.elements.preview),l=a?a.viewportRect:c.elements.viewport.getBoundingClientRect(),e=a?a.origin:new G(c.elements.preview);
c._currentZoom=a?a.value:c._currentZoom;f.scale=c._currentZoom;c.elements.zoomer.setAttribute("aria-valuenow",c._currentZoom);b();c.options.enforceBoundary&&(l=W.call(c,l),a=l.translate,l=l.origin,f.x>=a.maxX&&(e.x=l.minX,f.x=a.maxX),f.x<=a.minX&&(e.x=l.maxX,f.x=a.minX),f.y>=a.maxY&&(e.y=l.minY,f.y=a.maxY),f.y<=a.minY&&(e.y=l.maxY,f.y=a.minY));b();Y.call(c);C.call(c)}function W(a){var b=this._currentZoom,c=a.width;a=a.height;var f=this.elements.boundary.clientWidth/2,d=this.elements.boundary.clientHeight/
2,e=this.elements.preview.getBoundingClientRect(),n=e.width;e=e.height;var g=c/2,h=a/2;f=-1*(g/b-f);d=-1*(h/b-d);g*=1/b;h*=1/b;return{translate:{maxX:f,minX:f-(1/b*n-1/b*c),maxY:d,minY:d-(1/b*e-1/b*a)},origin:{maxX:1/b*n-g,minX:g,maxY:1/b*e-h,minY:h}}}function z(){var a=this._currentZoom,b=this.elements.preview.getBoundingClientRect(),c=this.elements.viewport.getBoundingClientRect(),f=q.parse(this.elements.preview.style[u]),l=new G(this.elements.preview),e=c.left-b.left+c.width/2;b=(c.top-b.top+c.height/
2)/a;e/=a;c=(b-l.y)*(1-a);f.x-=(e-l.x)*(1-a);f.y-=c;a={};a[E]=e+"px "+b+"px";a[u]=f.toString();d(this.elements.preview,a)}function Z(){function a(a,b){var c=n.elements.preview.getBoundingClientRect(),f=r.y+b,d=r.x+a;n.options.enforceBoundary?(D.top>c.top+b&&D.bottom<c.bottom+b&&(r.y=f),D.left>c.left+a&&D.right<c.right+a&&(r.x=d)):(r.y=f,r.x=d)}function b(a){n.elements.preview.setAttribute("aria-grabbed",a);n.elements.boundary.setAttribute("aria-dropeffect",a?"move":"none")}function c(b){var c={};
a(b[0],b[1]);c[u]=r.toString();d(n.elements.preview,c);F.call(n);document.body.style[B]="";z.call(n);C.call(n);p=0}function f(a){if(void 0===a.button||0===a.button)a.preventDefault(),g||(g=!0,h=a.pageX,k=a.pageY,a.touches&&(a=a.touches[0],h=a.pageX,k=a.pageY),b(g),r=q.parse(n.elements.preview),window.addEventListener("mousemove",l),window.addEventListener("touchmove",l),window.addEventListener("mouseup",e),window.addEventListener("touchend",e),document.body.style[B]="none",D=n.elements.viewport.getBoundingClientRect())}
function l(b){b.preventDefault();var c=b.pageX,f=b.pageY;b.touches&&(f=b.touches[0],c=f.pageX,f=f.pageY);var e=c-h,l=f-k,g={};"touchmove"===b.type&&1<b.touches.length?(c=b.touches[0],b=b.touches[1],b=Math.sqrt((c.pageX-b.pageX)*(c.pageX-b.pageX)+(c.pageY-b.pageY)*(c.pageY-b.pageY)),p||(p=b/n._currentZoom),A.call(n,b/p),m(n.elements.zoomer)):(a(e,l),g[u]=r.toString(),d(n.elements.preview,g),F.call(n),k=f,h=c)}function e(){g=!1;b(g);window.removeEventListener("mousemove",l);window.removeEventListener("touchmove",
l);window.removeEventListener("mouseup",e);window.removeEventListener("touchend",e);document.body.style[B]="";z.call(n);C.call(n);p=0}var n=this,g=!1,h,k,p,D,r;n.elements.overlay.addEventListener("mousedown",f);n.elements.viewport.addEventListener("keydown",function(a){function b(a){switch(a){case 37:return[1,0];case 38:return[0,1];case 39:return[-1,0];case 40:return[0,-1]}}if(!a.shiftKey||38!==a.keyCode&&40!==a.keyCode)n.options.enableKeyMovement&&37<=a.keyCode&&40>=a.keyCode&&(a.preventDefault(),
a=b(a.keyCode),r=q.parse(n.elements.preview),document.body.style[B]="none",D=n.elements.viewport.getBoundingClientRect(),c(a));else{var f=0;f=38===a.keyCode?parseFloat(n.elements.zoomer.value,10)+parseFloat(n.elements.zoomer.step,10):parseFloat(n.elements.zoomer.value,10)-parseFloat(n.elements.zoomer.step,10);n.setZoom(f)}});n.elements.overlay.addEventListener("touchstart",f)}function F(){if(this.elements){var a=this.elements.boundary.getBoundingClientRect(),b=this.elements.preview.getBoundingClientRect();
d(this.elements.overlay,{width:b.width+"px",height:b.height+"px",top:b.top-a.top+"px",left:b.left-a.left+"px"})}}function C(){var a=this.get();if(0<this.elements.preview.offsetHeight&&0<this.elements.preview.offsetWidth)if(this.options.update.call(this,a),this.$&&"undefined"===typeof Prototype)this.$(this.element).trigger("update.croppie",a);else{if(window.CustomEvent)var b=new CustomEvent("update",{detail:a});else b=document.createEvent("CustomEvent"),b.initCustomEvent("update",!0,!0,a);this.element.dispatchEvent(b)}}
function L(){var a={},b=this.elements.preview,c=new q(0,0,1);var f=new G;if(0<this.elements.preview.offsetHeight&&0<this.elements.preview.offsetWidth&&!this.data.bound){this.data.bound=!0;a[u]=c.toString();a[E]=f.toString();a.opacity=1;d(b,a);f=this.elements.preview.getBoundingClientRect();this._originalImageWidth=f.width;this._originalImageHeight=f.height;this.data.orientation=t(this.elements.img);this.options.enableZoom?K.call(this,!0):this._currentZoom=1;c.scale=this._currentZoom;a[u]=c.toString();
d(b,a);if(this.data.points.length){a=this.data.points;if(4!==a.length)throw"Croppie - Invalid number of points supplied: "+a;b=a[2]-a[0];f=this.elements.viewport.getBoundingClientRect();var e=this.elements.boundary.getBoundingClientRect();b=f.width/b;c=-1*a[1]+(f.top-e.top);f=-1*a[0]+(f.left-e.left);e={};e[E]=a[0]+"px "+a[1]+"px";e[u]=(new q(f,c,b)).toString();d(this.elements.preview,e);A.call(this,b);this._currentZoom=b}else a=this.elements.preview.getBoundingClientRect(),b=this.elements.viewport.getBoundingClientRect(),
c=this.elements.boundary.getBoundingClientRect(),a=new q(b.left-c.left-(a.width-b.width)/2,b.top-c.top-(a.height-b.height)/2,this._currentZoom),d(this.elements.preview,u,a.toString());z.call(this);F.call(this)}}function K(a){var b=0,c=this.options.maxZoom||1.5,f=this.elements.zoomer,d=parseFloat(f.value),e=this.elements.boundary.getBoundingClientRect(),g=N(this.elements.img,this.data.orientation),h=this.elements.viewport.getBoundingClientRect();this.options.enforceBoundary&&(b=h.width/g.width,h=h.height/
g.height,b=Math.max(b,h));b>=c&&(c=b+1);f.min=x(b,4);f.max=x(c,4);!a&&(d<f.min||d>f.max)?A.call(this,d<f.min?f.min:f.max):a&&(a=Math.max(e.width/g.width,e.height/g.height),a=null!==this.data.boundZoom?this.data.boundZoom:a,A.call(this,a));m(f)}function aa(a){var b=this.elements.canvas,c=this.elements.img,f=b.getContext("2d"),d=this.options.enableExif&&window.EXIF;a=this.options.enableOrientation&&a;f.clearRect(0,0,b.width,b.height);b.width=c.width;b.height=c.height;d&&!a?(a=t(c),w(b,c,parseInt(a||
0,10))):a&&w(b,c,a)}function M(a){var b=a.points,c=parseInt(b[0],10),f=parseInt(b[1],10),d=parseInt(b[2],10);b=parseInt(b[3],10);d-=c;b-=f;var e=a.circle,g=document.createElement("canvas"),h=g.getContext("2d"),k=a.outputWidth||d,m=a.outputHeight||b;g.width=k;g.height=m;a.backgroundColor&&(h.fillStyle=a.backgroundColor,h.fillRect(0,0,k,m));!1!==this.options.enforceBoundary&&(d=Math.min(d,this._originalImageWidth),b=Math.min(b,this._originalImageHeight));h.drawImage(this.elements.preview,c,f,d,b,0,
0,k,m);e&&(h.fillStyle="#fff",h.globalCompositeOperation="destination-in",h.beginPath(),h.arc(g.width/2,g.height/2,g.width/2,0,2*Math.PI,!0),h.closePath(),h.fill());return g}function ba(a){var b=this;return new Promise(function(c,f){M.call(b,a).toBlob(function(a){c(a)},a.format,a.quality)})}function ca(a){this.elements.img.parentNode&&(Array.prototype.forEach.call(this.elements.img.classList,function(b){a.classList.add(b)}),this.elements.img.parentNode.replaceChild(a,this.elements.img),this.elements.preview=
a);this.elements.img=a}function R(a,b){var c=this,f=[],d=null;var e=c.options.enableExif&&window.EXIF;if("string"===typeof a){var h=a;a={}}else if(Array.isArray(a))f=a.slice();else{if("undefined"===typeof a&&c.data.url)return L.call(c),C.call(c),null;h=a.url;f=a.points||[];d="undefined"===typeof a.zoom?null:a.zoom}c.data.bound=!1;c.data.url=h||c.data.url;c.data.boundZoom=d;return g(h,e).then(function(d){ca.call(c,d);if(f.length)c.options.relative&&(f=[f[0]*d.naturalWidth/100,f[1]*d.naturalHeight/
100,f[2]*d.naturalWidth/100,f[3]*d.naturalHeight/100]);else{d=N(d);var e=c.elements.viewport.getBoundingClientRect(),g=e.width/e.height;if(d.width/d.height>g){var l=d.height;e=l*g}else e=d.width,l=d.height/g;g=(d.width-e)/2;d=(d.height-l)/2;c.data.points=[g,d,g+e,d+l]}c.data.points=f.map(function(a){return parseFloat(a)});c.options.useCanvas&&aa.call(c,a.orientation||1);L.call(c);C.call(c);b&&b()}).catch(function(a){console.error("Croppie:"+a)})}function x(a,b){return parseFloat(a).toFixed(b||0)}
function S(){var a=this.elements.preview.getBoundingClientRect(),b=this.elements.viewport.getBoundingClientRect(),c=b.left-a.left;a=b.top-a.top;var d=c+this.elements.viewport.offsetWidth+(b.width-this.elements.viewport.offsetWidth)/2;b=a+this.elements.viewport.offsetHeight+(b.height-this.elements.viewport.offsetHeight)/2;var e=this._currentZoom;if(Infinity===e||isNaN(e))e=1;var g=this.options.enforceBoundary?0:Number.NEGATIVE_INFINITY;c=Math.max(g,c/e);a=Math.max(g,a/e);d=Math.max(g,d/e);b=Math.max(g,
b/e);return{points:[x(c),x(a),x(d),x(b)],zoom:e,orientation:this.data.orientation}}function da(a){var b=this,c=S.call(b),f=h(h({},ea),h({},a)),e="string"===typeof a?a:f.type||"base64";a=f.size||"viewport";var g=f.format,k=f.quality,m=f.backgroundColor;f="boolean"===typeof f.circle?f.circle:"circle"===b.options.viewport.type;var q=b.elements.viewport.getBoundingClientRect(),t=q.width/q.height;"viewport"===a?(c.outputWidth=q.width,c.outputHeight=q.height):"object"===typeof a&&(a.width&&a.height?(c.outputWidth=
a.width,c.outputHeight=a.height):a.width?(c.outputWidth=a.width,c.outputHeight=a.width/t):a.height&&(c.outputWidth=a.height*t,c.outputHeight=a.height));-1<fa.indexOf(g)&&(c.format="image/"+g,c.quality=k);c.circle=f;c.url=b.data.url;c.backgroundColor=m;return new Promise(function(a,f){switch(e.toLowerCase()){case "rawcanvas":a(M.call(b,c));break;case "canvas":case "base64":f=M.call(b,c).toDataURL(c.format,c.quality);a(f);break;case "blob":ba.call(b,c).then(a);break;default:f=c.points;var g=document.createElement("div"),
h=document.createElement("img"),l=f[2]-f[0],k=f[3]-f[1];p(g,"croppie-result");g.appendChild(h);d(h,{left:-1*f[0]+"px",top:-1*f[1]+"px"});h.src=c.url;d(g,{width:l+"px",height:k+"px"});a(g)}})}function v(a,b){if(-1<a.className.indexOf("croppie-container"))throw Error("Croppie: Can't initialize croppie more than once");this.element=a;this.options=h(h({},v.defaults),b);if("img"===this.element.tagName.toLowerCase()){a=this.element;p(a,"cr-original-image");b={"aria-hidden":"true",alt:""};for(var c in b)a.setAttribute(c,
b[c]);c=document.createElement("div");this.element.parentNode.appendChild(c);c.appendChild(a);this.element=c;this.options.url=this.options.url||a.src}var f=this.options.viewport.type?"cr-vp-"+this.options.viewport.type:null;this.options.useCanvas=this.options.enableOrientation||this.options.enableExif&&window.EXIF;this.data={};this.elements={};c=this.elements.boundary=document.createElement("div");a=this.elements.viewport=document.createElement("div");this.elements.img=document.createElement("img");
b=this.elements.overlay=document.createElement("div");this.options.useCanvas?(this.elements.canvas=document.createElement("canvas"),this.elements.preview=this.elements.canvas):this.elements.preview=this.elements.img;p(c,"cr-boundary");c.setAttribute("aria-dropeffect","none");var e=this.options.boundary.width;var g=this.options.boundary.height;d(c,{width:e+(isNaN(e)?"":"px"),height:g+(isNaN(g)?"":"px")});p(a,"cr-viewport");f&&p(a,f);d(a,{width:this.options.viewport.width+"px",height:this.options.viewport.height+
"px"});a.setAttribute("tabindex",0);p(this.elements.preview,"cr-image");f=this.elements.preview;e={alt:"preview","aria-grabbed":"false"};for(var k in e)f.setAttribute(k,e[k]);p(b,"cr-overlay");this.element.appendChild(c);c.appendChild(this.elements.preview);c.appendChild(a);c.appendChild(b);p(this.element,"croppie-container");this.options.customClass&&p(this.element,this.options.customClass);Z.call(this);this.options.enableZoom&&V.call(this);this.options.enableResize&&U.call(this);this.options.url&&
(k={url:this.options.url,points:this.options.points},delete this.options.url,delete this.options.points,R.call(this,k))}"function"!==typeof Promise&&!function(a){function b(a,b){return function(){a.apply(b,arguments)}}function c(a){if("object"!==typeof this)throw new TypeError("Promises must be constructed via new");if("function"!==typeof a)throw new TypeError("not a function");this._value=this._state=null;this._deferreds=[];m(a,b(e,this),b(g,this))}function d(a){var b=this;return null===this._state?
void this._deferreds.push(a):void q(function(){var c=b._state?a.onFulfilled:a.onRejected;if(null===c)return void(b._state?a.resolve:a.reject)(b._value);try{var d=c(b._value)}catch(J){return void a.reject(J)}a.resolve(d)})}function e(a){try{if(a===this)throw new TypeError("A promise cannot be resolved with itself.");if(a&&("object"===typeof a||"function"===typeof a)){var c=a.then;if("function"===typeof c)return void m(b(c,a),b(e,this),b(g,this))}this._state=!0;this._value=a;h.call(this)}catch(X){g.call(this,
X)}}function g(a){this._state=!1;this._value=a;h.call(this)}function h(){for(var a=0,b=this._deferreds.length;b>a;a++)d.call(this,this._deferreds[a]);this._deferreds=null}function k(a,b,c,d){this.onFulfilled="function"===typeof a?a:null;this.onRejected="function"===typeof b?b:null;this.resolve=c;this.reject=d}function m(a,b,c){var d=!1;try{a(function(a){d||(d=!0,b(a))},function(a){d||(d=!0,c(a))})}catch(J){d||(d=!0,c(J))}}var p=setTimeout,q="function"===typeof setImmediate&&setImmediate||function(a){p(a,
1)},t=Array.isArray||function(a){return"[object Array]"===Object.prototype.toString.call(a)};c.prototype["catch"]=function(a){return this.then(null,a)};c.prototype.then=function(a,b){var f=this;return new c(function(c,e){d.call(f,new k(a,b,c,e))})};c.all=function(){var a=Array.prototype.slice.call(1===arguments.length&&t(arguments[0])?arguments[0]:arguments);return new c(function(b,c){function d(e,g){try{if(g&&("object"===typeof g||"function"===typeof g)){var h=g.then;if("function"===typeof h)return void h.call(g,
function(a){d(e,a)},c)}a[e]=g;0===--f&&b(a)}catch(ha){c(ha)}}if(0===a.length)return b([]);for(var f=a.length,e=0;e<a.length;e++)d(e,a[e])})};c.resolve=function(a){return a&&"object"===typeof a&&a.constructor===c?a:new c(function(b){b(a)})};c.reject=function(a){return new c(function(b,c){c(a)})};c.race=function(a){return new c(function(b,c){for(var d=0,f=a.length;f>d;d++)a[d].then(b,c)})};c._setImmediateFn=function(a){q=a};"undefined"!==typeof module&&module.exports?module.exports=c:a.Promise||(a.Promise=
c)}(this);"function"!==typeof window.CustomEvent&&function(){function a(a,c){c=c||{bubbles:!1,cancelable:!1,detail:void 0};var b=document.createEvent("CustomEvent");b.initCustomEvent(a,c.bubbles,c.cancelable,c.detail);return b}a.prototype=window.Event.prototype;window.CustomEvent=a}();HTMLCanvasElement.prototype.toBlob||Object.defineProperty(HTMLCanvasElement.prototype,"toBlob",{value:function(a,b,c){c=atob(this.toDataURL(b,c).split(",")[1]);for(var d=c.length,e=new Uint8Array(d),g=0;g<d;g++)e[g]=
c.charCodeAt(g);a(new Blob([e],{type:b||"image/png"}))}});var Q=["Webkit","Moz","ms"],P=document.createElement("div").style,T=[1,8,3,6],ia=[2,7,4,5];var u=k("transform");var E=k("transformOrigin");var B=k("userSelect");var ja={translate3d:{suffix:", 0px"},translate:{suffix:""}},q=function(a,b,c){this.x=parseFloat(a);this.y=parseFloat(b);this.scale=parseFloat(c)};q.parse=function(a){return a.style?q.parse(a.style[u]):-1<a.indexOf("matrix")||-1<a.indexOf("none")?q.fromMatrix(a):q.fromString(a)};q.fromMatrix=
function(a){var b=a.substring(7).split(",");b.length&&"none"!==a||(b=[1,0,0,1,0,0]);return new q(parseInt(b[4],10),parseInt(b[5],10),parseFloat(b[0]))};q.fromString=function(a){var b=a.split(") ");a=b[0].substring(v.globals.translate.length+1).split(",");b=1<b.length?b[1].substring(6):1;return new q(1<a.length?a[0]:0,1<a.length?a[1]:0,b)};q.prototype.toString=function(){return v.globals.translate+"("+this.x+"px, "+this.y+"px"+(ja[v.globals.translate].suffix||"")+") scale("+this.scale+")"};var G=function(a){a&&
a.style[E]?(a=a.style[E].split(" "),this.x=parseFloat(a[0]),this.y=parseFloat(a[1])):this.y=this.x=0};G.prototype.toString=function(){return this.x+"px "+this.y+"px"};var Y=function(a,b,c){var d;return function(){var f=this,e=arguments,g=c&&!d;clearTimeout(d);d=setTimeout(function(){d=null;c||a.apply(f,e)},b);g&&a.apply(f,e)}}(F,500),ea={type:"canvas",format:"png",quality:1},fa=["jpeg","webp","png"];if(window.jQuery){var y=window.jQuery;y.fn.croppie=function(a){if("string"===typeof a){var b=Array.prototype.slice.call(arguments,
1),c=y(this).data("croppie");return"get"===a?c.get():"result"===a?c.result.apply(c,b):"bind"===a?c.bind.apply(c,b):this.each(function(){var c=y(this).data("croppie");if(c){var d=c[a];if(y.isFunction(d))d.apply(c,b),"destroy"===a&&y(this).removeData("croppie");else throw"Croppie "+a+" method not found";}})}return this.each(function(){var b=new v(this,a);b.$=y;y(this).data("croppie",b)})}}v.defaults={viewport:{width:100,height:100,type:"square"},boundary:{},orientationControls:{enabled:!0,leftClass:"",
rightClass:""},resizeControls:{width:!0,height:!0},customClass:"",showZoomer:!0,enableZoom:!0,enableResize:!1,mouseWheelZoom:!0,enableExif:!1,enforceBoundary:!0,enableOrientation:!1,enableKeyMovement:!0,update:function(){}};v.globals={translate:"translate3d"};h(v.prototype,{bind:function(a,b){return R.call(this,a,b)},get:function(){var a=S.call(this),b=a.points;this.options.relative&&(b[0]/=this.elements.img.naturalWidth/100,b[1]/=this.elements.img.naturalHeight/100,b[2]/=this.elements.img.naturalWidth/
100,b[3]/=this.elements.img.naturalHeight/100);return a},result:function(a){return da.call(this,a)},refresh:function(){L.call(this)},setZoom:function(a){A.call(this,a);m(this.elements.zoomer)},rotate:function(a){if(!this.options.useCanvas||!this.options.enableOrientation)throw"Croppie: Cannot rotate without enableOrientation && EXIF.js included";var b=this.elements.canvas,c=this.data,d=this.data.orientation,e=-1<T.indexOf(d)?T:ia;d=e.indexOf(d);c.orientation=e[(e.length+d+a/90%e.length%e.length)%
e.length];w(b,this.elements.img,this.data.orientation);K.call(this);O.call(this);copy=null},destroy:function(){this.element.removeChild(this.elements.boundary);var a=this.element;a.classList?a.classList.remove("croppie-container"):a.className=a.className.replace("croppie-container","");this.options.enableZoom&&this.element.removeChild(this.elements.zoomerWrap);delete this.elements}});e.Croppie=window.Croppie=v});
