var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,e,b){a instanceof String&&(a=String(a));for(var f=a.length,g=0;g<f;g++){var l=a[g];if(e.call(b,l,g,a))return{i:g,v:l}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,e,b){a!=Array.prototype&&a!=Object.prototype&&(a[e]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,e,b,f){if(e){b=$jscomp.global;a=a.split(".");for(f=0;f<a.length-1;f++){var g=a[f];g in b||(b[g]={});b=b[g]}a=a[a.length-1];f=b[a];e=e(f);e!=f&&null!=e&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:e})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");var editor,saved=!0,tested=!0,gladid,user,nick,hash,pieces,loadGlad=!1,wannaSave=!1,tutoState=0;
$(document).ready(function(){$("#header-editor").addClass("here");$.post("back_login.php",{action:"GET"}).done(function(a){"NULL"!=a?(user=JSON.parse(a),$("#login").html(user.nome),"1"==user.tutor&&showTutorial(),a=new Image,a.src=user.foto,$("#profile-icon img").attr("src",a.src),a.onerror=function(){$("#profile-icon img").attr("src","data:image/gif;base64,R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=")},editor.setTheme("ace/theme/"+user.theme),editor.setFontSize(user.font+"px"),$("#newglad").length?($("#newglad").remove(),
$("#fog-skin").fadeIn()):loadGlad||$("#open").click()):$("#fog-skin").fadeIn()});$(".fog").hide();$("#glad-code").length&&(loadGlad={id:$("#glad-code #idglad").html(),name:$("#glad-code #name").html(),user:$("#glad-code #user").html(),code:$("#glad-code #code").html(),vstr:$("#glad-code #vstr").html(),vagi:$("#glad-code #vagi").html(),vint:$("#glad-code #vint").html(),skin:$("#glad-code #skin").html()},nick=$("#glad-code #user").html(),$("#glad-code").remove());load_glad_generator($("#fog-skin"));
$("#header-container").addClass("small");load_editor();editor.focus();$("#float-card .glad-preview").click(function(){$("#skin").click()});$("#panel-left-opener").click(function(){$(this).hasClass("open")?($("#panel-left").width(0).addClass("hidden"),$(this).removeClass("open")):($("#panel-left").width(65).removeClass("hidden"),$(this).addClass("open"))});$("#profile-icon").click(function(){user?window.location.href="profile":googleLogin().then(function(a){window.location.href="profile"})});$("#new").click(function(){saved?
window.location.href="newglad":showDialog("Deseja criar um novo gladiador e perder as altera\u00e7\u00f5es feitas no gladiador atual?",["Sim","N\u00e3o"]).then(function(a){"Sim"==a&&(saved=!0,window.location.href="newglad")})});$("#open").click(function(){if(!$(this).hasClass("disabled"))if(user){$("#fog-glads").fadeIn();$("#fog-glads .glad-preview").remove();$("#fog-glads #btn-glad-open").prop("disabled",!0);var a=$("<div id='template'></div>").load("glad-card-template.html",function(){});$.post("back_glad.php",
{action:"GET"}).done(function(g){g=JSON.parse(g);for(var d in g)$("#fog-glads .glad-card-container").append("<div class='glad-preview'></div>");$("#fog-glads .glad-card-container .glad-preview").html(a);for(d in g)setGladImage(d,g[d].skin),$("#fog-glads .glad-preview .info .glad span").eq(d).html(g[d].name),$("#fog-glads .glad-preview .info .attr .str span").eq(d).html(g[d].vstr),$("#fog-glads .glad-preview .info .attr .agi span").eq(d).html(g[d].vagi),$("#fog-glads .glad-preview .info .attr .int span").eq(d).html(g[d].vint),
$("#fog-glads .glad-preview").eq(d).data("id",g[d].id),$("#fog-glads .glad-preview .delete").eq(d).click(function(){var a=$(this).parents(".glad-preview");showDialog("Deseja excluir o gladiador <span class='highlight'>"+a.find(".glad span").html()+"</span>?",["Sim","N\u00e3o"]).then(function(d){"Sim"==d&&(a.fadeOut(function(){a.remove()}),$.post("back_glad.php",{action:"DELETE",id:a.data("id")}).done(function(a){}))})});$("#fog-glads .glad-preview .code .button").remove();$("#fog-glads .glad-preview").click(function(){$("#fog-glads #btn-glad-open").removeProp("disabled");
$("#fog-glads .glad-preview").removeClass("selected");$(this).addClass("selected")});$("#fog-glads .glad-preview").dblclick(function(){$("#fog-glads #btn-glad-open").click()})})}else showDialog("Voc\u00ea precisa fazer LOGIN no sistema para visualizar seus gladiadores",["Cancelar","LOGIN"]).then(function(a){"LOGIN"==a&&googleLogin().then(function(a){user=a.email;setLoadGlad();$("#login").html(a.nome).off().click(function(){window.location.href="profile"})})})});$("#fog-glads #btn-glad-cancel").click(function(){$("#fog-glads").hide()});
$("#fog-glads #btn-glad-open").click(function(){if(saved){var a=$("#fog-glads .glad-preview.selected").data("id");window.location.href="glad-"+a}else a=$("#fog-glads .glad-preview.selected .glad span").html(),showDialog("Deseja abrir o gladiador <span class='highlight'>"+a+"</span> para edi\u00e7\u00e3o? Todas altera\u00e7\u00f5es no gladiador atual ser\u00e3o perdidas",["Sim","N\u00e3o"]).then(function(a){"Sim"==a&&(saved=!0,a=$("#fog-glads .glad-preview.selected").data("id"),window.location.href=
"glad-"+a)})});$("#save").click(function(){if(!$(this).hasClass("disabled"))if(user)if(setLoadGlad(),tested){var a="INSERT";gladid&&(a="UPDATE");var b=$("#distribuicao #nome").val();$.post("back_glad.php",{action:a,id:gladid,nome:b,vstr:$("#float-card .glad-preview .info .attr .str span").html(),vagi:$("#float-card .glad-preview .info .attr .agi span").html(),vint:$("#float-card .glad-preview .info .attr .int span").html(),skin:JSON.stringify(pieces)}).done(function(d){-1!=d.search("LIMIT")?showMessage("Voc\u00ea n\u00e3o pode possuir mais de <span class='highlight'>"+
JSON.parse(d).LIMIT+"</span> gladiadores simultaneamente. Aumente seu n\u00edvel de mestre para desbloquear mais gladiadores."):"EXISTS"==d?showMessage("O nome <span class='highlight'>"+b+"</span> j\u00e1 est\u00e1 sendo usado por outro gladiador"):"INVALID"==d?showMessage("CHEATER"):-1!=d.search("ID")&&(gladid=JSON.parse(d).ID,"INSERT"==a?showDialog("O gladiador <span class='highlight'>"+b+"</span> foi criado e gravado em seu perfil. Deseja inscrev\u00ea-lo para competir contra outros gladiadores?",
["Sim","Agora n\u00e3o"]).then(function(a){"Sim"==a&&window.open("battle")}):showMessage("Gladiador <span class='highlight'>"+b+"</span> gravado"),saved=!0)})}else showDialog("Voc\u00ea precisar testar o gladiador <span class='highlight'>"+loadGlad.name+"</span> ao menos uma vez antes de salv\u00e1-lo. Deseja fazer isso agora?",["Sim","N\u00e3o"]).then(function(a){"Sim"==a&&($("#test").click(),wannaSave=!0)});else showDialog("Voc\u00ea precisa fazer LOGIN no sistema para salvar seu gladiador",["Cancelar",
"LOGIN"]).then(function(a){"LOGIN"==a&&googleLogin().then(function(a){user=a.email;setLoadGlad();$("#login").html(a.nome).off().click(function(){window.location.href="profile"})})})});$("#skin").click(function(){$("#fog-skin").fadeIn()});$("#test").click(function(){function a(){if(2==tutoState)tutoState=3,showTutorial();else if(9==tutoState||10==tutoState||12==tutoState||14==tutoState||16==tutoState||18==tutoState||20==tutoState||22==tutoState)showTutorial();else if(setLoadGlad(),!$(this).hasClass("disabled")){$("#fog-battle").fadeIn();
var a=$("#float-card .glad-preview .glad span").html();$("#fog-battle h3 span").html(a)}}var b=editor.getValue();-1!=b.search("setup()")?showDialog("A fun\u00e7\u00e3o <span class='highlight'>setup</span> s\u00f3 deve ser usada nos modos de batalha cl\u00e1ssicos (aqueles que voc\u00ea faz upload manual do c\u00f3digo). Posso remover este trecho para voc\u00ea?",["N\u00c3O","Pode"]).then(function(d){"Pode"==d&&(editor.setValue(b.replace(/setup\(\)[\s\n]*?{[\w\W]*?}/g,"")),setTimeout(function(){a()},
300))}):a()});var a={Wanderer:{difficulty:1,filename:"Wanderer"},Runner:{difficulty:1,filename:"Runner"},Blinker:{difficulty:1,filename:"Blinker"},Arch:{difficulty:2,filename:"Arch"},Patient:{difficulty:2,filename:"Patient"},Warrior:{difficulty:2,filename:"Warrior"},Mage:{difficulty:2,filename:"Mage"},Rogue:{difficulty:2,filename:"Rogue"},Archie:{difficulty:3,filename:"Archie"},"War Maker":{difficulty:3,filename:"WarMaker"},Magnus:{difficulty:3,filename:"Magnus"},Rouge:{difficulty:3,filename:"Rouge"}},
e=["","one","two","three"],b;for(b in a)$("#fog-battle #list").append("<div class='glad'><div class='name'></div><div class='diff'><div class='bar'></div><div class='bar'></div><div class='bar'></div></div></div>"),$("#fog-battle #list .glad").last().data("filename",a[b].filename),$("#fog-battle #list .glad .name").last().html(b),$("#fog-battle #list .glad .diff").last().addClass(e[a[b].difficulty]);$("#fog-battle #list .glad").click(function(){var a="samples/gladbots/"+$(this).data("filename")+".c",
b;if($(this).hasClass("selected"))$(this).removeClass("selected"),$("#fog-battle .glad-card-container").html("");else if(4>$("#fog-battle #list .glad.selected").length){$(this).addClass("selected");var d=$("<div id='template'></div>").load("glad-card-template.html",function(){$("#fog-battle .glad-card-container").html("<div class='glad-preview'></div>");$("#fog-battle .glad-card-container .glad-preview").html(d);getGladFromFile(a).then(function(a){fetchSpritesheet(a.skin).then(function(a){$("#fog-battle .glad-preview .image").html(getSpriteThumb(a,
"walk","down"))});$("#fog-battle .glad-preview .info .glad span").html(a.name);$("#fog-battle .glad-preview .info .attr .str span").html(a.vstr);$("#fog-battle .glad-preview .info .attr .agi span").html(a.vagi);$("#fog-battle .glad-preview .info .attr .int span").html(a.vint);b=a.code});$("#fog-battle .glad-preview .delete").remove();$("#fog-battle .glad-preview .code .button").click(function(){$("body").append("<div id='fog'><div id='code-box'><pre class='line-numbers language-c'><code class='language-c'>"+
b+"</code></pre><div id='button-container'><button id='close' class='button'>Fechar</button></div></div></div>");Prism.highlightElement($("code")[0]);$("#code-box #close").click(function(a){$("#fog").remove()})})})}if(0<$("#fog-battle #list .glad.selected").length){var h=$("#fog-battle #list .glad.selected").length;$("#fog-battle #btn-battle").removeProp("disabled");$("#fog-battle #list-title span").html(h+" selecionados")}else $("#fog-battle #btn-battle").prop("disabled",!0),$("#fog-battle #list-title span").html("")});
var f;$("#fog-battle #btn-cancel").click(function(){f&&f.isActive()?(f.kill(),ajaxcall&&ajaxcall.abort()):$("#fog-battle").hide()});$("#fog-battle #btn-battle").click(function(){f=new progressButton($(this),["Executando batalha...","Aguardando resposta do servidor"]);var b=[],e=0;$.each($("#fog-battle #list .glad.selected"),function(){var d="samples/gladbots/"+a[$(this).find(".name").html()].filename+".c";getGladFromFile(d).then(function(a){b.push(a.code);e++})});var d=setInterval(function(){e==$("#fog-battle #list .glad.selected").length&&
(b.push(loadGlad.code),clearInterval(d),runSimulation({glads:b,savecode:!0,single:!0}).then(function(a){"ERROR"!=a&&(showDialog("Deseja visualizar a batalha?",["Sim","N\u00e3o"]).then(function(d){"Sim"==d?window.open("play/"+a):$.post("back_log.php",{action:"DELETE",hash:a});wannaSave&&(showDialog("Gladiador testado com sucesso. Deseja grav\u00e1-lo?",["Sim","N\u00e3o"]).then(function(a){"Sim"==a&&$("#save").click()}),wannaSave=!1);4!=tutoState&&5!=tutoState&&6!=tutoState&&8!=tutoState&&11!=tutoState&&
13!=tutoState&&15!=tutoState&&17!=tutoState&&19!=tutoState&&21!=tutoState&&23!=tutoState||showTutorial()}),tested=!0);f.kill();$("#fog-battle").hide()}))},10)});$("#download").click(function(){if(!$(this).hasClass("disabled")){var a=$("#distribuicao #nome").val(),b=$("#float-card .glad-preview .attr .str span").html(),d=$("#float-card .glad-preview .attr .agi span").html(),h=$("#float-card .glad-preview .attr .int span").html();showInput("Nome do arquivo:",a+".c").then(function(e){e&&$.post("back_skin.php",
{action:"SAVE",skin:JSON.stringify(pieces)}).done(function(c){hash=c;download(e,'setup(){\n    setName("'+a+'");\n    setSTR('+b+");\n    setAGI("+d+");\n    setINT("+h+');\n    setSpritesheet("'+hash+'");\n}\n\n'+editor.getValue())})})}});$("#settings").click(function(){var a="ambiance chaos chrome clouds clouds_midnight cobalt crimson_editor dawn dracula dreamweaver eclipse github gob gruvbox idle_fingers iplastic katzenmilch kr_theme kuroir merbivore merbivore_soft mono_industrial monokai pastel_on_dark solarized_dark solarized_light sqlserver terminal textmate tomorrow tomorrow_night_blue tomorrow_night_bright tomorrow_night_eighties tomorrow_night twilight vibrant_ink xcode".split(" ");
$("body").append("<div id='fog'><div id='settings-window'><div id='title'><h2>Prefer\u00eancias do editor</h2></div><div id='settings-content'><div id='options'><h3>Temas</h3><div id='list'></div><h3>Tamanho da fonte</h3><div id='font-size'><button class='button font-small'><img src='icon/font_minus.png'></button><button class='button font-big'><img src='icon/font_plus.png'></button></div></div><div id='sample'><h3>Visualiza\u00e7\u00e3o</h3><pre id='code-sample'></pre></div></div><div id='button-container'><button class='button' id='cancel'>Cancelar</button><button class='button' id='change'>ALTERAR</button></div></div></div>");
for(var b in a)$("#settings-window #list").append("<div class='theme'>"+a[b]+"</div>"),(user&&user.theme==a[b]||!user&&"dreamweaver"==a[b])&&$("#settings-window #list .theme").last().addClass("selected");var d=ace.edit("code-sample");user&&(d.setTheme("ace/theme/"+user.theme),d.setFontSize(user.font+"px"));d.getSession().setMode("ace/mode/c_cpp");d.setReadOnly(!0);d.setValue("int start = 1;\n\nloop(){\n\tupgradeSTR();\n\tif (getCloseEnemy()){\n\t\tfloat dist = getDist(getTargetX(), getTargetY());\n\t\tif (dist < 0.8 && isTargetVisible()){\n\t\t\tattackMelee();\n\t\t}\n\t\telse\n\t\t\tmoveToTarget();\n\t}\n\telse{\n\t\tif (start){\n\t\t\tif(moveTo(12.5,12.5))\n\t\t\t\tstart = 0;\n\t\t}\n\t\telse\n\t\t\tturnLeft(50);\n\t}\n}",
-1);$("#settings-window #list .theme").click(function(){$("#settings-window #list .theme").removeClass("selected");$(this).addClass("selected");var a=$(this).html();d.setTheme("ace/theme/"+a)});$("#settings-window #font-size .button").click(function(){var a=parseInt(d.getFontSize());$(this).hasClass("font-small")?d.setFontSize(a-2):$(this).hasClass("font-big")&&d.setFontSize(a+2);d.resize()});$("#settings-window #cancel").click(function(){$("#fog").remove()});$("#settings-window #change").click(function(){var a=
d.getTheme().split("/")[2],b=parseInt(d.getFontSize());editor.setTheme(d.getTheme());editor.setFontSize(d.getFontSize());$("#fog").remove();user&&$.post("back_login.php",{action:"EDITOR",theme:a,font:b}).done(function(){user.theme=a;user.font=b})})});$("#help").click(function(){$("body").append("<div id='fog'><div id='help-window'><div id='title'>Que tipo de ajuda voc\u00ea gostaria?</div><div id='cat-container'><div id='docs' class='categories'><img src='icon/document.png'><span>Leitura</span></div><div id='video' class='categories'><img src='icon/video.png'><span>V\u00eddeo</span></div><div id='tutorial' class='categories'><img src='icon/tutor.png'><span>Tutorial</span></div></div>");
$("#fog").hide().fadeIn();$("#fog").click(function(){$(this).remove()});$("#help-window #tutorial").click(function(){showTutorial()});$("#help-window #docs").click(function(a){a.stopPropagation();$(this).hasClass("selected")||($("#help-window .categories").removeClass("selected"),$(this).addClass("selected"),$("#help-window #subcat").remove(),$("#help-window").append("<div id='subcat'><a href='manual' class='button' target='_blank'>Manual da gladCode</a><a href='docs' class='button' target='_blank'>Refer\u00eancia das fun\u00e7\u00f5es</a></div>"),
$("#help-window #subcat").hide().slideDown())});$("#help-window #video").click(function(a){a.stopPropagation();$(this).hasClass("selected")||($("#help-window .categories").removeClass("selected"),$(this).addClass("selected"),$("#help-window #subcat").remove(),$("#help-window").append("<div id='subcat'><button class='video button' data-video='te1M98UDKiM'>Introdu\u00e7\u00e3o e conceitos</button><button class='video button' data-video='tjMjqQ14AS8'>Editor de gladiadores</button><button class='video button' data-video='Wrc-0_Kq-_4'>Programando gladiadores</button><button class='video button' data-video='5QQtfruq8_8'>Habilidades e efeitos</button></div>"),
$("#help-window #subcat").hide().slideDown(),$("#help-window .video.button").click(function(){$("#fog").remove();var a=$(this).data("video");$("body").append("<div id='fog' class='dark'><div id='video-container'><iframe width='100%' height='100%' src='https://www.youtube.com/embed/"+a+"' frameborder='0' allowfullscreen></iframe><div id='remove'></div></div></div>");$("#fog").hide().fadeIn();$("#fog #remove").click(function(){$("#fog").remove()})}))})});editor.on("change",function(){tested=saved=!1;
""!=$("#float-card .glad-preview").html()&&""!=editor.getValue()?$("#download").removeClass("disabled"):$("#download").addClass("disabled");1==tutoState&&showTutorial()})});
function setLoadGlad(){loadGlad={};var a=[],e;for(e in selected)a.push(e);loadGlad.skin=JSON.stringify(a);loadGlad.id=gladid;loadGlad.user=nick;loadGlad.name=$("#distribuicao #nome").val();loadGlad.vstr=$("#distribuicao .slider").eq(0).val();loadGlad.vagi=$("#distribuicao .slider").eq(1).val();loadGlad.vint=$("#distribuicao .slider").eq(2).val();loadGlad.code='setup(){\n\tsetName("'+loadGlad.name+'");\n\tsetSTR('+loadGlad.vstr+");\n\tsetAGI("+loadGlad.vagi+");\n\tsetINT("+loadGlad.vint+');\n\tsetSkin("'+
loadGlad.skin+'");\n\tsetUser("'+loadGlad.user+'");\n}\n\n'+editor.getValue()}function getGladFromFile(a){var e=$.Deferred();$.post("back_glad.php",{action:"FILE",filename:a}).done(function(a){a=JSON.parse(a);a.skin&&(a.skin=JSON.stringify(a.skin));return e.resolve(a)});return e.promise()}
function load_editor(){ace.require("ace/ext/language_tools");editor=ace.edit("code");editor.setTheme("ace/theme/dreamweaver");editor.setFontSize(18);editor.session.setMode("ace/mode/c_cpp");editor.getSession().setUseWrapMode(!0);editor.$blockScrolling=Infinity;editor.setOptions({enableBasicAutocompletion:!0,enableSnippets:!0,enableLiveAutocompletion:!0})}
var menus={body:["gender","shape","ears","eyes"],hair:["style","color","facial","bcolor"],cloth:["shirt","armor","legs","feet"],misc:["head","shoulder","hands","cape","belt"],equip:["melee","ranged","shield"]},canvas=document.createElement("canvas");canvas.setAttribute("width",192);canvas.setAttribute("height",192);var ctx=canvas.getContext("2d"),spritesheet=document.createElement("canvas");spritesheet.setAttribute("width",2496);spritesheet.setAttribute("height",4032);
var spritectx=spritesheet.getContext("2d"),lastcolor="black",direction=2,scale=1,animationOn=!1,selected={},imageIndex=[],parentTree=[],anim_num=0,move=[{name:"walk",sprites:9,line:8,image:"walk"},{name:"cast",sprites:7,line:0,image:"magic"},{name:"thrust",sprites:8,line:4,image:"thrust"},{name:"slash",sprites:6,line:12,image:"slash"},{name:"shoot",sprites:13,line:16,image:"arrows"}],moveEnum={walk:0,cast:1,thrust:2,slash:3,shoot:4};
function load_glad_generator(a){a.load("glad-create.html",function(){function a(d){return 0==d?0:a(d-1)+Math.ceil(d/6)}buildIndex();$(".img-button.sub").addClass("hidden");$("#middle-container").append(canvas);reload_reqs();$(".slider-container").on("touchstart mouseenter",function(){text=[{path:"sprite/images/strength.png",title:"For\u00e7a - STR",description:"For\u00e7a f\u00edsica e resist\u00eancia do gladiador.",list:[{path:"sprite/images/decapitation.png",description:"Dano f\u00edsico, o dano causado com armas corpo-a-corpo"},
{path:"sprite/images/healing.png",description:"Pontos de vida, respons\u00e1veis por manter o gladiador vivo"}]},{path:"sprite/images/agility.png",title:"Agilidade - AGI",description:"Agilidade, rapidez e destreza do gladiador.",list:[{path:"sprite/images/bullseye.png",description:"Precis\u00e3o, o dano causado com armas \u00e0 dist\u00e2ncia"},{path:"sprite/images/sprint.png",description:"Velocidade de movimento dentro da arena"},{path:"sprite/images/blades.png",description:"Velocidade de execu\u00e7\u00e3o de ataques"}]},
{path:"sprite/images/smart.png",title:"Intelig\u00eancia - INT",description:"Rapidez de racioc\u00ednio e Capacidade intelectual do gladiador.",list:[{path:"sprite/images/energy.png",description:"Poder m\u00e1gico, o dano causado com habilidades m\u00e1gicas"},{path:"sprite/images/3balls.png",description:"Velocidade de execu\u00e7\u00e3o de uma habilidade"},{path:"sprite/images/energise.png",description:"Pontos de habilidade, usados para lan\u00e7ar habilidades"}]}];index=$(".slider-container").index($(this));
$("#info #title img").attr("src",text[index].path);$("#info #title span").html(text[index].title);$("#info #body .fill").html(text[index].description);$("#info ul").html("");$.each(text[index].list,function(a,b){$("#info ul").append("<li><img src='"+b.path+"'><span>"+b.description+"</span></li>")})});$("#save-glad").click(function(){$("#distribuicao-container").css({display:"flex",height:$("#skin-container").outerHeight()});$("#skin-container").hide();var a=document.createElement("canvas");a.setAttribute("width",
64);a.setAttribute("height",64);a.getContext("2d").drawImage(canvas,64,64,64,64,0,0,64,64);$("#cv").html(a);tested=saved=!1});$("#get-code").click(function(){var a=$("#distribuicao #nome").val();if(2>=a.length||!a.match(/^[\w \u00c0-\u00fa]+?$/g))$("#distribuicao #nome").addClass("error"),$("#distribuicao #nome").focus();else{$("#distribuicao #nome").removeClass("error");pieces=[];$.each(selected,function(a,c){pieces.push(c.id)});var b=$("#distribuicao .slider-input").eq(0).val(),e=$("#distribuicao .slider-input").eq(1).val(),
c=$("#distribuicao .slider-input").eq(2).val();1==tutoState&&(tutoState=2,showTutorial());editor&&(""==editor.getValue()&&(editor.setValue("loop(){\n    //comportamento do gladiador\n}"),editor.gotoLine(1,0,!0)),editor.focus(),$("#save, #test").removeClass("disabled"),$("#fog-skin").hide(),$("#back").click(),$("#float-card .glad-preview").load("glad-card-template.html",function(){$("#float-card .glad-preview .info .glad span").html(a);$("#float-card .glad-preview .info .attr .str span").html(b);$("#float-card .glad-preview .info .attr .agi span").html(e);
$("#float-card .glad-preview .info .attr .int span").html(c);$(".delete-container, .code").remove();var d=document.createElement("canvas");d.setAttribute("width",64);d.setAttribute("height",64);d.getContext("2d").drawImage(canvas,64,64,64,64,0,0,64,64);$("#float-card .glad-preview .image").html(d);""!=$("#float-card .glad-preview").html()&&""!=editor.getValue()?$("#download").removeClass("disabled"):$("#download").addClass("disabled")}))}tested=saved=!1});$("#back").click(function(){$("#distribuicao-container").hide();
$("#skin-container").show()});$("#reset").click(function(){$(".img-button").removeClass("selected");$(".img-button .sub").addClass("hidden");$("#distribuicao #nome").val("");$("#distribuicao .slider").val(0).change();selected={};for(var a in images)images[a].default&&(selected[images[a].id]=images[a]);reload_reqs();$("#distribuicao-container").hide();$("#skin-container").show()});$(".img-button.cat").click(function(){$(this).hasClass("n-av")||($(".img-button.cat").removeClass("selected"),$(".img-button.sub").removeClass("selected"),
$(".img-button.sub").addClass("hidden"),$.each(menus[$(this).attr("id")],function(a,b){$("#"+b).removeClass("hidden")}),$(this).addClass("selected"),reload_reqs())});$(".img-button.sub").click(function(){$(this).hasClass("n-av")||($(".img-button.sub").removeClass("selected"),$(this).addClass("selected"),reload_reqs())});$("#turn").click(function(){direction=(direction+1)%4;draw()});$("#down-scale").click(function(){1<scale&&(scale-=.5);draw()});$("#up-scale").click(function(){3.5>scale&&(scale+=.5);
draw()});var b=0;$("#play-pause").click(function(){animationOn?(animationOn=!1,b=0,$(this).find("img").attr("src","sprite/images/play.png")):(animationOn=!0,$(this).find("img").attr("src","sprite/images/pause.png"));draw()});$("#animation").click(function(){var a={walk:!0,cast:!0,thrust:!1,slash:!1,shoot:!1};$.each(selected,function(b,d){d.move&&(a[d.move]=!0)});do anim_num=(anim_num+1)%move.length;while(!a[move[anim_num].name]);b=0;$(this).find("img").attr("src","sprite/images/"+move[anim_num].image+
".png")});setInterval(function(){ctx.clearRect(0,0,canvas.width,canvas.height);animationOn&&b++;b>=move[anim_num].sprites&&(b=0);l=direction+move[anim_num].line;ctx.drawImage(spritesheet,192*b,192*l,192,192,96-192*scale/2,96-192*scale/2-5,192*scale,192*scale)},100);$(document).on("input change","#distribuicao .slider",function(){$(this).parents(".slider-container").find(".slider-value").html(a($(this).val()));$(this).parents(".slider-container").find(".slider-input").val($(this).val());$("#get-code").prop("disabled",
"true");var d=0;$("#distribuicao .slider-value").each(function(){d+=parseInt($(this).html())});var b=$("#distribuicao #remaining span");b.html(50-d);50==d?($("#get-code").html("GERAR C\u00d3DIGO"),$("#get-code").removeProp("disabled"),b.css("color","#4caf50")):50<d?b.css("color","#f44336"):b.css("color","black")});$(".close").click(function(){$("#fog-skin").hide()});if(loadGlad){selected={};var f=!1;try{var g=JSON.parse(loadGlad.skin)}catch(d){f=!0,g=[]}for(var l in g)getImage(g[l])&&(selected[g[l]]=
getImage(g[l]));gladid=loadGlad.id;$("#distribuicao #nome").val(loadGlad.name);$("#distribuicao .slider").eq(0).val(loadGlad.vstr);$("#distribuicao .slider").eq(1).val(loadGlad.vagi);$("#distribuicao .slider").eq(2).val(loadGlad.vint);$("#distribuicao .slider").change();editor.setValue(decodeHTML(loadGlad.code));editor.gotoLine(1,0,!0);$("#get-code").click();saved=!0;f||fetchSpritesheet(JSON.stringify(g)).then(function(a){$("#float-card .image").html(getSpriteThumb(a,"walk","down"))})}})}
function draw(){function a(a){var b=["up","left","down","right"];return a.layer&&a.layer.default?a.layer[b[direction]]?a.layer[b[direction]]:a.layer.default:a.layer}var e=0,b=[],f;for(f in selected)b.push(selected[f]);b.sort(function(b,d){return a(b)-a(d)});var g=[];for(f=0;f<b.length;f++)""==b[f].path||b[f].png?e++:(g[f]=new Image,g[f].src="sprite/Universal-LPC-spritesheet/"+b[f].path,g[f].onload=function(){e++});var l=document.createElement("canvas");l.width=spritesheet.width;l.height=spritesheet.height;
var d=l.getContext("2d");interval=setInterval(function(){if(e==b.length){clearInterval(interval);for(f=0;f<b.length;f++)if(g[f])if(b[f].oversize){var a=move[moveEnum[b[f].move]].line,m=move[moveEnum[b[f].move]].sprites;for(k=0;4>k;k++)for(j=0;j<m;j++)d.drawImage(g[f],192*j,192*k,192,192,192*j,192*a+192*k,192,192)}else for(k=0;21>k;k++)for(j=0;13>j;j++)d.drawImage(g[f],64*j,64*k,64,64,64+192*j,64+192*k,64,64);spritectx.clearRect(0,0,spritesheet.width,spritesheet.height);spritectx.drawImage(l,0,0)}},
10)}
function reload_reqs(a){a||$("#right-container").html("");var e={};setTimeout(function(){var b=parentTree[$(".img-button.sub.selected").attr("id")];$.each(b,function(a,c){c=getImage(c);a=!0;if(Array.isArray(c.parent)){for(h=0;h<c.parent.length&&!$(".img-button#"+c.parent[h]).hasClass("selected");h++);h==c.parent.length&&(a=!1)}else $(".img-button#"+c.parent).hasClass("selected")||(a=!1);a&&(e[c.id]=c)});$.each(images,function(a,c){if(c.req)if(c.req.or){for(h=0;h<c.req.or.length&&!selected[c.req.or[h]];h++);h==
c.req.or.length&&(delete e[c.id],delete selected[c.id])}else if(c.req.and)for(h=0;h<c.req.and.length;h++){if(!selected[c.req.and[h]]){delete e[c.id];delete selected[c.id];break}}else if(c.req.not)for(h=0;h<c.req.not.length;h++){if(selected[c.req.not[h]]){delete e[c.id];delete selected[c.id];break}}else selected[c.req]||(delete e[c.id],delete selected[c.id])});var f=!1;$.each(selected,function(a,c){"shape"==c.parent&&(f=!0)});f||(selected.male?selected["male-light"]=getImage("male-light"):selected["female-light"]=
getImage("female-light"));if($("#style").hasClass("selected")){var g=lastcolor;$.each(selected,function(a,c){"color"==c.parent[1]&&(lastcolor=g=c.id.split("_")[1])});$.each(images,function(a,c){"color"==c.parent[1]&&($(this).attr("id").split("_")[1]==g?e[c.id]=c:delete e[c.id])})}$("#facial").hasClass("selected")&&(g=lastcolor,$.each(selected,function(a,c){"bcolor"==c.parent[1]&&(lastcolor=g=c.id.split("_")[1])}),$.each(images,function(a,c){"bcolor"==c.parent[1]&&(c.id.split("_")[1]==g?e[c.id]=c:
delete e[c.id])}));if($("#color").hasClass("selected")){var l;$.each(selected,function(a,c){"style"==c.parent[0]&&(l=c.id.split("_")[0])});$.each(images,function(a,c){"style"==c.parent[0]&&(c.id.split("_")[0]==l?e[c.id]=c:delete e[c.id])})}if($("#bcolor").hasClass("selected")){var d;$.each(selected,function(a,c){"facial"==c.parent[0]&&(d=c.id.split("_")[0])});$.each(images,function(a,c){"facial"==c.parent[0]&&(c.id.split("_")[0]==d?e[c.id]=c:delete e[c.id])})}$(".img-button.sub.n-av").removeClass("n-av");
(selected["male-orc"]||selected["male-red_orc"]||selected.skeleton||selected["female-orc"]||selected["female-red_orc"])&&$("#eyes, #ears").addClass("n-av");selected.hair_none&&$("#color").addClass("n-av");selected.facial_none&&$("#bcolor").addClass("n-av");(selected.male_chain||selected.female_chain)&&$("#shirt, #legs").addClass("n-av");$.each(selected,function(a,c){if(Array.isArray(c.block))for(h=0;h<c.block.length;h++)$("#"+c.block[h]).addClass("n-av");else $("#"+c.block).addClass("n-av");c.move&&
$(".img-button#"+c.parent).hasClass("selected")&&(anim_num=moveEnum[c.move],$("#animation").find("img").attr("src","sprite/images/"+move[anim_num].image+".png"));"none"==c.parent&&selected[c.id]&&delete selected[c.id];c.select&&(selected[c.select]=getImage(c.select))});$.each($(".img-button.sub.n-av"),function(){var a=parentTree[$(this).attr("id")],c;for(c in a)selected[a[c]]&&delete selected[a[c]]});if(!a)for(var h in e)load_assets(e[h]);draw()},1)}
function load_assets(a){var e=document.createElement("canvas");e.setAttribute("width",64);e.setAttribute("height",64);var b=e.getContext("2d"),f=a.path,g=new Image;g.src=a.png?"sprite/images/"+f:"sprite/Universal-LPC-spritesheet/"+f;g.onload=function(){try{var d=10,e=0,f=64;a.line&&(d=a.line);a.col&&(e=a.col);a.oversize&&(f=192);if(a.png)b.drawImage(g,0,0,a.width,a.height,0,0,64,64);else if(a.scale){var c=0,l=0;a.posx&&(c=a.posx);a.posy&&(l=a.posy);b.drawImage(g,e*f,d*f,f,f,f/2-a.scale*f/2+c,f/2-
a.scale*f/2+l,64*a.scale,64*a.scale)}else b.drawImage(g,e*f,d*f,f,f,0,-5,64,64)}catch(n){console.log(n)}};0==$(".img-button.item#"+a.id).length&&$("#right-container").append("<div class='img-button item' id='"+a.id+"'></div>");$(".img-button.item#"+a.id).append(e);a.default&&$(".img-button.item#"+a.id).addClass("selected");for(var l in selected)selected[l].id==a.id&&($(".img-button.item").removeClass("selected"),$(".img-button.item#"+a.id).addClass("selected"));$(".img-button.item#"+a.id).click(function(){var b=
[];Array.isArray(a.parent)?b=a.parent:b.push(a.parent);for(var e in selected){var f=[];Array.isArray(selected[e].parent)?f=selected[e].parent:f.push(selected[e].parent);for(var c in f)for(var g in b)f[c]==b[g]&&delete selected[e]}selected[a.id]=a;$(".img-button.item").removeClass("selected");$(this).addClass("selected");reload_reqs(!0)})}function getImage(a){return images[imageIndex[a]]}
function buildIndex(){for(i=0;i<images.length;i++){imageIndex[images[i].id]=i;if(images[i].parent)if(Array.isArray(images[i].parent))for(j in images[i].parent)parentTree[images[i].parent[j]]||(parentTree.push(images[i].parent[j]),parentTree[images[i].parent[j]]=[]),parentTree[images[i].parent[j]].push(images[i].id);else parentTree[images[i].parent]||(parentTree.push(images[i].parent),parentTree[images[i].parent]=[]),parentTree[images[i].parent].push(images[i].id);images[i].default&&(selected[images[i].id]=
images[i])}}function cloneCanvas(a){var e=document.createElement("canvas"),b=e.getContext("2d");e.width=a.width;e.height=a.height;b.drawImage(a,0,0);return e}function download(a,e){var b=document.createElement("a");b.setAttribute("href","data:text/plain;charset=utf-8,"+encodeURIComponent(e));b.setAttribute("download",a);document.createEvent?(a=document.createEvent("MouseEvents"),a.initEvent("click",!0,!0),b.dispatchEvent(a)):b.click()}
function setGladImage(a,e){fetchSpritesheet(e).then(function(b){$("#fog-glads .glad-preview .image").eq(a).html(getSpriteThumb(b,"walk","down"))})}window.onbeforeunload=function(){return saved?null:!0};
