var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,e){a instanceof String&&(a=String(a));for(var b=a.length,c=0;c<b;c++){var g=a[c];if(d.call(e,g,c,a))return{i:c,v:g}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,e){a!=Array.prototype&&a!=Object.prototype&&(a[d]=e.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,e,b){if(d){e=$jscomp.global;a=a.split(".");for(b=0;b<a.length-1;b++){var c=a[b];c in e||(e[c]={});e=e[c]}a=a[a.length-1];b=e[a];d=d(b);d!=b&&null!=d&&$jscomp.defineProperty(e,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,e){return $jscomp.findInternal(this,a,e).v}},"es6","es3");var file_manager_action;
function get_dir(){var a=$(".window #dir-path").text().split(" > ");a.splice(0,1);return a=user.pasta+"/"+a.join("/")}
function create_dir(a,d){$.post("back_getfile.php",{action:"NEWDIR",dir:d,name:a}).done(function(e){e=reload_canvas(d);$.when(e).then(function(){$(".window .folder .name").filter(function(){return $(this).html()===a}).parent().addClass("selected")});$(".window .folder.selected").dblclick(function(){var a=$(".window .folder.selected .name").html();d+="/"+a;reload_canvas(d);$(".window #dir-path").append(" > <a class='dir'>"+a+"</a>");$(".window #filename").val("")})})}
function reload_canvas(a){var d="",e="",b=$.post("back_getfile.php",{action:"DIR",dir:a});b.done(function(c){var b=c.split("||")[0].split("|");c=c.split("||")[1].split("|");if(""!=c[0])for(var f=0;f<c.length;f++){var h=c[f].split(".")[1];d="c"==h||"cpp"==h?d+("<div class='file'><img src='icon/file_c.png'><div class='name'>"+c[f]+"</div></div>"):d+("<div class='file'><img src='icon/file_generic.png'><div class='name'>"+c[f]+"</div></div>")}if(""!=b[0])for(f=0;f<b.length;f++)e+="<div class='folder'><img src='icon/folder.png'><span class='name'>"+
b[f]+"</span></div>";b=e+d;$(".window #blank").html(b);$(".window .file, .window .folder").click(function(a){a.stopPropagation();$(".window .file, .window .folder").removeClass("selected");$(this).addClass("selected");$(".window #filename").val($(".window #blank .selected .name").html())});$(".window .folder").dblclick(function(){var b=$(".window .folder.selected .name").html();reload_canvas(a+"/"+b);$(".window #dir-path").append("<span class='arrow'> > </span><a class='dir'>"+b+"</a>");$(".window #filename").val("");
$(".window #dir-path .dir").last().click(function(){var a=$(".window #dir-path .dir").index($(this));$(".window #dir-path .dir").eq(a).nextAll().remove();$(".window #dir-path .arrow").eq(a).nextAll().remove();reload_canvas(get_dir())})});$(".window .file").dblclick(function(){if("load"==file_manager_action){var b=$(".window .file.selected .name").html(),c="/home/gladcode/user/"+a+"/"+b,e=!1;$(".tab").each(function(){meta_files[$(".tab").index($(this))].path==c&&(switch_tab($(this)),e=!0,$("#fog").click())});
e||$.post("back_getfile.php",{action:"FILE",href:c}).done(function(a){if("NULL"!=a){var b=c.split("/")[c.split("/").length-1];new_tab(b,a);meta_files[meta_files.length-1].path=c;meta_files[meta_files.length-1].local=!1;$("#button-csave").hide();$("#button-csync").show()}$("#fog").click()})}else"save"==file_manager_action&&(b="<div id='window-wrapper'><div class='window message' id='overwrite'><div class='row title'>Deseja sobrescrever o arquivo \""+$(".window #blank .selected .name").html()+"\"?</div><div class='row buttons'><img class='green' src='icon/check.png'><img class='red' src='icon/close_x.png'></div></div></div>",
$("body").append(b),$("#window-wrapper").click(function(){$(this).remove()}),$(".window.message").click(function(a){a.stopPropagation()}),$(".window.message img.red").click(function(){$("#window-wrapper").click()}),$(".window.message img.green").click(function(){$("#window-wrapper").click();var a=$(".window #filename").val(),b=get_dir(),c=editor.getValue();$.post("back_getfile.php",{action:"SAVE",name:a,dir:b,text:c}).done(function(c){$("#fog").click();$(".tab.active .name").html(a);$(".tab.active .changed").remove();
c="/home/gladcode/user/"+b+"/"+a;meta_files[$(".tab").index($(".tab.active"))].path=c;meta_files[$(".tab").index($(".tab.active"))].local=!1;$("#button-csave").hide();$("#button-csync").show()})}))})});return b}
function show_file_manager(a){file_manager_action=a;var d;"load"==a?d="Abrir arquivo":"save"==a&&(d="Guardar arquivo");a="<div id='fog'><div class='window' id='folder-canvas'><div id='title'><div>"+d+"</div><img id='button-close-window' class='red' src='icon/close_x.png'></div><div id='dir-path'><a class='dir'>Minha Pasta</a></div><div id='blank'></div><div class='row'><input id='filename' type='text'></div><div class='row buttons'><div class='column'><img class='grey' id='button-newdir' src='icon/folder_add.png' title='Nova pasta'><img class='grey' id='button-remove' src='icon/delete.png' title='Excluir'></div><div class='column'><img class='green' id='button-ok' src='icon/check.png'></div></div></div></div>";$("body").append(a);
$("#fog").click(function(){$(this).remove();$(window).width()>window_size_threshold&&editor.focus()});$(".window").click(function(a){a.stopPropagation()});reload_canvas(user.pasta);$(window).width()>window_size_threshold&&$(".window #filename").focus();$(".window #blank").click(function(){$(".window .file, .window .folder").removeClass("selected")});$(".window #dir-path .dir").click(function(){$.when(reload_canvas(user.pasta)).then(function(){$(".window #dir-path .dir").eq(0).nextAll().remove();$(".window #dir-path .arrow").remove()})});
$(".window #button-newdir").click(function(a){$(".window .file, .window .folder").removeClass("selected");$(".window #blank").append("<div class='folder selected'><img src='icon/folder.png'><span class='name'><input type='text' value='Nova pasta'></span></div>");var b=$(".window .folder.selected input");$(".window #blank").scrollTop(b.position().top+b.height());var c=get_dir();b.select();b.keydown(function(a){13==a.keyCode&&create_dir(b.val(),c)});b.focusout(function(){create_dir(b.val(),c)})});$(".window #button-remove").click(function(a){if(1==
$(".window #blank .selected").length){var b=$(".window #blank .selected .name").html();a="<div id='window-wrapper'><div class='window message'><div class='row title'>Tem certeza que deseja excluir "+($(".window #blank .selected").hasClass("folder")?"a pasta":"o arquivo")+' "'+b+"\"?</div><div class='row buttons'><img class='green' src='icon/check.png'><img class='red' src='icon/close_x.png'></div></div></div>";$("body").append(a);$("#window-wrapper").click(function(){$(this).remove();$(window).width()>
window_size_threshold&&editor.focus()});$(".window.message").click(function(a){a.stopPropagation()});$(".window.message img.red").click(function(){$("#window-wrapper").click()});$(".window.message img.green").click(function(){$("#window-wrapper").click();var a=get_dir();$.post("back_getfile.php",{action:"REMOVE",name:b,dir:a}).done(function(b){reload_canvas(a)})})}});$(".window #button-close-window").click(function(a){$("#fog").click()});$(".window #button-ok").click(function(a){if(0==$(".folder.selected input").length){var b,
c=$(".window #filename").val();$(".window .folder, .window .file").each(function(){c==$(this).find(".name").html()&&(b=$(this))});if(b)b.click(),b.dblclick();else if("save"==file_manager_action&&""!=$(".window #filename").val()){var d=get_dir();a=editor.getValue();$.post("back_getfile.php",{action:"SAVE",name:c,dir:d,text:a}).done(function(a){$("#fog").click();$(".tab.active .name").html(c);$(".tab.active .changed").remove();a="/home/gladcode/user/"+d+"/"+c;meta_files[$(".tab").index($(".tab.active"))].path=
a;meta_files[$(".tab").index($(".tab.active"))].local=!1;$("#button-csave").hide();$("#button-csync").show()})}}})}function sync_file(a,d){$.post("back_getfile.php",{action:"SYNC",path:d,text:a}).done(function(a){})};
