var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,f){a instanceof String&&(a=String(a));for(var e=a.length,b=0;b<e;b++){var l=a[b];if(c.call(f,l,b,a))return{i:b,v:l}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,f){a!=Array.prototype&&a!=Object.prototype&&(a[c]=f.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,f,e){if(c){f=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var b=a[e];b in f||(f[b]={});f=f[b]}a=a[a.length-1];e=f[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(f,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,f){return $jscomp.findInternal(this,a,f).v}},"es6","es3");
function setGladImage(a,c,f,e){fetchSpritesheet(f).then(function(b){var f="walk";e&&(f="die");a.find(".glad-preview .image").eq(c).html(getSpriteThumb(b,f,"down"))})}function getImage(a){for(var c in images)if(images[c].id==a)return images[c];return!1}
function getSpriteThumb(a,c,f){var e={walk:8,cast:0,thrust:4,slash:12,shoot:16,up:0,left:1,down:2,right:3};f=e[c]+e[f];e=1;"die"==c&&(e=5,f=20);c=document.createElement("canvas");c.setAttribute("width",64);c.setAttribute("height",64);c.getContext("2d").drawImage(a,192*e+64,192*f+64,64,64,0,0,64,64);return c}
function fetchSpritesheet(a){var c=$.Deferred(),f={walk:{sprites:9,line:8},cast:{sprites:7,line:0},thrust:{sprites:8,line:4},slash:{sprites:6,line:12},shoot:{sprites:13,line:16},die:{sprites:6,line:20}},e=!1;try{a=JSON.parse(a)}catch(n){e=!0,a={}}var b=document.createElement("canvas");b.setAttribute("width",2496);b.setAttribute("height",4032);var l=b.getContext("2d"),d=0,g=[],h;for(h in a)getImage(a[h])&&g.push(getImage(a[h]));validate_skin(g)||(e=!0);if(e)k=new Image,k.src="res/glad.png",k.onload=
function(){for(var a=0;21>a;a++)for(var d=0;13>d;d++)l.drawImage(k,64*d,64*a,64,64,64+192*d,64+192*a,64,64);return c.resolve(b)};else{var m=function(){for(var a=0;a<g.length;a++)if(k[a])if(g[a].oversize)for(var c=f[g[a].move].line,d=f[g[a].move].sprites,b=0;4>b;b++)for(var e=0;e<d;e++)l.drawImage(k[a],192*e,192*b,192,192,192*e,192*c+192*b,192,192);else for(b=0;21>b;b++)for(e=0;13>e;e++)l.drawImage(k[a],64*e,64*b,64,64,64+192*e,64+192*b,64,64)};g.sort(function(a,b){if(null==a.layer)return-1;if(null==
b.layer)return 1;"object"===typeof a.layer&&(a.layer=a.layer.down);"object"===typeof b.layer&&(b.layer=b.layer.down);return a.layer-b.layer});l.clearRect(0,0,b.width,b.height);var k=[];for(h=0;h<g.length;h++)if(g[h]&&""!=g[h].path&&!g[h].png)k[h]=new Image,k[h].src="sprite/Universal-LPC-spritesheet/"+g[h].path,k[h].onload=function(){d++;if(d==g.length)return m(),c.resolve(b)};else if(d++,d==g.length)return m(),c.resolve(b)}return c.promise()}
function load_glad_cards(a,c){function f(b){for(var f in b)a.append("<div class='glad-preview'></div>");template=$("<div id='template'></div>").load("glad-card-template.html",function(){a.find(".glad-preview").html(template);var d={},f;for(f in b)d.$jscomp$loop$prop$i$0$2=f,c.dead&&b[d.$jscomp$loop$prop$i$0$2].dead?setGladImage(a,d.$jscomp$loop$prop$i$0$2,b[d.$jscomp$loop$prop$i$0$2].skin,!0):setGladImage(a,d.$jscomp$loop$prop$i$0$2,b[d.$jscomp$loop$prop$i$0$2].skin),a.find(".glad-preview .info .glad span").eq(d.$jscomp$loop$prop$i$0$2).html(b[d.$jscomp$loop$prop$i$0$2].name),
a.find(".glad-preview .info .attr .str span").eq(d.$jscomp$loop$prop$i$0$2).html(b[d.$jscomp$loop$prop$i$0$2].vstr),a.find(".glad-preview .info .attr .agi span").eq(d.$jscomp$loop$prop$i$0$2).html(b[d.$jscomp$loop$prop$i$0$2].vagi),a.find(".glad-preview .info .attr .int span").eq(d.$jscomp$loop$prop$i$0$2).html(b[d.$jscomp$loop$prop$i$0$2].vint),a.find(".glad-preview").eq(d.$jscomp$loop$prop$i$0$2).data("id",b[d.$jscomp$loop$prop$i$0$2].id),c.code&&(b[d.$jscomp$loop$prop$i$0$2].code?(a.find(".glad-preview .code .button").eq(d.$jscomp$loop$prop$i$0$2).removeProp("disabled"),
a.find(".glad-preview .code .button").eq(d.$jscomp$loop$prop$i$0$2).click(function(a){return function(c){c.stopPropagation();$("body").append("<div id='fog' class='code'><div class='float-box'><pre id='code' pre class='line-numbers language-c'><code class='language-c'>"+b[a.$jscomp$loop$prop$i$0$2].code+"</code></pre><div id='button-container'><button class='button'>FECHAR</button></div></div></div>");Prism.highlightElement($("code")[0]);$("#fog.code .button").click(function(){$("#fog.code").remove()})}}(d))):
a.find(".glad-preview .code .button").eq(d.$jscomp$loop$prop$i$0$2).prop("disabled",!0)),c.master&&a.find(".glad-preview .info .master").eq(d.$jscomp$loop$prop$i$0$2).html(b[d.$jscomp$loop$prop$i$0$2].user),c.dead&&b[d.$jscomp$loop$prop$i$0$2].dead&&a.find(".glad-preview").eq(d.$jscomp$loop$prop$i$0$2).addClass("dead").attr("title","Este gladiador est\u00e1 morto"),b[d.$jscomp$loop$prop$i$0$2].oldversion&&a.find(".glad-preview").eq(d.$jscomp$loop$prop$i$0$2).addClass("old").attr("title","Este gladiador precisa ser atualizado"),
d={$jscomp$loop$prop$i$0$2:d.$jscomp$loop$prop$i$0$2};c.code||a.find(".glad-preview .code .button").remove();c.remove||a.find(".glad-preview .delete-container").remove();c.clickHandler&&a.find(".glad-preview").click(c.clickHandler);c.dblClickHandler&&a.find(".glad-preview").dblclick(c.dblClickHandler);return e.resolve(!0)})}var e=$.Deferred();c.customLoad?f(c.customLoad):$.post("back_glad.php",{action:"GET"}).done(function(a){f(JSON.parse(a))});return e.promise()};
