var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var g=0;return function(){return g<a.length?{done:!1,value:a[g++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,g,c){a!=Array.prototype&&a!=Object.prototype&&(a[g]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,g){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:g})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(c){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(c||"")+"_"+g++,c)}var g=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,g){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var c=0,d={next:function(){if(c<a.length){var f=c++;return{value:g(f,a[f]),done:!1}}d.next=function(){return{done:!0,value:void 0}};return d.next()}};d[Symbol.iterator]=function(){return d};return d};
$jscomp.polyfill=function(a,g,c,d){if(g){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var f=a[d];f in c||(c[f]={});c=c[f]}a=a[a.length-1];d=c[a];g=g(d);g!=d&&null!=g&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:g})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
var _self="undefined"!=typeof window?window:"undefined"!=typeof WorkerGlobalScope&&self instanceof WorkerGlobalScope?self:{},Prism=function(){var a=/\blang(?:uage)?-([\w-]+)\b/i,g=0,c=_self.Prism={manual:_self.Prism&&_self.Prism.manual,disableWorkerMessageHandler:_self.Prism&&_self.Prism.disableWorkerMessageHandler,util:{encode:function(b){return b instanceof d?new d(b.type,c.util.encode(b.content),b.alias):"Array"===c.util.type(b)?b.map(c.util.encode):b.replace(/&/g,"&amp;").replace(/</g,"&lt;").replace(/\u00a0/g,
" ")},type:function(b){return Object.prototype.toString.call(b).match(/\[object (\w+)\]/)[1]},objId:function(b){return b.__id||Object.defineProperty(b,"__id",{value:++g}),b.__id},clone:function(b,e){var k=c.util.type(b);switch(e=e||{},k){case "Object":if(e[c.util.objId(b)])return e[c.util.objId(b)];var a={};e[c.util.objId(b)]=a;for(var d in b)b.hasOwnProperty(d)&&(a[d]=c.util.clone(b[d],e));return a;case "Array":if(e[c.util.objId(b)])return e[c.util.objId(b)];a=[];return e[c.util.objId(b)]=a,b.forEach(function(b,
d){a[d]=c.util.clone(b,e)}),a}return b}},languages:{extend:function(b,e){b=c.util.clone(c.languages[b]);for(var a in e)b[a]=e[a];return b},insertBefore:function(b,e,a,d){d=d||c.languages;var k=d[b];if(2==arguments.length){a=arguments[1];for(var l in a)a.hasOwnProperty(l)&&(k[l]=a[l]);return k}var h={},f;for(f in k)if(k.hasOwnProperty(f)){if(f==e)for(l in a)a.hasOwnProperty(l)&&(h[l]=a[l]);h[f]=k[f]}var g=d[b];return d[b]=h,c.languages.DFS(c.languages,function(c,a){a===g&&c!=b&&(this[c]=h)}),h},DFS:function(b,
a,d,l){l=l||{};for(var e in b)b.hasOwnProperty(e)&&(a.call(b,e,b[e],d||e),"Object"!==c.util.type(b[e])||l[c.util.objId(b[e])]?"Array"!==c.util.type(b[e])||l[c.util.objId(b[e])]||(l[c.util.objId(b[e])]=!0,c.languages.DFS(b[e],a,e,l)):(l[c.util.objId(b[e])]=!0,c.languages.DFS(b[e],a,null,l)))}},plugins:{},highlightAll:function(b,e){c.highlightAllUnder(document,b,e)},highlightAllUnder:function(b,e,a){a={callback:a,selector:'code[class*="language-"], [class*="language-"] code, code[class*="lang-"], [class*="lang-"] code'};
c.hooks.run("before-highlightall",a);for(var d=a.elements||b.querySelectorAll(a.selector),k=0;b=d[k++];)c.highlightElement(b,!0===e,a.callback)},highlightElement:function(b,e,d){for(var k,f,g=b;g&&!a.test(g.className);)g=g.parentNode;g&&(k=(g.className.match(a)||[,""])[1].toLowerCase(),f=c.languages[k]);b.className=b.className.replace(a,"").replace(/\s+/g," ")+" language-"+k;b.parentNode&&(g=b.parentNode,/pre/i.test(g.nodeName)&&(g.className=g.className.replace(a,"").replace(/\s+/g," ")+" language-"+
k));var h={element:b,language:k,grammar:f,code:b.textContent};if(c.hooks.run("before-sanity-check",h),!h.code||!h.grammar)return h.code&&(c.hooks.run("before-highlight",h),h.element.textContent=h.code,c.hooks.run("after-highlight",h)),c.hooks.run("complete",h),void 0;(c.hooks.run("before-highlight",h),e&&_self.Worker)?(b=new Worker(c.filename),b.onmessage=function(b){h.highlightedCode=b.data;c.hooks.run("before-insert",h);h.element.innerHTML=h.highlightedCode;c.hooks.run("after-highlight",h);c.hooks.run("complete",
h);d&&d.call(h.element)},b.postMessage(JSON.stringify({language:h.language,code:h.code,immediateClose:!0}))):(h.highlightedCode=c.highlight(h.code,h.grammar,h.language),c.hooks.run("before-insert",h),h.element.innerHTML=h.highlightedCode,c.hooks.run("after-highlight",h),c.hooks.run("complete",h),d&&d.call(b))},highlight:function(b,a,k){b={code:b,grammar:a,language:k};return c.hooks.run("before-tokenize",b),b.tokens=c.tokenize(b.code,b.grammar),c.hooks.run("after-tokenize",b),d.stringify(c.util.encode(b.tokens),
b.language)},matchGrammar:function(b,a,d,f,g,z,h){var e=c.Token,k;for(k in d)if(d.hasOwnProperty(k)&&d[k]){if(k==h)break;var l=d[k];l="Array"===c.util.type(l)?l:[l];for(var w=0;w<l.length;++w){var p=l[w],A=p.inside,B=!!p.lookbehind,x=!!p.greedy,y=0,C=p.alias;if(x&&!p.pattern.global){var q=p.pattern.toString().match(/[imuy]*$/)[0];p.pattern=RegExp(p.pattern.source,q+"g")}p=p.pattern||p;q=f;for(var t=g;q<a.length;t+=a[q].length,++q){var n=a[q];if(a.length>b.length)return;if(!(n instanceof e)){if(x&&
q!=a.length-1){p.lastIndex=t;var m=p.exec(b);if(!m)break;var u=m.index+(B?m[1].length:0),v=m.index+m[0].length,r=q;n=t;for(var D=a.length;D>r&&(v>n||!a[r].type&&!a[r-1].greedy);++r)n+=a[r].length,u>=n&&(++q,t=n);if(a[q]instanceof e)continue;r-=q;n=b.slice(t,n);m.index-=t}else p.lastIndex=0,m=p.exec(n),r=1;if(m){if(B&&(y=m[1]?m[1].length:0),u=m.index+y,m=m[0].slice(y),v=u+m.length,u=n.slice(0,u),v=n.slice(v),n=[q,r],u&&(++q,t+=u.length,n.push(u)),m=new e(k,A?c.tokenize(m,A):m,C,m,x),n.push(m),v&&n.push(v),
Array.prototype.splice.apply(a,n),1!=r&&c.matchGrammar(b,a,d,q,t,!0,k),z)break}else if(z)break}}}}},tokenize:function(b,a){var d=[b],e=a.rest;if(e){for(var f in e)a[f]=e[f];delete a.rest}return c.matchGrammar(b,d,a,0,0,!1),d},hooks:{all:{},add:function(b,a){var d=c.hooks.all;d[b]=d[b]||[];d[b].push(a)},run:function(b,a){if((b=c.hooks.all[b])&&b.length)for(var d,e=0;d=b[e++];)d(a)}}},d=c.Token=function(b,a,d,c,f){this.type=b;this.content=a;this.alias=d;this.length=0|(c||"").length;this.greedy=!!f};
if(d.stringify=function(b,a,f){if("string"==typeof b)return b;if("Array"===c.util.type(b))return b.map(function(c){return d.stringify(c,a,b)}).join("");var e={type:b.type,content:d.stringify(b.content,a,f),tag:"span",classes:["token",b.type],attributes:{},language:a,parent:f};b.alias&&(f="Array"===c.util.type(b.alias)?b.alias:[b.alias],Array.prototype.push.apply(e.classes,f));c.hooks.run("wrap",e);f=Object.keys(e.attributes).map(function(b){return b+'="'+(e.attributes[b]||"").replace(/"/g,"&quot;")+
'"'}).join(" ");return"<"+e.tag+' class="'+e.classes.join(" ")+'"'+(f?" "+f:"")+">"+e.content+"</"+e.tag+">"},!_self.document)return _self.addEventListener?(c.disableWorkerMessageHandler||_self.addEventListener("message",function(b){b=JSON.parse(b.data);var a=b.language,d=b.immediateClose;_self.postMessage(c.highlight(b.code,c.languages[a],a));d&&_self.close()},!1),_self.Prism):_self.Prism;var f=document.currentScript||[].slice.call(document.getElementsByTagName("script")).pop();return f&&(c.filename=
f.src,c.manual||f.hasAttribute("data-manual")||("loading"!==document.readyState?window.requestAnimationFrame?window.requestAnimationFrame(c.highlightAll):window.setTimeout(c.highlightAll,16):document.addEventListener("DOMContentLoaded",c.highlightAll))),_self.Prism}();"undefined"!=typeof module&&module.exports&&(module.exports=Prism);"undefined"!=typeof global&&(global.Prism=Prism);
Prism.languages.clike={comment:[{pattern:/(^|[^\\])\/\*[\s\S]*?(?:\*\/|$)/,lookbehind:!0},{pattern:/(^|[^\\:])\/\/.*/,lookbehind:!0,greedy:!0}],string:{pattern:/(["'])(?:\\(?:\r\n|[\s\S])|(?!\1)[^\\\r\n])*\1/,greedy:!0},"class-name":{pattern:/((?:\b(?:class|interface|extends|implements|trait|instanceof|new)\s+)|(?:catch\s+\())[\w.\\]+/i,lookbehind:!0,inside:{punctuation:/[.\\]/}},keyword:/\b(?:if|else|while|do|for|return|in|instanceof|function|new|try|throw|catch|finally|null|break|continue)\b/,"boolean":/\b(?:true|false)\b/,
"function":/\w+(?=\()/,number:/\b0x[\da-f]+\b|(?:\b\d+\.?\d*|\B\.\d+)(?:e[+-]?\d+)?/i,operator:/--?|\+\+?|!=?=?|<=?|>=?|==?=?|&&?|\|\|?|\?|\*|\/|~|\^|%/,punctuation:/[{}[\];(),.:]/};
Prism.languages.c=Prism.languages.extend("clike",{keyword:/\b(?:_Alignas|_Alignof|_Atomic|_Bool|_Complex|_Generic|_Imaginary|_Noreturn|_Static_assert|_Thread_local|asm|typeof|inline|auto|break|case|char|const|continue|default|do|double|else|enum|extern|float|for|goto|if|int|long|register|return|short|signed|sizeof|static|struct|switch|typedef|union|unsigned|void|volatile|while)\b/,operator:/>>=?|<<=?|->|([-+&|:])\1|[?:~]|[-+*\/%&|^!=<>]=?/,number:/(?:\b0x[\da-f]+|(?:\b\d+\.?\d*|\B\.\d+)(?:e[+-]?\d+)?)[ful]*/i});
Prism.languages.insertBefore("c","string",{macro:{pattern:/(^\s*)#\s*[a-z]+(?:[^\r\n\\]|\\(?:\r\n|[\s\S]))*/im,lookbehind:!0,alias:"property",inside:{string:{pattern:/(#\s*include\s*)(?:<.+?>|("|')(?:\\?.)+?\2)/,lookbehind:!0},directive:{pattern:/(#\s*)\b(?:define|defined|elif|else|endif|error|ifdef|ifndef|if|import|include|line|pragma|undef|using)\b/,lookbehind:!0,alias:"keyword"}}},constant:/\b(?:__FILE__|__LINE__|__DATE__|__TIME__|__TIMESTAMP__|__func__|EOF|NULL|SEEK_CUR|SEEK_END|SEEK_SET|stdin|stdout|stderr)\b/});
delete Prism.languages.c["class-name"];delete Prism.languages.c["boolean"];
!function(){if("undefined"!=typeof self&&self.Prism&&self.document){var a=/\n(?!$)/g,g=function(d){var f=c(d)["white-space"];if("pre-wrap"===f||"pre-line"===f){f=d.querySelector("code");var b=d.querySelector(".line-numbers-rows"),e=d.querySelector(".line-numbers-sizer");d=f.textContent.split(a);e||(e=document.createElement("span"),e.className="line-numbers-sizer",f.appendChild(e));e.style.display="block";d.forEach(function(a,d){e.textContent=a||"\n";a=e.getBoundingClientRect().height;b.children[d].style.height=
a+"px"});e.textContent="";e.style.display="none"}},c=function(a){return a?window.getComputedStyle?getComputedStyle(a):a.currentStyle||null:null};window.addEventListener("resize",function(){Array.prototype.forEach.call(document.querySelectorAll("pre.line-numbers"),g)});Prism.hooks.add("complete",function(d){if(d.code){var c=d.element.parentNode,b=/\s*\bline-numbers\b\s*/;if(c&&/pre/i.test(c.nodeName)&&(b.test(c.className)||b.test(d.element.className))&&!d.element.querySelector(".line-numbers-rows")){b.test(d.element.className)&&
(d.element.className=d.element.className.replace(b," "));b.test(c.className)||(c.className+=" line-numbers");b=d.code.match(a);var e=Array((b?b.length+1:1)+1);e=e.join("<span></span>");b=document.createElement("span");b.setAttribute("aria-hidden","true");b.className="line-numbers-rows";b.innerHTML=e;c.hasAttribute("data-start")&&(c.style.counterReset="linenumber "+(parseInt(c.getAttribute("data-start"),10)-1));d.element.appendChild(b);g(c);Prism.hooks.run("line-numbers",d)}}});Prism.hooks.add("line-numbers",
function(a){a.plugins=a.plugins||{};a.plugins.lineNumbers=!0});Prism.plugins.lineNumbers={getLine:function(a,c){if("PRE"===a.tagName&&a.classList.contains("line-numbers")){var b=a.querySelector(".line-numbers-rows");a=parseInt(a.getAttribute("data-start"),10)||1;var d=a+(b.children.length-1);a>c&&(c=a);c>d&&(c=d);return b.children[c-a]}}}}}();
