var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(b,d,c){if(null==b)throw new TypeError("The 'this' value for String.prototype."+c+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+c+" must not be a regular expression");return b+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,c){b!=Array.prototype&&b!=Object.prototype&&(b[d]=c.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,d,c,e){if(d){c=$jscomp.global;b=b.split(".");for(e=0;e<b.length-1;e++){var f=b[e];f in c||(c[f]={});c=c[f]}b=b[b.length-1];e=c[b];d=d(e);d!=e&&null!=d&&$jscomp.defineProperty(c,b,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("String.prototype.repeat",function(b){return b?b:function(b){var c=$jscomp.checkStringArgs(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var d="";b;)if(b&1&&(d+=c),b>>>=1)c+=c;return d}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(b){return b?b:function(b,c,e){var d=this.length||0;0>c&&(c=Math.max(0,d+c));if(null==e||e>d)e=d;e=Number(e);0>e&&(e=Math.max(0,d+e));for(c=Number(c||0);c<e;c++)this[c]=b;return this}},"es6","es3");$jscomp.polyfill("Math.log10",function(b){return b?b:function(b){return Math.log(b)/Math.LN10}},"es6","es3");
var tileD=32,screenW=42*tileD,screenH=49*tileD,screenRatio=screenW/screenH,arenaX1=8*tileD,arenaY1=14*tileD,arenaD=screenW-2*arenaX1,arenaRate=arenaD/25,nglad=0,json,loadglads=!1,startsim=!1,loadCache=!1,stab,gender,simtimenow,sfxVolume=1,dt=0,showFrames=!0,actionlist=[{name:"fireball",value:0,animation:"cast"},{name:"teleport",value:1,animation:"cast"},{name:"charge",value:2,animation:"walk"},{name:"block",value:3,animation:"cast"},{name:"assassinate",value:4,animation:"shoot"},{name:"ambush",value:5,
animation:"cast"},{name:"melee",value:6,animation:"melee"},{name:"ranged",value:7,animation:"shoot"},{name:"movement",value:8,animation:"walk"},{name:"waiting",value:9,animation:"none"},{name:"none",value:10,animation:"none"}],animationlist={walk:{start:8,frames:9},cast:{start:0,frames:7},shoot:{start:16,frames:10},stab:{start:4,frames:8},slash:{start:12,frames:6},die:{start:20,frames:6}};function phaser_update(b){json=b;0==nglad&&loadCache&&(nglad=json.glads.length)}var game;
function load_phaser(){game&&game.destroy();game=new Phaser.Game({width:$(document).width(),height:$(document).height(),renderer:Phaser.WEBGL_MULTI,parent:"canvas-div",antialias:!0,multitexture:!0,enableDebug:!1,state:{preload:preload,create:create,update:update,render:render}})}
function preload(){game.load.onLoadStart.add(loadStart,this);game.load.onFileComplete.add(fileComplete,this);game.load.onLoadComplete.add(loadComplete,this);for(i=0;i<hashes.length;i++)game.cache.addSpriteSheet("glad"+i,null,hashes[i],192,192);game.load.audio("music","res/audio/adventure.mp3");game.load.audio("ending","res/audio/ending.mp3");game.load.audio("victory","res/audio/victory.mp3");game.load.audio("fireball","res/audio/fireball.mp3");game.load.audio("explosion","res/audio/explosion.mp3");
game.load.audio("teleport","res/audio/teleport.mp3");game.load.audio("charge_male","res/audio/charge_male.mp3");game.load.audio("charge_female","res/audio/charge_female.mp3");game.load.audio("block","res/audio/block.mp3");game.load.audio("assassinate","res/audio/assassinate.mp3");game.load.audio("ambush","res/audio/ambush.mp3");game.load.audio("ranged","res/audio/ranged.mp3");game.load.audio("arrow_hit","res/audio/arrow_hit.mp3");game.load.audio("stun","res/audio/stun.mp3");game.load.audio("melee",
"res/audio/melee.mp3");game.load.audio("lvlup","res/audio/lvlup.mp3");game.load.audio("death_male","res/audio/death_male.mp3");game.load.audio("death_female","res/audio/death_female.mp3");game.load.spritesheet("dummy","res/glad.png",64,64);game.load.atlas("atlas_crowd","res/atlas_crowd.png","res/atlas_crowd.json");game.load.atlas("atlas_effects","res/atlas_effects.png","res/atlas_effects.json");game.load.atlas("background","res/layers.png","res/layers.json");game.load.start();loadCache=!0;resize();
$("#canvas-div canvas").focus();game.camera&&game.camera.focusOnXY(screenW*game.camera.scale.x/2,screenH*game.camera.scale.y/2)}function loadStart(){$("#loadbar #status").html("Preparando recursos");$("#loadbar #second .bar").width(0)}function fileComplete(b,d,c,e,f){$("#loadbar #status").html("Carregando recursos");$("#loadbar #second .bar").width(b+"%");$("#loadbar #main .bar").width(50+b/2+"%")}function loadComplete(){$("#loadbar #status").html("Tudo pronto")}
var layers=[],sprite=[],sproj=[],gladArray=[],projArray=[],music,ending,victory,clones=[],poison=Math.sqrt(2*Math.pow(arenaD/2,2))/arenaRate,gasl=[],groupglad,groupgas,groupnpc=[],bar={},npc,audio={},textures;
function create(){textures=game.renderer.setTexturePriority(["atlas_crowd","atlas_effects"]);game.physics.startSystem(Phaser.Physics.ARCADE);groupglad=game.add.group();groupgas=game.add.group();groupnpc.push(game.add.group());groupnpc.push(game.add.group());groupglad.add(groupgas);groupglad.add(groupnpc[0]);groupglad.add(groupnpc[1]);for(var b=0;3>=b;b++)layers.push(game.add.image(0,0,"background","layer_"+b)),groupglad.add(layers[b]);music=game.add.audio("music",.5,!0);ending=game.add.audio("ending");
victory=game.add.audio("victory");game.input.mouse.onMouseWheel=zoomWheel;game.input.onDown.add(function(b){b.button===Phaser.Mouse.LEFT_BUTTON&&(game.input.mouse.drag=!0)},this);game.input.mouse.drag=!1;game.input.onUp.add(function(b){game.input.mouse.drag=!1},this);initBars();fillPeople();$.each(npc,function(b,c){var d=getPosArena(c.x,c.y,!0);c.sprite={};if(b.match(/royalguard\d/g)||b.match(/commonguard\d/g)||b.match(/archer\d/g)){c.sprite.body=game.add.sprite(d.x,d.y,"atlas_crowd");c.sprite.gear=
game.add.sprite(d.x,d.y,"atlas_crowd");if(b.match(/archer\d/g)){var f=[0,1,2,2,1,0],g={body:"dummy_grey_"+c.gender+"_",gear:"archer_"+c.gender+"_"};c.sprite.body.animations.add("guard",buildFrames(g.body,f,c.start.body,2),c.time,!1);c.sprite.gear.animations.add("guard",buildFrames(g.gear,f,c.start.gear),c.time,!1);game.time.events.repeat(Phaser.Timer.SECOND*c.interval,1E3,function(){c.sprite.body.animations.play("guard");c.sprite.gear.animations.play("guard")},this)}else b.match(/royalguard\d/g)?
(f=[-1,0,1,0],g={body:"dummy_grey_"+c.gender+"_",gear:"royal_"+c.gender+"_"},c.sprite.body.animations.add("guard",buildFrames(g.body,f,c.start.body,2),c.time,!1),c.sprite.gear.animations.add("guard",buildFrames(g.gear,f,c.start.gear),c.time,!1),game.time.events.repeat(Phaser.Timer.SECOND*c.interval,1E3,function(){c.sprite.body.animations.play("guard");c.sprite.gear.animations.play("guard")},this)):b.match(/commonguard\d/g)&&(f=[0,1],g={body:"dummy_grey_"+c.gender+"_",gear:"guard_"+c.gender+"_"},c.sprite.body.animations.add("guard",
buildFrames(g.body,f,c.start.body,2),c.time,!0),c.sprite.gear.animations.add("guard",buildFrames(g.gear,f,c.start.gear,0,{start:0,end:3}),c.time,!0),c.sprite.body.animations.play("guard"),c.sprite.gear.animations.play("guard"));c.sprite.body.animations.play("guard");c.sprite.gear.animations.play("guard")}else"king"==b||"queen"==b?(c.sprite.body=game.add.sprite(d.x,d.y,"atlas_crowd"),f=[0,1,0],g={body:"dummy_grey_"+c.gender+"_",gear:"guard_"+c.gender+"_",hair:"hair_"+c.gender+"_"+c.hair.style+"_0"},
c.sprite.body.animations.add("watch",buildFrames(g.body,f,c.start.body,2),c.time,!1),c.sprite.body.animations.play("watch"),game.time.events.repeat(Phaser.Timer.SECOND*c.interval,1E3,function(){c.sprite.body.animations.play("watch")},this),c.sprite.gear=c.color?game.add.sprite(d.x,d.y,"atlas_crowd",b+"-blue"):game.add.sprite(d.x,d.y,"atlas_crowd",b+"-red"),"no_hair"!=c.hair.style&&(c.sprite.hair=game.add.sprite(d.x,d.y,"atlas_crowd",g.hair+c.start.hair))):(c.sprite.body=game.add.sprite(d.x,d.y,"atlas_crowd"),
"no_hair"!=c.hair.style&&(c.sprite.hair=game.add.sprite(d.x,d.y,"atlas_crowd")),c.sprite.shirt=game.add.sprite(d.x,d.y,"atlas_crowd"),c.sprite.pants=game.add.sprite(d.x,d.y,"atlas_crowd"),c.sprite.shoes=game.add.sprite(d.x,d.y,"atlas_crowd"));for(var h in c.sprite){groupnpc[c.layer-1].add(c.sprite[h]);c.sprite[h].scale.setTo(game.camera.scale.x,game.camera.scale.y);c.sprite[h].anchor.setTo(.5,.5);if("hair"==h&&"no_hair"!=c.hair.style)g="hair_"+c.gender+"_"+c.hair.style+"_",b=[0],c.cheer&&(b=c.anim.hair),
c.sprite[h].animations.add("cheer",buildFrames(g,b,c.start.hair,2),c.time,!0),c.sprite[h].tint=c.hair.color;else if("shoes"==h)"male"==c.gender&&(k=1),g="shoes_"+c.gender+"_",c.sprite[h].animations.add("cheer",buildFrames(g,[0],c.start.shoes,k),c.time,!0);else{var k=2;f=[0,1];if("body"==h)c.sprite[h].tint=c.skin.tint,g="cheer_"+c.gender+"_";else if("pants"==h||"shirt"==h)c.sprite[h].tint=clothesColor(),b="","shirt"==h&&"female"==c.gender&&(b=parseInt(2*Math.random()+1)),g="cheer_"+h+b+"_"+c.gender+
"_";c.sprite[h].animations.add("cheer",buildFrames(g,f,c.start.body,k),c.time,!0)}c.cheer&&c.sprite[h].animations.play("cheer")}})}var mt,ma=null,ta=0,tc=0;function measureTime(b){ma||(ma=new Date);"s"==b?mt=new Date:"e"==b&&(ta+=new Date-mt,tc++,1E3<=new Date-ma&&(console.log(ta/tc),ma=null,ta=tc=0))}var gasld=4,gaspl=25;
function update(){if(json.poison){poison=parseFloat(json.poison);if(1<=Math.sqrt(2*Math.pow(arenaD/2,2))/arenaRate/poison&&(0==gasl.length||(17-poison)/gasld>gasl.length-1)){for(var b=[],d=0;d<gaspl;d++)b.push(game.add.image(0,0,"atlas_effects","gas")),b[d].anchor.setTo(.5,.5),b[d].scale.setTo(b[d].width/arenaRate*3),b[d].rotSpeed=1*Math.random()-.5,b[d].alpha=0,groupgas.add(b[d]);gasl.push(b)}for(b=0;b<gasl.length;b++)for(d=0;d<gasl[b].length;d++){var c=360/gasl[b].length*d;c=c*Math.PI/180;var e=
12.5+(poison+b*gasld+gasl[b][d].width/2/arenaRate)*Math.sin(c);c=12.5+(poison+b*gasld+gasl[b][d].height/2/arenaRate)*Math.cos(c);gasl[b][d].angle+=gasl[b][d].rotSpeed;1>gasl[b][d].alpha&&(gasl[b][d].alpha+=.005);gasl[b][d].x=arenaX1+e*arenaRate;gasl[b][d].y=arenaY1+c*arenaRate}}if(0<nglad&&!loadglads){loadglads=!0;for(b=0;b<nglad;b++)textures.length<game.renderer.maxTextures&&game.renderer.currentBatchedTextures.push("glad"+newindex[b]),sprite[b]=game.add.sprite(arenaX1+parseFloat(json.glads[b].x)*
arenaRate,arenaY1+parseFloat(json.glads[b].y)*arenaRate,"glad"+newindex[b]),sprite[b].anchor.setTo(.5,.5),createAnimation(b,"walk"),createAnimation(b,"melee"),createAnimation(b,"slash"),createAnimation(b,"stab"),createAnimation(b,"shoot"),createAnimation(b,"cast"),sprite[b].animations.add("die",arrayFill(260,265),10,!1),groupglad.add(sprite[b]),gladArray[b]={x:0,y:0,hp:parseFloat(json.glads[b].hp),alive:!0,fade:0,clone:null,invisible:!1,stun:!1,assassinate:!1,level:1,block:!1,charge:!1,poison:!1,
xp:parseInt(json.glads[b].xp),time:!1,sprites:{}};music.play();music.volume=$("#sound").data("music")}else if(0<sprite.length){startsim||(startsim=!0,$("#fog").remove(),$("#canvas-container").css({opacity:1}),resize(),pausesim=!1);if(json&&simtimenow!=json.simtime)for(b=0;b<nglad;b++){d=parseFloat(json.glads[b].x);e=parseFloat(json.glads[b].y);c=parseInt(json.glads[b].action);var f=parseInt(json.glads[b].lvl),g=parseInt(json.glads[b].xp),h=parseFloat(json.glads[b].head),k=parseFloat(json.glads[b].hp),
n=parseFloat(json.glads[b].lockedfor);sprite[b].x=arenaX1+d*arenaRate;sprite[b].y=arenaY1+e*arenaRate;showMessageBaloon(b);showHpApBars(b);f!=gladArray[b].level&&(gladArray[b].level=f,f=addSprite(gladArray[b],"lvlup",sprite[b].x,sprite[b].y),f.anchor.setTo(.5,.35),f.animations.play("lvlup",null,!1,!0),groupglad.add(f),playAudio("lvlup",sfxVolume));k!=gladArray[b].hp&&("fireball"==actionlist[c].name&&.1<json.glads[b].buffs.burn.timeleft&&(f=addSprite(gladArray[b],"explode",sprite[b].x,sprite[b].y),
f.anchor.setTo(.5,.5),f.alpha=.5,f.width=5*arenaRate,f.height=3*arenaRate,f.animations.play("explode",null,!1,!0),playAudio("explosion",sfxVolume)),gladArray[b].hp=k);if(0>=k)gladArray[b].alive&&(sprite[b].animations.play("die"),"male"==gender[newindex[b]]?playAudio("death_male",sfxVolume):playAudio("death_female",sfxVolume)),gladArray[b].alive=!1;else if(gladArray[b].alive=!0,k=actionlist[c].animation+"-"+getActionDirection(h),"movement"==actionlist[c].name)sprite[b].animations.play(k);else if("charge"==
actionlist[c].name)gladArray[b].charge||(sprite[b].animations.stop(),sprite[b].animations.play(k,50,!0),gladArray[b].charge=!0,"male"==gender[newindex[b]]?playAudio("charge_male",sfxVolume):playAudio("charge_female",sfxVolume));else if(actionlist[c]&&"none"!=actionlist[c].animation&&gladArray[b].time!=json.simtime){f=animationlist[actionlist[c].animation].frames;n+=.1;if("ranged"==actionlist[c].name||"melee"==actionlist[c].name)n*=2;n=Math.max(10,f/n);sprite[b].animations.stop();sprite[b].animations.play(k,
n);gladArray[b].time=json.simtime;"teleport"==actionlist[c].name&&0==gladArray[b].fade&&(gladArray[b].fade=1,gladArray[b].x=sprite[b].x,gladArray[b].y=sprite[b].y,playAudio("teleport",sfxVolume));"assassinate"==actionlist[c].name&&(gladArray[b].assassinate=!0);"block"==actionlist[c].name&&(gladArray[b].block=!1);"ranged"==actionlist[c].name&&playAudio("ranged",sfxVolume);"melee"==actionlist[c].name&&playAudio("melee",sfxVolume)}gladArray[b].invisible=.1<json.glads[b].buffs.invisible.timeleft?!0:!1;
gladArray[b].invisible?(1<=sprite[b].alpha&&playAudio("ambush",sfxVolume),.3<sprite[b].alpha&&(sprite[b].alpha-=.05)):1>sprite[b].alpha&&(sprite[b].alpha+=.05);1!=gladArray[b].fade||gladArray[b].x==sprite[b].x&&gladArray[b].y==sprite[b].y?2==gladArray[b].fade&&(sprite[b].alpha+=.05,1<=sprite[b].alpha&&(sprite[b].alpha=1,gladArray[b].fade=0)):(clones.push(game.add.sprite(gladArray[b].x,gladArray[b].y,sprite[b].key,sprite[b].frame)),clones[clones.length-1].anchor.setTo(.5,.5),clones[clones.length-1].alpha=
1,sprite[b].alpha=0,gladArray[b].fade=2);for(l in clones)clones[l].alpha-=.05,0>=clones[l].alpha&&(clones[l].destroy(),clones.splice(l,1));!gladArray[b].stun&&.1<json.glads[b].buffs.stun.timeleft&&gladArray[b].alive?(gladArray[b].stun=addSprite(gladArray[b],"stun",sprite[b].x,sprite[b].y),gladArray[b].stun.anchor.setTo(.5,1),gladArray[b].stun.scale.setTo(.6),gladArray[b].stun.animations.play("stun",null,!0,!1),playAudio("stun",sfxVolume)):gladArray[b].stun&&(.1>=json.glads[b].buffs.stun.timeleft||
!gladArray[b].alive)&&(gladArray[b].stun.kill(),gladArray[b].stun=!1);!gladArray[b].block&&.1<json.glads[b].buffs.resist.timeleft?(gladArray[b].block=!0,n=addSprite(gladArray[b],"shield",sprite[b].x,sprite[b].y),n.anchor.setTo(.5),groupglad.add(n),n.animations.play("shield",null,!1,!0),n.alpha=.5,playAudio("block",sfxVolume)):gladArray[b].block&&.1>=json.glads[b].buffs.resist.timeleft&&(gladArray[b].block=!1);gladArray[b].charge&&(g!=gladArray[b].xp?(sprite[b].animations.currentAnim.speed=15,k="0"==
stab[newindex[b]]?"slash-"+getActionDirection(h):"stab-"+getActionDirection(h),sprite[b].animations.stop(),sprite[b].animations.play(k,20),playAudio("melee",sfxVolume)):"charge"!=actionlist[c].name&&(sprite[b].animations.currentAnim.speed=15,gladArray[b].charge=!1));gladArray[b].poison=Math.sqrt(Math.pow(12.5-d,2)+Math.pow(12.5-e,2))>=poison?!0:!1;sprite[b].tint=json.glads[b].buffs.burn&&.1<json.glads[b].buffs.burn.timeleft?16756850:gladArray[b].poison?9895318:gladArray[b].block?16770355:16777215;
gladArray[b].xp=g;timeSlider!=Math.floor(json.simtime)&&(timeSlider=json.simtime,$("#time").slider("value",10*parseFloat(json.simtime)));update_ui(json)}debugTimer()}if(simtimenow!=json.simtime){if(json.projectiles&&0<json.projectiles.length)for(d=json.projectiles.length,b=0;b<d;b++){e=json.projectiles[b].id;c=json.projectiles[b].type;var l=findProj(e);if(-1==l){if(0==json.projectiles[b].type)var p=newProjectile("arrow");else 1==json.projectiles[b].type?(p=newProjectile("fireball"),p.animations.play("fireball"),
playAudio("fireball",sfxVolume)):2==json.projectiles[b].type&&(p=newProjectile("arrow"),p.tint=65280);gladArray[json.projectiles[b].owner]&&gladArray[json.projectiles[b].owner].assassinate&&(gladArray[json.projectiles[b].owner].assassinate=!1,p=newProjectile("arrow"),p.tint=16711680,playAudio("assassinate",sfxVolume));p.anchor.setTo(.5,.5);l=sproj.length;sproj.push({sprite:p,active:!0,id:e,type:c})}sproj[l].sprite.x=arenaX1+parseFloat(json.projectiles[b].x)*arenaRate;sproj[l].sprite.y=arenaY1+parseFloat(json.projectiles[b].y)*
arenaRate;sproj[l].sprite.angle=parseFloat(json.projectiles[b].head)+90;sproj[l].active=!0}for(var m in sproj)!1===sproj[m].active?(1==sproj[m].type?(f=newProjectile("explode",sproj[m].sprite.x,sproj[m].sprite.y),f.anchor.setTo(.5,.5),f.alpha=.5,f.width=5*arenaRate,f.height=3*arenaRate,f.animations.play("explode",null,!1,!0),playAudio("explosion",sfxVolume)):playAudio("arrow_hit",sfxVolume),sproj[m].sprite.kill(),sproj.splice(m,1)):sproj[m].active=!1;groupglad.sort("y",Phaser.Group.SORT_ASCENDING);
for(b=0;b<nglad;b++)gladArray[b].alive||groupglad.sendToBack(sprite[b]);groupglad.sendToBack(layers[0]);groupglad.bringToTop(groupgas);groupglad.bringToTop(layers[1]);groupglad.bringToTop(groupnpc[0]);groupglad.bringToTop(layers[2]);groupglad.bringToTop(groupnpc[1]);groupglad.bringToTop(layers[3])}game.input.mouse.drag&&(game.camera.target&&($(".ui-glad").removeClass("follow"),game.camera.unfollow()),game.camera.view.y-=game.input.speed.y,game.camera.view.x-=game.input.speed.x,$(".baloon").remove());
(game.input.keyboard.isDown(Phaser.Keyboard.NUMPAD_ADD)||game.input.keyboard.isDown(Phaser.Keyboard.EQUALS))&&zoomWheel({deltaY:-1});(game.input.keyboard.isDown(Phaser.Keyboard.NUMPAD_SUBTRACT)||game.input.keyboard.isDown(Phaser.Keyboard.UNDERSCORE))&&zoomWheel({deltaY:1});game.input.keyboard.isDown(Phaser.Keyboard.LEFT)&&(game.camera.view.x-=10);game.input.keyboard.isDown(Phaser.Keyboard.RIGHT)&&(game.camera.view.x+=10);game.input.keyboard.isDown(Phaser.Keyboard.UP)&&(game.camera.view.y-=10);game.input.keyboard.isDown(Phaser.Keyboard.DOWN)&&
(game.camera.view.y+=10);simtimenow=json.simtime}function render(){}function findProj(b){for(i in sproj)if(sproj[i].id==b)return i;return-1}function arrayFill(b,d){for(a=[];b<=d;b++)a.push(b);return a}function getActionDirection(b){return 45<=b&&135>=b?"right":135<b&&225>b?"down":225<=b&&315>=b?"left":"up"}
function createAnimation(b,d){var c=["-up","-left","-down","-right"];if("melee"==d){var e="0"==stab[newindex[b]]?"slash":"stab";animationlist.melee=animationlist[e]}else e=d;for(var f=0;4>f;f++){var g=13*(animationlist[e].start+f);sprite[b].animations.add(d+c[f],arrayFill(g,g+animationlist[e].frames-1),15,!1)}}
function update_ui(b){if(showFrames){var d=b.glads.length,c={};for(i=0;i<d;c={$jscomp$loop$prop$j$19:c.$jscomp$loop$prop$j$19},i++){var e=b.glads[i].name,f=b.glads[i].STR,g=b.glads[i].AGI,h=b.glads[i].INT,k=parseInt(b.glads[i].hp),n=parseInt(b.glads[i].maxhp),l=parseInt(b.glads[i].ap),p=parseInt(b.glads[i].maxap),m=parseInt(b.glads[i].lvl),q=parseInt(b.glads[i].xp),r=parseFloat(b.glads[i].buffs.burn.timeleft),t=parseFloat(b.glads[i].buffs.resist.timeleft),u=parseFloat(b.glads[i].buffs.stun.timeleft),
v=parseFloat(b.glads[i].buffs.invisible.timeleft),w=parseFloat(b.glads[i].buffs.movement.timeleft);if(gladArray[i])var x=gladArray[i].poison;uiVars[i].name||(uiVars[i].name=e,$(".glad-name span").eq(i).html(e),$(".glad-portrait").eq(i).append(getSpriteThumb(hashes[newindex[i]],"walk","down")));uiVars[i].STR!==f&&(uiVars[i].STR=f,$(".glad-str span").eq(i).html(f));uiVars[i].AGI!==g&&(uiVars[i].AGI=g,$(".glad-agi span").eq(i).html(g));uiVars[i].INT!==h&&(uiVars[i].INT=h,$(".glad-int span").eq(i).html(h));
uiVars[i].lvl!=m&&(uiVars[i].lvl=m,$(".lvl-value span").eq(i).html(m),$(".lvl-value").eq(i).addClass("up"),c.$jscomp$loop$prop$j$19=i,setTimeout(function(b){return function(){$(".lvl-value").eq(b.$jscomp$loop$prop$j$19).removeClass("up")}}(c),500));uiVars[i].xp!=q&&(uiVars[i].xp=q,$(".xp-bar .filled").eq(i).height(q+"%"));uiVars[i].hp!=k&&(uiVars[i].hp=k,$(".hp-bar .filled").eq(i).width(k/n*100+"%"));0>=k?(uiVars[i].dead=!0,$(".ui-glad").eq(i).addClass("dead")):uiVars[i].dead&&(uiVars[i].dead=!1,
$(".ui-glad").eq(i).removeClass("dead"));uiVars[i].ap!=l&&(uiVars[i].ap=l,$(".ap-bar .filled").eq(i).width(l/p*100+"%"));r?(uiVars[i].burn=!0,$(".buff-burn").eq(i).addClass("active")):uiVars[i].burn&&(uiVars[i].burn=!1,$(".buff-burn").eq(i).removeClass("active"));t?(uiVars[i].resist=!0,$(".buff-resist").eq(i).addClass("active")):uiVars[i].resist&&(uiVars[i].resist=!1,$(".buff-resist").eq(i).removeClass("active"));u?(uiVars[i].stun=!0,$(".buff-stun").eq(i).addClass("active")):uiVars[i].stun&&(uiVars[i].stun=
!1,$(".buff-stun").eq(i).removeClass("active"));v?(uiVars[i].invisible=!0,$(".buff-invisible").eq(i).addClass("active")):uiVars[i].invisible&&(uiVars[i].invisible=!1,$(".buff-invisible").eq(i).removeClass("active"));w?(uiVars[i].speed=!0,$(".buff-speed").eq(i).addClass("active")):uiVars[i].speed&&(uiVars[i].speed=!1,$(".buff-speed").eq(i).removeClass("active"));x?(uiVars[i].poison=!0,$(".buff-poison").eq(i).addClass("active")):uiVars[i].poison&&(uiVars[i].poison=!1,$(".buff-poison").eq(i).removeClass("active"))}}}
var showFPS=!1,oldTime=null,avgFPS=0,contFPS=0,avgFPS5=[];
function debugTimer(){if(showFPS){var b=function(){setTimeout(function(){if(0<contFPS){avgFPS=1E3/(avgFPS/contFPS);contFPS=0;avgFPS5.push(avgFPS);5<avgFPS5.length&&avgFPS5.splice(0,1);avgFPS=0;for(var c in avgFPS5)avgFPS+=avgFPS5[c];avgFPS/=avgFPS5.length;$("#fps").html("FPS: "+parseFloat(avgFPS).toFixed(1))}$("#fps").length?b():(avgFPS5=[],contFPS=avgFPS=0)},1E3)};if(oldTime){var d=new Date;avgFPS+=d-oldTime;contFPS++;oldTime=d}else oldTime=new Date;$("#fps").length||($("#canvas-container").append("<div id='fps'></fps>"),
b())}else $("#fps").length&&$("#fps").remove()}
$(window).keydown(function(b){b.keyCode==Phaser.Keyboard.S&&$("#sound").click();b.keyCode==Phaser.Keyboard.F&&(showFPS=(showFPS+1)%2,$.post("back_play.php",{action:"SET_PREF",show_fps:1==showFPS}));b.keyCode==Phaser.Keyboard.B&&(showbars=(showbars+1)%2,$.post("back_play.php",{action:"SET_PREF",show_bars:1==showbars}));b.keyCode==Phaser.Keyboard.M&&(showFrames?($("#ui-container").fadeOut(),showFrames=!1):($("#ui-container").fadeIn(),showFrames=!0),$.post("back_play.php",{action:"SET_PREF",show_frames:showFrames}));
b.keyCode==Phaser.Keyboard.SPACEBAR&&$("#pause").click();b.keyCode==Phaser.Keyboard.A&&$("#back-step").click();b.keyCode==Phaser.Keyboard.D&&$("#fowd-step").click();b.keyCode>=Phaser.Keyboard.ONE&&b.keyCode<=Phaser.Keyboard.FIVE&&(b=b.keyCode-Phaser.Keyboard.ONE,$(".ui-glad").eq(b).click())});
function getGladPositionOnCanvas(b){var d=game.camera.scale.y*tileD,c=game.camera.scale.x*tileD;c=arenaX1/tileD*c+c*parseFloat(json.glads[b].x);b=arenaY1/tileD*d+d*parseFloat(json.glads[b].y);d=$("#canvas-div canvas").position().top-game.camera.view.y;var e=$("#canvas-div canvas").position().left-game.camera.view.x;return{x:c+e,y:b+d}}
function showMessageBaloon(b){var d=json.glads[b].message;if(""!=d&&0<json.glads[b].hp){var c=getGladPositionOnCanvas(b);$(".baloon.glad-"+b).length?$(".baloon.glad-"+b).html(d):$("#canvas-div").append("<div class='baloon glad-"+b+"'>"+d+"</div>");d=$(".baloon.glad-"+b);var e=c.x+15*game.camera.scale.x;c=c.y-15*game.camera.scale.y-d.outerHeight();d.css({top:c,left:e});200>d.width()&&50<=d.height()?(d.css({left:e-230}),d.addClass("left")):d.hasClass("left")&&d.removeClass("left");gladArray[b].baloon=
!0}else gladArray[b].baloon&&$(".baloon.glad-"+b).fadeOut(function(){$(this).remove();gladArray[b].baloon=null})}function initBars(){var b=game.add.graphics(0,0);b.beginFill(0);b.drawRect(-100,0,30,9);var d=game.add.graphics(0,0);d.beginFill(16711680);d.drawRect(-100,0,30,5);var c=game.add.graphics(0,0);c.beginFill(255);c.drawRect(-100,0,30,4);bar.back=b.generateTexture();bar.back.alpha=.15;bar.hp=d.generateTexture();bar.hp.alpha=.4;bar.ap=c.generateTexture();bar.ap.alpha=.4}var showbars=!0;
function showHpApBars(b){if(showbars){if(!gladArray[b].bars){var d={};d.back=game.add.sprite(0,0,bar.back);d.back.alpha=.15;d.hp=game.add.sprite(0,0,bar.hp);d.hp.alpha=.4;d.ap=game.add.sprite(0,0,bar.ap);d.ap.alpha=.4;gladArray[b].bars=d}if(0<json.glads[b].hp){d=arenaX1+json.glads[b].x*arenaRate;var c=arenaY1+json.glads[b].y*arenaRate,e=parseFloat(json.glads[b].hp),f=parseFloat(json.glads[b].maxhp),g=parseFloat(json.glads[b].ap);parseFloat(json.glads[b].maxap);gladArray[b].bars.back.x=d+-15;gladArray[b].bars.back.y=
c+-35;gladArray[b].bars.back.width=30;gladArray[b].bars.back.height=9;gladArray[b].bars.hp.x=d+-15;gladArray[b].bars.hp.y=c+-35;gladArray[b].bars.hp.width=e/f*30;gladArray[b].bars.hp.height=5;gladArray[b].bars.ap.x=d+-15;gladArray[b].bars.ap.y=c+-30;gladArray[b].bars.ap.width=g/f*30;gladArray[b].bars.ap.height=4;gladArray[b].bars.back.alive||(gladArray[b].bars.back.revive(),gladArray[b].bars.hp.revive(),gladArray[b].bars.ap.revive())}else gladArray[b].bars.back.kill(),gladArray[b].bars.hp.kill(),
gladArray[b].bars.ap.kill()}else gladArray[b].bars&&gladArray[b].bars.back.alive&&(gladArray[b].bars.back.kill(),gladArray[b].bars.hp.kill(),gladArray[b].bars.ap.kill())}
function zoomWheel(b){var d=1-b.deltaY/Math.abs(b.deltaY)*.05,c=screenW*game.camera.scale.x*d,e=screenH*game.camera.scale.y*d;b=(game.input.mouse.input.x+game.camera.x)/game.camera.scale.x;var f=(game.input.mouse.input.y+game.camera.y)/game.camera.scale.y;var g=$(window).width()>$(window).height()?e<=$(window).height()?"height":"none":c<=$(window).width()?"width":"none";"width"==g?(c=$(window).width(),e=$(window).width()*screenH/screenW,game.camera.scale.x=$(window).width()/screenW,game.camera.scale.y=
$(window).width()/screenW):"height"==g?(e=$(window).height(),c=$(window).height()*screenW/screenH,game.camera.scale.x=$(window).height()/screenH,game.camera.scale.y=$(window).height()/screenH):(game.camera.scale.x*=d,game.camera.scale.y*=d);c>$(window).width()&&(c=$(window).width());e>$(window).height()&&(e=$(window).height());game.scale.setGameSize(c,e);game.camera.bounds.width=screenW;game.camera.bounds.height=screenH;"none"==g&&(d=game.input.mouse.input.y,c=game.camera.scale.y,game.camera.x=b*
game.camera.scale.x-game.input.mouse.input.x,game.camera.y=f*c-d);$(".baloon").remove()}function getPosArena(b,d,c){b=(b+.5)*tileD;d=(d+.5)*tileD;void 0!==c&&c||(b+=arenaX1,d+=arenaY1);return{x:b,y:d}}
function fillPeople(){var b=Math.floor(2*Math.random());npc={king:{x:20,y:7.3,start:{body:0,hair:2},heading:"down",gender:"male",color:b,time:5,interval:2*Math.random()+3},queen:{x:21,y:7.3,start:{body:0,hair:4},heading:"down",gender:"female",color:b,time:5,interval:2*Math.random()+3},counselor1:{x:19,y:6.7,start:{body:4},heading:"down",gender:"male"},counselor2:{x:22,y:6.7,start:{body:4},heading:"down",gender:"male"},royalguard1:{x:16,y:4,start:{gear:2,body:4},heading:"down",time:.4*Math.random()+
.6,interval:6*Math.random()+8},royalguard2:{x:25,y:4,start:{gear:2,body:4},heading:"down",time:.4*Math.random()+.6,interval:6*Math.random()+8},archer1:{x:4,y:3,start:{gear:3,body:9},heading:"down",time:8,interval:2*Math.random()+7},archer2:{x:39,y:1,start:{gear:3,body:9},heading:"down",time:8,interval:2*Math.random()+7},archer3:{x:21,y:39,start:{gear:0,body:6},heading:"up",time:8,interval:2*Math.random()+7},commonguard1:{x:2,y:9,start:{gear:2,body:4},heading:"down",time:.1*Math.random()+.1},commonguard2:{x:39,
y:9,start:{gear:1,body:3},heading:"left",time:.1*Math.random()+.1},commonguard3:{x:2,y:40,start:{gear:3,body:5},heading:"right",time:.1*Math.random()+.1},commonguard4:{x:39,y:40,start:{gear:0,body:2},heading:"up",time:.1*Math.random()+.1}};b=[{name:"male",anims:3,prob:.7},{name:"female",anims:2,prob:.3}];for(var d in npc)npc[d].layer=1,npc[d].skin||(npc[d].skin=skinColor(d)),npc[d].gender||(npc[d].gender=b[weightedRoll([b[0].prob,b[1].prob])].name),npc[d].hair=getHair(npc[d].skin.name,npc[d].gender);
arenaSpaces=[{x:2.4,y:10.1,axis:1,capacity:29,fill:.3,heading:"right",layer:1},{x:3.4,y:10.4,axis:1,capacity:29,fill:.4,heading:"right",layer:1},{x:5.4,y:11,axis:1,capacity:29,fill:.5,heading:"right",layer:1},{x:6.4,y:11.3,axis:1,capacity:28,fill:.6,heading:"right",layer:1},{x:34.6,y:11.3,axis:1,capacity:28,fill:.6,heading:"left",layer:1},{x:35.6,y:11,axis:1,capacity:29,fill:.5,heading:"left",layer:1},{x:37.6,y:11.5,axis:1,capacity:29,fill:.4,heading:"left",layer:1},{x:38.6,y:11.2,axis:1,capacity:29,
fill:.3,heading:"left",layer:1},{x:8,y:5,axis:0,capacity:6,fill:.7,heading:"down",layer:1},{x:8.1,y:5.5,axis:0,capacity:7,fill:.8,heading:"down",layer:2},{x:8,y:9,axis:0,capacity:8,fill:.5,heading:"down",layer:1},{x:8.1,y:9.5,axis:0,capacity:8,fill:.6,heading:"down",layer:2},{x:28,y:5,axis:0,capacity:6,fill:.7,heading:"down",layer:1},{x:26.9,y:5.5,axis:0,capacity:7,fill:.8,heading:"down",layer:2},{x:26,y:9,axis:0,capacity:8,fill:.5,heading:"down",layer:1},{x:25.9,y:9.5,axis:0,capacity:8,fill:.6,heading:"down",
layer:2},{x:7,y:39.5,axis:0,capacity:10,fill:.6,heading:"up",layer:1},{x:5,y:40.5,axis:0,capacity:12,fill:.4,heading:"up",layer:2},{x:25,y:39.5,axis:0,capacity:10,fill:.6,heading:"up",layer:1},{x:25,y:40.5,axis:0,capacity:12,fill:.4,heading:"up",layer:2}];d={up:[0,8,16],left:[2,10,18],down:[4,12,20],right:[6,14,22]};var c={male:{up:0,left:3,down:1,right:4},female:{up:0,left:2,down:4,right:6}},e={male:[{up:0,left:1,down:2,right:3},{up:0,left:1,down:2,right:3},{up:4,left:6,down:8,right:10}],female:[{up:0,
left:2,down:4,right:6},{up:8,left:9,down:10,right:11}]},f={male:[[0,0],[0,0],[0,1]],female:[[0,1],[0,0]]},g=0,h;for(h in arenaSpaces)for(var k=0;k<arenaSpaces[h].capacity;k++)if(Math.random()<1*arenaSpaces[h].fill){var n=0,l=0;1==arenaSpaces[h].axis?l=k:n=k;var p=skinColor(),m=b[weightedRoll([b[0].prob,b[1].prob])],q=Math.floor(Math.random()*m.anims);npc["people"+g]={x:arenaSpaces[h].x+n,y:arenaSpaces[h].y+l,heading:arenaSpaces[h].heading,time:6*Math.random()+2,layer:arenaSpaces[h].layer,skin:p,gender:m.name,
hair:getHair(p.name,m.name),anims:m.anims,start:{body:d[arenaSpaces[h].heading][q],shoes:c[m.name][arenaSpaces[h].heading],hair:e[m.name][q][arenaSpaces[h].heading]},cheer:!0,anim:{hair:f[m.name][q]}};g++}}
function clothesColor(){var b=0,d=0,c=0,e=Math.random();.15>e?d=b=c=Math.round(200*Math.random()+50).toString(16):(.5>e?(e=Math.random(),.4>e?b=230:.6>e?d=180:c=200):c=d=b=150,b=Math.round(Math.random()*b).toString(16),d=Math.round(Math.random()*d).toString(16),c=Math.round(Math.random()*c).toString(16));2>b.length&&(b="0"+b);2>d.length&&(d="0"+d);2>c.length&&(c="0"+c);return"0x"+b+d+c}
function getHair(b,d){var c=0;var e={light:[.1,.25],black:[0,0],tanned:[.05,.15],dark:[0,.05],darkelf:[.2,.4],red_orc:[.1,.1]};var f=Math.random();f<e[b][0]?(e=90*Math.random()+110,f=55*Math.random()+70,c=25*Math.random()+55):f<e[b][1]+e[b][0]?(e=70*Math.random()+160,f=.8*e):(e=70*Math.random()+30,f=.75*e,c=30*Math.random()+20);e=Math.round(e).toString(16);f=Math.round(f).toString(16);c=Math.round(c).toString(16);2>e.length&&(e="0"+e);2>f.length&&(f="0"+f);2>c.length&&(c="0"+c);c="0x"+e+f+c;b=weightedRoll({male:{light:[.25,
.3,.1,.05,.3,.1],black:[.05,.05,.2,.4,.1,.4],tanned:[.35,.2,.1,.05,.3,.1],dark:[.15,.1,.2,.3,.25,.3],darkelf:[.3,.1,0,0,0,.8],red_orc:[.15,0,.3,.05,.1,.5]},female:{light:[.3,.05,.3,.3,.2,0],black:[.1,.6,.15,.3,.3,.02],tanned:[.3,.2,.3,.3,.2,.01],dark:[.2,.3,.2,.2,.3,.02],darkelf:[.1,0,.1,.4,.3,.2],red_orc:[.1,.05,.1,.2,.3,.2]}}[d][b]);return{color:c,style:{male:"ponytail parted mohawk jewfro bedhead no_hair".split(" "),female:"long jewfro loose longknot pixie no_hair".split(" ")}[d][b]}}
function skinColor(b){var d={light:{chance:.35,tint:"0xfdd5b7"},black:{chance:.1,tint:"0x61382d"},tanned:{chance:.25,tint:"0xfdd082"},dark:{chance:.2,tint:"0xba8454"},darkelf:{chance:.05,tint:"0xaeb3ca"},red_orc:{chance:.05,tint:"0x568b33"}};if("king"==b||"queen"==b)d.darkelf.chance=0,d.red_orc.chance=0,d.light.chance=.4,d.tanned.chance=.3;b=Math.random();for(var c in d){if(b<d[c].chance)return{name:c,tint:d[c].tint};b-=d[c].chance}}
function weightedRoll(b){var d=0,c;for(c in b)d+=b[c];for(var e in b)b[e]/=d;d=Math.random();for(var f in b){if(d<b[f])return f;d-=b[f]}return-1}
function addSprite(b,d,c,e){var f={lvlup:{key:"level",frames:20,frameRate:15,loop:!1},explode:{key:"explosion",frames:12,frameRate:15,loop:!0},stun:{key:"stun",frames:6,frameRate:15,loop:!0},shield:{key:"shield",frames:20,frameRate:15,loop:!1}};if(b.sprites[d])b.sprites[d].x=c,b.sprites[d].y=e,b.sprites[d].revive();else{var g=Math.floor(Math.log10(Math.max(1,f[d].frames)))+1;b.sprites[d]=game.add.sprite(c,e,"atlas_effects");c=Phaser.Animation.generateFrameNames(f[d].key+"_",0,f[d].frames-1,"",g);
b.sprites[d].animations.add(d,c,f[d].frameRate,f[d].loop)}return b.sprites[d]}projSprites={arrow:[],fireball:[],explode:[]};
function newProjectile(b,d,c){var e=null,f;for(f in projSprites[b])if(!projSprites[b][f].alive){e=f;break}"explode"!=b&&(c=d=0);e?(projSprites[b][e].x=d,projSprites[b][e].y=c,projSprites[b][e].tint=16777215,projSprites[b][e].revive()):(e=projSprites[b].length,"arrow"==b?projSprites[b].push(game.add.image(d,c,"atlas_effects","arrow")):(projSprites[b].push(game.add.sprite(d,c,"atlas_effects")),"fireball"==b&&(d=Phaser.Animation.generateFrameNames("fireball_",0,7,"",2),projSprites[b][e].animations.add("fireball",
d,15,!0)),"explode"==b&&(d=Phaser.Animation.generateFrameNames("explosion_",0,11,"",2),projSprites[b][e].animations.add("explode",d,15,!0))));return projSprites[b][e]}function playAudio(b,d){audio[b]||(audio[b]=[]);var c=null,e;for(e in audio[b])if(!audio[b][e].isPlaying){c=e;break}c?(audio[b][c].volume=d,audio[b][c].play()):audio[b].push(game.add.audio(b,d).play())}
function buildFrames(b,d,c,e,f){c||(c=0);e||(e=0);var g=[],h;for(h in d){var k=d[h]+c;f&&k>f.end&&(k=f.start);k="0000000".slice(Math.log10(Math.max(1,k))+1,e)+k;g.push(b+k)}return g};
