var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.checkStringArgs=function(b,d,e){if(null==b)throw new TypeError("The 'this' value for String.prototype."+e+" must not be null or undefined");if(d instanceof RegExp)throw new TypeError("First argument to String.prototype."+e+" must not be a regular expression");return b+""};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(b,d,e){b!=Array.prototype&&b!=Object.prototype&&(b[d]=e.value)};$jscomp.getGlobal=function(b){return"undefined"!=typeof window&&window===b?b:"undefined"!=typeof global&&null!=global?global:b};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(b,d,e,f){if(d){e=$jscomp.global;b=b.split(".");for(f=0;f<b.length-1;f++){var c=b[f];c in e||(e[c]={});e=e[c]}b=b[b.length-1];f=e[b];d=d(f);d!=f&&null!=d&&$jscomp.defineProperty(e,b,{configurable:!0,writable:!0,value:d})}};
$jscomp.polyfill("String.prototype.repeat",function(b){return b?b:function(b){var d=$jscomp.checkStringArgs(this,null,"repeat");if(0>b||1342177279<b)throw new RangeError("Invalid count value");b|=0;for(var f="";b;)if(b&1&&(f+=d),b>>>=1)d+=d;return f}},"es6","es3");
$jscomp.polyfill("Array.prototype.fill",function(b){return b?b:function(b,e,f){var c=this.length||0;0>e&&(e=Math.max(0,c+e));if(null==f||f>c)f=c;f=Number(f);0>f&&(f=Math.max(0,c+f));for(e=Number(e||0);e<f;e++)this[e]=b;return this}},"es6","es3");
var tileD=32,screenW=42*tileD,screenH=49*tileD,screenRatio=screenW/screenH,arenaX1=8*tileD,arenaY1=14*tileD,arenaD=screenW-2*arenaX1,arenaRate=arenaD/25,nglad=0,json,loadglads=!1,startsim=!1,loadCache=!1,stab,gender,simtimenow,sfxVolume=1,actionlist=[{name:"fireball",value:0,animation:"cast"},{name:"teleport",value:1,animation:"cast"},{name:"charge",value:2,animation:"walk"},{name:"block",value:3,animation:"cast"},{name:"assassinate",value:4,animation:"shoot"},{name:"ambush",value:5,animation:"cast"},
{name:"melee",value:6,animation:"melee"},{name:"ranged",value:7,animation:"shoot"},{name:"movement",value:8,animation:"walk"},{name:"waiting",value:9,animation:"none"},{name:"none",value:10,animation:"none"}],animationlist={walk:{start:8,frames:9},cast:{start:0,frames:7},shoot:{start:16,frames:10},stab:{start:4,frames:8},slash:{start:12,frames:6},die:{start:20,frames:6}};function phaser_update(b){json=b;0==nglad&&loadCache&&(nglad=json.glads.length)}var game;
function load_phaser(){game&&game.destroy();game=new Phaser.Game($(document).width(),$(document).height(),Phaser.AUTO,"canvas-div",{preload:preload,create:create,update:update,render:render})}
function preload(){game.load.onLoadStart.add(loadStart,this);game.load.onFileComplete.add(fileComplete,this);game.load.onLoadComplete.add(loadComplete,this);for(i=0;i<hashes.length;i++)game.cache.addSpriteSheet("glad"+i,null,hashes[i],192,192);game.load.image("layer0","res/layer0.png");game.load.image("layer1","res/layer1.png");game.load.image("layer2","res/layer2.png");game.load.image("layer3","res/layer3.png");game.load.image("arrow","res/arrow.png");game.load.image("gas","res/gas.png",50,50);game.load.spritesheet("fireball",
"res/fireball.png",64,64);game.load.spritesheet("explosion","res/explosion.png",256,128);game.load.spritesheet("stun","res/stun.png",96,64);game.load.spritesheet("level","res/level.png",192,192);game.load.spritesheet("shield","res/shield.png",192,192);game.load.audio("music","res/audio/adventure.mp3");game.load.audio("ending","res/audio/ending.mp3");game.load.audio("victory","res/audio/victory.mp3");game.load.audio("fireball","res/audio/fireball.mp3");game.load.audio("explosion","res/audio/explosion.mp3");
game.load.audio("teleport","res/audio/teleport.mp3");game.load.audio("charge_male","res/audio/charge_male.mp3");game.load.audio("charge_female","res/audio/charge_female.mp3");game.load.audio("block","res/audio/block.mp3");game.load.audio("assassinate","res/audio/assassinate.mp3");game.load.audio("ambush","res/audio/ambush.mp3");game.load.audio("ranged","res/audio/ranged.mp3");game.load.audio("arrow_hit","res/audio/arrow_hit.mp3");game.load.audio("stun","res/audio/stun.mp3");game.load.audio("melee",
"res/audio/melee.mp3");game.load.audio("lvlup","res/audio/lvlup.mp3");game.load.audio("death_male","res/audio/death_male.mp3");game.load.audio("death_female","res/audio/death_female.mp3");game.load.spritesheet("dummy","res/glad.png",64,64);game.load.spritesheet("cheer_male","res/cheer_male.png",64,64);game.load.spritesheet("cheer_female","res/cheer_female.png",64,64);game.load.spritesheet("cheer_shirt_male","res/cheer_shirt_male.png",64,64);game.load.spritesheet("cheer_shirt1_female","res/cheer_shirt1_female.png",
64,64);game.load.spritesheet("cheer_shirt2_female","res/cheer_shirt2_female.png",64,64);game.load.spritesheet("cheer_pants_male","res/cheer_pants_male.png",64,64);game.load.spritesheet("cheer_pants_female","res/cheer_pants_female.png",64,64);game.load.spritesheet("cheer_male_hair_parted","sprite/Universal-LPC-spritesheet/hair/male/parted.png",64,64);game.load.spritesheet("cheer_male_hair_ponytail","sprite/Universal-LPC-spritesheet/hair/male/ponytail.png",64,64);game.load.spritesheet("cheer_male_hair_mohawk",
"sprite/Universal-LPC-spritesheet/hair/male/mohawk.png",64,64);game.load.spritesheet("cheer_male_hair_jewfro","sprite/Universal-LPC-spritesheet/hair/male/jewfro.png",64,64);game.load.spritesheet("cheer_male_hair_bedhead","sprite/Universal-LPC-spritesheet/hair/male/bedhead.png",64,64);game.load.spritesheet("cheer_male_shoes","sprite/Universal-LPC-spritesheet/feet/shoes/male/black_shoes_male.png",64,64);game.load.spritesheet("cheer_female_hair_long","sprite/Universal-LPC-spritesheet/hair/female/long.png",
64,64);game.load.spritesheet("cheer_female_hair_jewfro","sprite/Universal-LPC-spritesheet/hair/female/jewfro.png",64,64);game.load.spritesheet("cheer_female_hair_loose","sprite/Universal-LPC-spritesheet/hair/female/loose.png",64,64);game.load.spritesheet("cheer_female_hair_longknot","sprite/Universal-LPC-spritesheet/hair/female/longknot.png",64,64);game.load.spritesheet("cheer_female_hair_pixie","sprite/Universal-LPC-spritesheet/hair/female/pixie.png",64,64);game.load.spritesheet("cheer_female_hair_pixie",
"sprite/Universal-LPC-spritesheet/hair/female/pixie.png",64,64);game.load.spritesheet("cheer_female_shoes","sprite/Universal-LPC-spritesheet/feet/shoes/female/black_shoes_female.png",64,64);game.load.spritesheet("dummy_grey_male","res/dummy_grey_male.png",192,192);game.load.spritesheet("dummy_grey_female","res/dummy_grey_female.png",192,192);game.load.spritesheet("royal_male","res/royal_male.png",192,192);game.load.spritesheet("royal_female","res/royal_female.png",192,192);game.load.spritesheet("guard_male",
"res/guard_male.png",192,192);game.load.spritesheet("guard_female","res/guard_female.png",192,192);game.load.spritesheet("archer_male","res/archer_male.png",192,192);game.load.spritesheet("archer_female","res/archer_female.png",192,192);game.load.spritesheet("king_blue","res/king-blue.png",64,64);game.load.spritesheet("king_red","res/king-red.png",64,64);game.load.spritesheet("queen_blue","res/queen-blue.png",64,64);game.load.spritesheet("queen_red","res/queen-red.png",64,64);game.load.start();loadCache=
!0;resize();$("#canvas-div canvas").focus();game.camera.focusOnXY(screenW*game.camera.scale.x/2,screenH*game.camera.scale.y/2)}function loadStart(){$("#loadbar #status").html("Preparando recursos");$("#loadbar #second .bar").width(0)}function fileComplete(b,d,e,f,c){$("#loadbar #status").html("Carregando recursos");$("#loadbar #second .bar").width(b+"%");$("#loadbar #main .bar").width(50+b/2+"%")}function loadComplete(){$("#loadbar #status").html("Tudo pronto")}
var layers=[],sprite=[],sproj=[],gladArray=[],projArray=[],music,ending,victory,clones=[],poison=Math.sqrt(2*Math.pow(arenaD/2,2))/arenaRate,gasl=[],groupglad,groupgas,groupnpc=[],bar={},npc;
function create(){game.physics.startSystem(Phaser.Physics.ARCADE);groupglad=game.add.group();groupgas=game.add.group();groupnpc.push(game.add.group());groupnpc.push(game.add.group());for(var b=0;3>=b;b++)layers.push(game.add.image(0,0,"layer"+b)),groupglad.add(layers[b]);music=game.add.audio("music",.5,!0);ending=game.add.audio("ending");victory=game.add.audio("victory");game.input.mouse.onMouseWheel=zoomWheel;game.input.onDown.add(function(b){b.button===Phaser.Mouse.LEFT_BUTTON&&(game.input.mouse.drag=
!0)},this);game.input.mouse.drag=!1;game.input.onUp.add(function(b){game.input.mouse.drag=!1},this);b=game.add.graphics(0,0);b.beginFill(0);b.drawRect(-100,0,30,9);var d=game.add.graphics(0,0);d.beginFill(16711680);d.drawRect(-100,0,30,5);var e=game.add.graphics(0,0);e.beginFill(255);e.drawRect(-100,0,30,4);bar.back=game.add.sprite(-100,0,b.generateTexture());bar.back.alpha=.15;bar.hp=game.add.sprite(-100,0,d.generateTexture());bar.hp.alpha=.4;bar.ap=game.add.sprite(-100,0,e.generateTexture());bar.ap.alpha=
.4;fillPeople();$.each(npc,function(b,c){var d=getPosArena(c.x,c.y,!0);c.sprite={};b.match(/royalguard\d/g)||b.match(/commonguard\d/g)||b.match(/archer\d/g)?("male"==c.gender?(c.sprite.body=game.add.sprite(d.x,d.y,"dummy_grey_male"),b.match(/royalguard\d/g)&&(c.sprite.gear=game.add.sprite(d.x,d.y,"royal_male")),b.match(/commonguard\d/g)&&(c.sprite.gear=game.add.sprite(d.x,d.y,"guard_male")),b.match(/archer\d/g)&&(c.sprite.gear=game.add.sprite(d.x,d.y,"archer_male"))):(c.sprite.body=game.add.sprite(d.x,
d.y,"dummy_grey_female"),b.match(/royalguard\d/g)&&(c.sprite.gear=game.add.sprite(d.x,d.y,"royal_female")),b.match(/commonguard\d/g)&&(c.sprite.gear=game.add.sprite(d.x,d.y,"guard_female")),b.match(/archer\d/g)&&(c.sprite.gear=game.add.sprite(d.x,d.y,"archer_female"))),b.match(/royalguard\d/g)?(c.sprite.body.animations.add("guard",[c.start-13,c.start,c.start+13,c.start],c.time,!1),c.sprite.gear.animations.add("guard",[c.start-13,c.start,c.start+13,c.start],c.time,!1),game.time.events.repeat(Phaser.Timer.SECOND*
c.interval,1E3,function(){c.sprite.body.animations.play("guard");c.sprite.gear.animations.play("guard")},this)):b.match(/commonguard\d/g)?(c.sprite.body.animations.add("guard",[c.start,c.start+13],c.time,!0),c.sprite.gear.animations.add("guard",[c.start,c.start+13],c.time,!0),c.sprite.body.animations.play("guard"),c.sprite.gear.animations.play("guard")):b.match(/archer\d/g)&&(c.sprite.body.animations.add("guard",[c.start,c.start+1,c.start+2,c.start+2,c.start+1,c.start],c.time,!1),c.sprite.gear.animations.add("guard",
[c.start,c.start+1,c.start+2,c.start+2,c.start+1,c.start],c.time,!1),game.time.events.repeat(Phaser.Timer.SECOND*c.interval,1E3,function(){c.sprite.body.animations.play("guard");c.sprite.gear.animations.play("guard")},this)),c.sprite.body.animations.play("guard"),c.sprite.gear.animations.play("guard")):"king"==b||"queen"==b?(c.sprite.body=game.add.sprite(d.x,d.y,"dummy_grey_"+c.gender),c.sprite.body.animations.add("watch",[c.start,c.start+1,c.start],c.time,!1),c.sprite.body.animations.play("watch"),
game.time.events.repeat(Phaser.Timer.SECOND*c.interval,1E3,function(){c.sprite.body.animations.play("watch")},this),c.sprite.gear=c.color?game.add.sprite(d.x,d.y,b+"_blue"):game.add.sprite(d.x,d.y,b+"_red"),"no_hair"!=c.hair.style&&(c.sprite.hair=game.add.sprite(d.x,d.y,"cheer_"+c.gender+"_hair_"+c.hair.style),c.sprite.hair.animations.add("watch",[c.start],c.time,!0),c.sprite.hair.animations.play("watch"))):(c.sprite.body=game.add.sprite(d.x,d.y,"cheer_"+c.gender),c.sprite.shirt="female"==c.gender?
.5>Math.random()?game.add.sprite(d.x,d.y,"cheer_shirt1_female"):game.add.sprite(d.x,d.y,"cheer_shirt2_female"):game.add.sprite(d.x,d.y,"cheer_shirt_male"),c.sprite.pants=game.add.sprite(d.x,d.y,"cheer_pants_"+c.gender),"no_hair"!=c.hair.style&&(c.sprite.hair=game.add.sprite(d.x,d.y,"cheer_"+c.gender+"_hair_"+c.hair.style)),c.sprite.shoes=game.add.sprite(d.x,d.y,"cheer_"+c.gender+"_shoes"));for(var e in c.sprite){groupnpc[c.layer-1].add(c.sprite[e]);c.sprite[e].scale.setTo(game.camera.scale.x,game.camera.scale.y);
c.sprite[e].anchor.setTo(.5,.5);if("hair"==e)b={male:[0,0,7,7,14,14,21,21,0,0,7,7,14,14,21,21,63,61,70,69,81,79,88,87],female:[0,173,7,103,14,109,21,115,3,3,10,10,17,17,24,24]},c.sprite[e].animations.add("cheer",arrayFrame([b[c.gender][c.start],b[c.gender][c.start+1]]),c.time,!0),c.sprite[e].tint=c.hair.color;else if("shoes"==e)b={male:[0,0,7,7,14,14,21,21,0,0,7,7,14,14,21,21,61,61,69,69,78,78,87,87],female:[0,173,7,103,14,109,21,115,3,3,10,10,17,17,24,24]},c.sprite[e].animations.add("cheer",arrayFrame([b[c.gender][c.start],
b[c.gender][c.start+1]]),c.time,!0);else{if("body"==e)c.sprite[e].tint=c.skin.tint;else if("pants"==e||"shirt"==e)c.sprite[e].tint=clothesColor();c.cheer&&c.sprite[e].animations.add("cheer",arrayFill(c.start,parseInt(c.start+1)),c.time,!0)}c.cheer&&c.sprite[e].animations.play("cheer")}})}var gasld=4,gaspl=25;
function update(){if(json.poison){poison=parseFloat(json.poison);if(1<=Math.sqrt(2*Math.pow(arenaD/2,2))/arenaRate/poison&&(0==gasl.length||(17-poison)/gasld>gasl.length-1)){for(var b=[],d=0;d<gaspl;d++)b.push(game.add.sprite(0,0,"gas")),b[d].anchor.setTo(.5,.5),b[d].scale.setTo(b[d].width/arenaRate*3),b[d].rotSpeed=1*Math.random()-.5,b[d].alpha=0,groupgas.add(b[d]);gasl.push(b)}for(b=0;b<gasl.length;b++)for(d=0;d<gasl[b].length;d++){var e=360/gasl[b].length*d;e=e*Math.PI/180;var f=12.5+(poison+b*
gasld+gasl[b][d].width/2/arenaRate)*Math.sin(e);e=12.5+(poison+b*gasld+gasl[b][d].height/2/arenaRate)*Math.cos(e);gasl[b][d].angle+=gasl[b][d].rotSpeed;1>gasl[b][d].alpha&&(gasl[b][d].alpha+=.005);gasl[b][d].x=arenaX1+f*arenaRate;gasl[b][d].y=arenaY1+e*arenaRate}groupglad.add(groupgas);groupglad.add(groupnpc[0]);groupglad.add(groupnpc[1])}if(0<nglad&&!loadglads){loadglads=!0;for(b=0;b<nglad;b++)sprite[b]=game.add.sprite(arenaX1+parseFloat(json.glads[b].x)*arenaRate,arenaY1+parseFloat(json.glads[b].y)*
arenaRate,"glad"+newindex[b]),sprite[b].anchor.setTo(.5,.5),createAnimation(b,"walk"),createAnimation(b,"melee"),createAnimation(b,"slash"),createAnimation(b,"stab"),createAnimation(b,"shoot"),createAnimation(b,"cast"),sprite[b].animations.add("die",arrayFill(260,265),10,!1),groupglad.add(sprite[b]),gladArray[b]={x:0,y:0,hp:parseFloat(json.glads[b].hp),alive:!0,fade:0,clone:null,invisible:!1,stun:!1,assassinate:!1,level:1,block:!1,charge:!1,poison:!1,xp:parseInt(json.glads[b].xp),time:!1},gladArray[b].bars=
game.add.bitmapData(arenaX1+25*arenaRate,arenaY1+25*arenaRate),gladArray[b].bars.addToWorld();music.play();music.volume=$("#sound").data("music")}else if(0<sprite.length){startsim||(startsim=!0,$("#fog").remove(),$("#canvas-container").css({opacity:1}),resize(),pausesim=!1);if(json&&simtimenow!=json.simtime)for(simtimenow=json.simtime,b=0;b<nglad;b++){var c=parseFloat(json.glads[b].x);d=parseFloat(json.glads[b].y);f=parseInt(json.glads[b].action);var g=parseInt(json.glads[b].lvl);e=parseInt(json.glads[b].xp);
var k=parseFloat(json.glads[b].head),l=parseFloat(json.glads[b].hp),h=parseFloat(json.glads[b].lockedfor);showMessageBaloon(b);sprite[b].x=arenaX1+c*arenaRate;sprite[b].y=arenaY1+d*arenaRate;showHpApBars(b);g>gladArray[b].level&&(gladArray[b].level=g,g=game.add.sprite(sprite[b].x,sprite[b].y,"level"),g.anchor.setTo(.5),g.scale.setTo(.4),groupglad.add(g),g.animations.add("levelup",null,15,!1),g.animations.play("levelup",null,!1,!0),game.add.audio("lvlup",sfxVolume).play());l!=gladArray[b].hp&&("fireball"==
actionlist[f].name&&.1<json.glads[b].buffs.burn.timeleft&&(g=game.add.sprite(sprite[b].x,sprite[b].y,"explosion"),g.anchor.setTo(.5,.5),g.alpha=.5,g.width=5*arenaRate,g.height=3*arenaRate,g.animations.add("explode",null,15,!0),g.animations.play("explode",null,!1,!0),game.add.audio("explosion",sfxVolume).play()),gladArray[b].hp=l);if(0>=l)gladArray[b].alive&&(sprite[b].animations.play("die"),"male"==gender[newindex[b]]?game.add.audio("death_male",sfxVolume).play():game.add.audio("death_female",sfxVolume).play()),
gladArray[b].alive=!1;else if(gladArray[b].alive=!0,l=actionlist[f].animation+"-"+getActionDirection(k),"movement"==actionlist[f].name)sprite[b].animations.play(l);else if("charge"==actionlist[f].name)gladArray[b].charge||(sprite[b].animations.stop(),sprite[b].animations.play(l,50,!0),gladArray[b].charge=!0,"male"==gender[newindex[b]]?game.add.audio("charge_male",sfxVolume).play():game.add.audio("charge_female",sfxVolume).play());else if(actionlist[f]&&"none"!=actionlist[f].animation&&gladArray[b].time!=
json.simtime){g=animationlist[actionlist[f].animation].frames;h+=.1;if("ranged"==actionlist[f].name||"melee"==actionlist[f].name)h*=2;h=Math.max(10,g/h);sprite[b].animations.stop();sprite[b].animations.play(l,h);gladArray[b].time=json.simtime;"teleport"==actionlist[f].name&&0==gladArray[b].fade&&(gladArray[b].fade=1,gladArray[b].x=sprite[b].x,gladArray[b].y=sprite[b].y,game.add.audio("teleport",sfxVolume).play());"assassinate"==actionlist[f].name&&(gladArray[b].assassinate=!0);"block"==actionlist[f].name&&
(gladArray[b].block=!1);"ranged"==actionlist[f].name&&game.add.audio("ranged",sfxVolume).play();"melee"==actionlist[f].name&&game.add.audio("melee",sfxVolume).play()}gladArray[b].invisible=.1<json.glads[b].buffs.invisible.timeleft?!0:!1;gladArray[b].invisible?(1<=sprite[b].alpha&&game.add.audio("ambush",sfxVolume).play(),.3<sprite[b].alpha&&(sprite[b].alpha-=.05)):1>sprite[b].alpha&&(sprite[b].alpha+=.05);1!=gladArray[b].fade||gladArray[b].x==sprite[b].x&&gladArray[b].y==sprite[b].y?2==gladArray[b].fade&&
(sprite[b].alpha+=.05,1<=sprite[b].alpha&&(sprite[b].alpha=1,gladArray[b].fade=0)):(clones.push(game.add.sprite(gladArray[b].x,gladArray[b].y,sprite[b].key,sprite[b].frame)),clones[clones.length-1].anchor.setTo(.5,.5),clones[clones.length-1].alpha=1,sprite[b].alpha=0,gladArray[b].fade=2);for(m in clones)clones[m].alpha-=.05,0>=clones[m].alpha&&(clones[m].destroy(),clones.splice(m,1));!gladArray[b].stun&&.1<json.glads[b].buffs.stun.timeleft&&gladArray[b].alive?(gladArray[b].stun=game.add.sprite(sprite[b].x,
sprite[b].y,"stun"),gladArray[b].stun.anchor.setTo(.5,1),gladArray[b].stun.scale.setTo(.6),groupglad.add(gladArray[b].stun),gladArray[b].stun.animations.add("stun",null,15,!0),gladArray[b].stun.animations.play("stun",null,!0,!1),game.add.audio("stun",sfxVolume).play()):gladArray[b].stun&&(.1>=json.glads[b].buffs.stun.timeleft||!gladArray[b].alive)&&(gladArray[b].stun.destroy(),gladArray[b].stun=!1);!gladArray[b].block&&.1<json.glads[b].buffs.resist.timeleft?(gladArray[b].block=!0,h=game.add.sprite(sprite[b].x,
sprite[b].y,"shield"),h.anchor.setTo(.5),h.scale.setTo(.4),groupglad.add(h),h.animations.add("shield",null,15,!1),h.animations.play("shield",null,!1,!0),h.alpha=.5,game.add.audio("block",sfxVolume).play()):gladArray[b].block&&.1>=json.glads[b].buffs.resist.timeleft&&(gladArray[b].block=!1);gladArray[b].charge&&(e!=gladArray[b].xp?(sprite[b].animations.currentAnim.speed=15,l="0"==stab[newindex[b]]?"slash-"+getActionDirection(k):"stab-"+getActionDirection(k),sprite[b].animations.stop(),sprite[b].animations.play(l,
20),game.add.audio("melee",sfxVolume).play()):"charge"!=actionlist[f].name&&(sprite[b].animations.currentAnim.speed=15,gladArray[b].charge=!1));gladArray[b].poison=Math.sqrt(Math.pow(12.5-c,2)+Math.pow(12.5-d,2))>=poison?!0:!1;sprite[b].tint=json.glads[b].buffs.burn&&.1<json.glads[b].buffs.burn.timeleft?16756850:gladArray[b].poison?9895318:gladArray[b].block?16770355:16777215;gladArray[b].xp=e;$("#time").slider("value")!=10*parseFloat(json.simtime)&&$("#time").slider("value",10*parseFloat(json.simtime));
update_ui(json)}debugTimer()}if(json.projectiles&&0<json.projectiles.length)for(d=json.projectiles.length,b=0;b<d;b++){f=json.projectiles[b].id;e=json.projectiles[b].type;var m=findProj(f);if(-1==m){if(0==json.projectiles[b].type)var n=game.add.sprite(0,0,"arrow");else 1==json.projectiles[b].type?(n=game.add.sprite(0,0,"fireball"),n.animations.add("fireball",arrayFill(0,7),15,!0),n.animations.play("fireball"),game.add.audio("fireball",sfxVolume).play()):2==json.projectiles[b].type&&(n=game.add.sprite(0,
0,"arrow"),n.tint=65280);gladArray[json.projectiles[b].owner]&&gladArray[json.projectiles[b].owner].assassinate&&(gladArray[json.projectiles[b].owner].assassinate=!1,n=game.add.sprite(0,0,"arrow"),n.tint=16711680,game.add.audio("assassinate",sfxVolume).play());n.anchor.setTo(.5,.5);m=sproj.length;sproj.push({sprite:n,active:!0,id:f,type:e})}sproj[m].sprite.x=arenaX1+parseFloat(json.projectiles[b].x)*arenaRate;sproj[m].sprite.y=arenaY1+parseFloat(json.projectiles[b].y)*arenaRate;sproj[m].sprite.angle=
parseFloat(json.projectiles[b].head)+90;sproj[m].active=!0}for(c in sproj)!1===sproj[c].active?(1==sproj[c].type?(g=game.add.sprite(sproj[c].sprite.x,sproj[c].sprite.y,"explosion"),g.anchor.setTo(.5,.5),g.alpha=.5,g.width=5*arenaRate,g.height=3*arenaRate,g.animations.add("explode",null,15,!0),g.animations.play("explode",null,!1,!0),game.add.audio("explosion",sfxVolume).play()):game.add.audio("arrow_hit",sfxVolume).play(),sproj[c].sprite.destroy(),sproj.splice(c,1)):sproj[c].active=!1;groupglad.sort("y",
Phaser.Group.SORT_ASCENDING);for(b=0;b<nglad;b++)gladArray[b].alive||groupglad.sendToBack(sprite[b]);groupglad.sendToBack(layers[0]);groupglad.bringToTop(groupgas);groupglad.bringToTop(layers[1]);groupglad.bringToTop(groupnpc[0]);groupglad.bringToTop(layers[2]);groupglad.bringToTop(groupnpc[1]);groupglad.bringToTop(layers[3]);game.input.mouse.drag&&(game.camera.target&&($(".ui-glad").removeClass("follow"),game.camera.unfollow()),game.camera.view.y-=game.input.speed.y,game.camera.view.x-=game.input.speed.x,
$(".baloon").remove());(game.input.keyboard.isDown(Phaser.Keyboard.NUMPAD_ADD)||game.input.keyboard.isDown(Phaser.Keyboard.EQUALS))&&zoomWheel({deltaY:-1});(game.input.keyboard.isDown(Phaser.Keyboard.NUMPAD_SUBTRACT)||game.input.keyboard.isDown(Phaser.Keyboard.UNDERSCORE))&&zoomWheel({deltaY:1});game.input.keyboard.isDown(Phaser.Keyboard.LEFT)&&(game.camera.view.x-=10);game.input.keyboard.isDown(Phaser.Keyboard.RIGHT)&&(game.camera.view.x+=10);game.input.keyboard.isDown(Phaser.Keyboard.UP)&&(game.camera.view.y-=
10);game.input.keyboard.isDown(Phaser.Keyboard.DOWN)&&(game.camera.view.y+=10)}function render(){}function findProj(b){for(i in sproj)if(sproj[i].id==b)return i;return-1}function arrayFill(b,d){for(a=[];b<=d;b++)a.push(b);return a}function getActionDirection(b){return 45<=b&&135>=b?"right":135<b&&225>b?"down":225<=b&&315>=b?"left":"up"}
function createAnimation(b,d){var e=["-up","-left","-down","-right"];if("melee"==d){var f="0"==stab[newindex[b]]?"slash":"stab";animationlist.melee=animationlist[f]}else f=d;for(var c=0;4>c;c++){var g=13*(animationlist[f].start+c);sprite[b].animations.add(d+e[c],arrayFill(g,g+animationlist[f].frames-1),15,!1)}}
function update_ui(b){var d=b.glads.length,e={};for(i=0;i<d;e={$jscomp$loop$prop$j$15:e.$jscomp$loop$prop$j$15},i++){var f=b.glads[i].name,c=b.glads[i].STR,g=b.glads[i].AGI,k=b.glads[i].INT,l=parseInt(b.glads[i].hp),h=parseInt(b.glads[i].maxhp),m=parseInt(b.glads[i].ap),n=parseInt(b.glads[i].maxap),p=parseInt(b.glads[i].lvl),q=parseInt(b.glads[i].xp),r=parseFloat(b.glads[i].buffs.burn.timeleft),t=parseFloat(b.glads[i].buffs.resist.timeleft),u=parseFloat(b.glads[i].buffs.stun.timeleft),v=parseFloat(b.glads[i].buffs.invisible.timeleft),
w=parseFloat(b.glads[i].buffs.movement.timeleft);if(gladArray[i])var x=gladArray[i].poison;""==$(".glad-name span").eq(i).html()&&($(".glad-name span").eq(i).html(f),$(".glad-portrait").eq(i).append(getSpriteThumb(hashes[newindex[i]],"walk","down")));$(".glad-str span").eq(i).html()!==c&&$(".glad-str span").eq(i).html(c);$(".glad-agi span").eq(i).html()!==g&&$(".glad-agi span").eq(i).html(g);$(".glad-int span").eq(i).html()!==k&&$(".glad-int span").eq(i).html(k);$(".lvl-value span").eq(i).html()!=
p&&($(".lvl-value span").eq(i).html(p),$(".lvl-value").eq(i).addClass("up"),e.$jscomp$loop$prop$j$15=i,setTimeout(function(b){return function(){$(".lvl-value").eq(b.$jscomp$loop$prop$j$15).removeClass("up")}}(e),500));$(".xp-bar .filled").eq(i).width()!=q&&$(".xp-bar .filled").eq(i).height(q+"%");$(".hp-bar .filled").eq(i).width()!=l/h*100&&$(".hp-bar .filled").eq(i).width(l/h*100+"%");0>=l?$(".ui-glad").eq(i).addClass("dead"):$(".ui-glad").eq(i).hasClass("dead")&&$(".ui-glad").eq(i).removeClass("dead");
$(".ap-bar .filled").eq(i).width(m/n*100+"%");r?$(".buff-burn").eq(i).addClass("active"):$(".buff-burn").eq(i).hasClass("active")&&$(".buff-burn").eq(i).removeClass("active");t?$(".buff-resist").eq(i).addClass("active"):$(".buff-resist").eq(i).hasClass("active")&&$(".buff-resist").eq(i).removeClass("active");u?$(".buff-stun").eq(i).addClass("active"):$(".buff-stun").eq(i).hasClass("active")&&$(".buff-stun").eq(i).removeClass("active");v?$(".buff-invisible").eq(i).addClass("active"):$(".buff-invisible").eq(i).hasClass("active")&&
$(".buff-invisible").eq(i).removeClass("active");w?$(".buff-speed").eq(i).addClass("active"):$(".buff-speed").eq(i).hasClass("active")&&$(".buff-speed").eq(i).removeClass("active");x?$(".buff-poison").eq(i).addClass("active"):$(".buff-poison").eq(i).hasClass("active")&&$(".buff-poison").eq(i).removeClass("active")}}var showFPS=!1,oldTime=null,avgFPS=0,contFPS=0;
function debugTimer(){if(showFPS){if(oldTime){var b=new Date;avgFPS+=b-oldTime;contFPS++;oldTime=b}else oldTime=new Date;$("#fps").length||($("#canvas-container").append("<div id='fps'></fps>"),b=setInterval(function(){$("#fps").html("FPS: "+parseFloat(1E3/(avgFPS/contFPS)).toFixed(1));contFPS=avgFPS=0},1E3))}else $("#fps").length&&($("#fps").remove(),clearInterval(b))}
$(window).keydown(function(b){b.keyCode==Phaser.Keyboard.S&&$("#sound").click();b.keyCode==Phaser.Keyboard.F&&(showFPS=(showFPS+1)%2,$.post("back_play.php",{action:"SET_PREF",show_fps:1==showFPS}));b.keyCode==Phaser.Keyboard.B&&(showbars=(showbars+1)%2,$.post("back_play.php",{action:"SET_PREF",show_bars:1==showbars}));if(b.keyCode==Phaser.Keyboard.M){if("flex"==$("#ui-container").css("display")){$("#ui-container").fadeOut();var d=!1}else $("#ui-container").fadeIn(),d=!0;$.post("back_play.php",{action:"SET_PREF",
show_frames:d})}b.keyCode==Phaser.Keyboard.SPACEBAR&&$("#pause").click();b.keyCode==Phaser.Keyboard.A&&$("#back-step").click();b.keyCode==Phaser.Keyboard.D&&$("#fowd-step").click();b.keyCode>=Phaser.Keyboard.ONE&&b.keyCode<=Phaser.Keyboard.FIVE&&(b=b.keyCode-Phaser.Keyboard.ONE,$(".ui-glad").eq(b).click())});
function getGladPositionOnCanvas(b){var d=game.camera.scale.y*tileD,e=game.camera.scale.x*tileD;e=arenaX1/tileD*e+e*parseFloat(json.glads[b].x);b=arenaY1/tileD*d+d*parseFloat(json.glads[b].y);d=$("#canvas-div canvas").position().top-game.camera.view.y;var f=$("#canvas-div canvas").position().left-game.camera.view.x;return{x:e+f,y:b+d}}
function showMessageBaloon(b){var d=json.glads[b].message;if(""!=d&&0<json.glads[b].hp){var e=getGladPositionOnCanvas(b);$(".baloon.glad-"+b).length?$(".baloon.glad-"+b).html(d):$("#canvas-div").append("<div class='baloon glad-"+b+"'>"+d+"</div>");b=$(".baloon.glad-"+b);d=e.x+15*game.camera.scale.x;e=e.y-15*game.camera.scale.y-b.outerHeight();b.css({top:e,left:d});200>b.width()&&50<=b.height()?(b.css({left:d-230}),b.addClass("left")):b.hasClass("left")&&b.removeClass("left")}else $(".baloon.glad-"+
b).fadeOut(function(){$(this).remove()})}var showbars=!0;
function showHpApBars(b){gladArray[b].bars&&gladArray[b].bars.clear();if(showbars&&0<json.glads[b].hp){var d=arenaX1+json.glads[b].x*arenaRate,e=arenaY1+json.glads[b].y*arenaRate,f=parseFloat(json.glads[b].hp),c=parseFloat(json.glads[b].maxhp),g=parseFloat(json.glads[b].ap),k=parseFloat(json.glads[b].maxap);gladArray[b].bars.draw(bar.back,d+-15,e+-35,30,9);gladArray[b].bars.draw(bar.hp,d+-15,e+-35,f/c*30,5);gladArray[b].bars.draw(bar.ap,d+-15,e+-30,g/k*30,4)}}
function zoomWheel(b){var d=1-b.deltaY/Math.abs(b.deltaY)*.05,e=screenW*game.camera.scale.x*d,f=screenH*game.camera.scale.y*d;b=(game.input.mouse.input.x+game.camera.x)/game.camera.scale.x;var c=(game.input.mouse.input.y+game.camera.y)/game.camera.scale.y;var g=$(window).width()>$(window).height()?f<=$(window).height()?"height":"none":e<=$(window).width()?"width":"none";"width"==g?(e=$(window).width(),f=$(window).width()*screenH/screenW,game.camera.scale.x=$(window).width()/screenW,game.camera.scale.y=
$(window).width()/screenW):"height"==g?(f=$(window).height(),e=$(window).height()*screenW/screenH,game.camera.scale.x=$(window).height()/screenH,game.camera.scale.y=$(window).height()/screenH):(game.camera.scale.x*=d,game.camera.scale.y*=d);e>$(window).width()&&(e=$(window).width());f>$(window).height()&&(f=$(window).height());game.scale.setGameSize(e,f);game.camera.bounds.width=screenW;game.camera.bounds.height=screenH;"none"==g&&(d=game.input.mouse.input.y,e=game.camera.scale.y,game.camera.x=b*
game.camera.scale.x-game.input.mouse.input.x,game.camera.y=c*e-d);$(".baloon").remove()}function getPosArena(b,d,e){b=(b+.5)*tileD;d=(d+.5)*tileD;void 0!==e&&e||(b+=arenaX1,d+=arenaY1);return{x:b,y:d}}
function fillPeople(){var b=Math.floor(2*Math.random());npc={king:{x:20,y:7.3,start:26,heading:"down",gender:"male",color:b,time:5,interval:2*Math.random()+3},queen:{x:21,y:7.3,start:26,heading:"down",gender:"female",color:b,time:5,interval:2*Math.random()+3},counselor1:{x:19,y:6.7,start:4,gender:"male"},counselor2:{x:22,y:6.7,start:4,gender:"male"},royalguard1:{x:16,y:4,start:78,heading:"down",time:.4*Math.random()+.6,interval:6*Math.random()+8},royalguard2:{x:25,y:4,start:78,heading:"down",time:.4*
Math.random()+.6,interval:6*Math.random()+8},archer1:{x:4,y:3,start:234,heading:"down",time:8,interval:2*Math.random()+7},archer2:{x:39,y:1,start:234,heading:"down",time:8,interval:2*Math.random()+7},archer3:{x:21,y:39,start:208,heading:"up",time:8,interval:2*Math.random()+7},commonguard1:{x:2,y:9,start:78,heading:"down",time:.1*Math.random()+.1},commonguard2:{x:39,y:9,start:65,heading:"left",time:.1*Math.random()+.1},commonguard3:{x:2,y:40,start:91,heading:"right",time:.1*Math.random()+.1},commonguard4:{x:39,
y:40,start:52,heading:"up",time:.1*Math.random()+.1}};b=[{name:"male",anims:3,prob:.7},{name:"female",anims:2,prob:.3}];for(var d in npc)npc[d].layer=1,npc[d].skin||(npc[d].skin=skinColor(d)),npc[d].gender||(npc[d].gender=b[weightedRoll([b[0].prob,b[1].prob])].name),npc[d].hair=getHair(npc[d].skin.name,npc[d].gender);arenaSpaces=[{x:2.4,y:10.1,axis:1,capacity:29,fill:.3,heading:"right",layer:1},{x:3.4,y:10.4,axis:1,capacity:29,fill:.4,heading:"right",layer:1},{x:5.4,y:11,axis:1,capacity:29,fill:.5,
heading:"right",layer:1},{x:6.4,y:11.3,axis:1,capacity:28,fill:.6,heading:"right",layer:1},{x:34.6,y:11.3,axis:1,capacity:28,fill:.6,heading:"left",layer:1},{x:35.6,y:11,axis:1,capacity:29,fill:.5,heading:"left",layer:1},{x:37.6,y:11.5,axis:1,capacity:29,fill:.4,heading:"left",layer:1},{x:38.6,y:11.2,axis:1,capacity:29,fill:.3,heading:"left",layer:1},{x:8,y:5,axis:0,capacity:6,fill:.7,heading:"down",layer:1},{x:8.1,y:5.5,axis:0,capacity:7,fill:.8,heading:"down",layer:2},{x:8,y:9,axis:0,capacity:8,
fill:.5,heading:"down",layer:1},{x:8.1,y:9.5,axis:0,capacity:8,fill:.6,heading:"down",layer:2},{x:28,y:5,axis:0,capacity:6,fill:.7,heading:"down",layer:1},{x:26.9,y:5.5,axis:0,capacity:7,fill:.8,heading:"down",layer:2},{x:26,y:9,axis:0,capacity:8,fill:.5,heading:"down",layer:1},{x:25.9,y:9.5,axis:0,capacity:8,fill:.6,heading:"down",layer:2},{x:7,y:39.5,axis:0,capacity:10,fill:.6,heading:"up",layer:1},{x:5,y:40.5,axis:0,capacity:12,fill:.4,heading:"up",layer:2},{x:25,y:39.5,axis:0,capacity:10,fill:.6,
heading:"up",layer:1},{x:25,y:40.5,axis:0,capacity:12,fill:.4,heading:"up",layer:2}];d={up:[0,8,16],left:[2,10,18],down:[4,12,20],right:[6,14,22]};var e=0,f;for(f in arenaSpaces)for(var c=0;c<arenaSpaces[f].capacity;c++)if(Math.random()<arenaSpaces[f].fill){var g=0,k=0;1==arenaSpaces[f].axis?k=c:g=c;var l=skinColor(),h=b[weightedRoll([b[0].prob,b[1].prob])];npc["people"+e]={x:arenaSpaces[f].x+g,y:arenaSpaces[f].y+k,heading:arenaSpaces[f].heading,time:6*Math.random()+2,layer:arenaSpaces[f].layer,skin:l,
gender:h.name,hair:getHair(l.name,h.name),anims:h.anims,start:d[arenaSpaces[f].heading][parseInt(Math.random()*h.anims)],cheer:!0};e++}}
function clothesColor(){var b=0,d=0,e=0,f=Math.random();.15>f?d=b=e=Math.round(200*Math.random()+50).toString(16):(.5>f?(f=Math.random(),.4>f?b=230:.6>f?d=180:e=200):e=d=b=150,b=Math.round(Math.random()*b).toString(16),d=Math.round(Math.random()*d).toString(16),e=Math.round(Math.random()*e).toString(16));2>b.length&&(b="0"+b);2>d.length&&(d="0"+d);2>e.length&&(e="0"+e);return"0x"+b+d+e}
function arrayFrame(b){var d=[7,7,7,7,8,8,8,8,9,9,9,9,6,6,6,6,13,13,13,13],e,f,c=[],g,k;for(k in b)for(g=e=f=0;b[k]>=f;)if(f+d[e]>b[k]){c.push(g+b[k]-f);break}else g+=13,f+=d[e],e++;return c}
function getHair(b,d){var e=0;var f={light:[.1,.25],black:[0,0],tanned:[.05,.15],dark:[0,.05],darkelf:[.2,.4],red_orc:[.1,.1]};var c=Math.random();c<f[b][0]?(f=90*Math.random()+110,c=55*Math.random()+70,e=25*Math.random()+55):c<f[b][1]+f[b][0]?(f=70*Math.random()+160,c=.8*f):(f=70*Math.random()+30,c=.75*f,e=30*Math.random()+20);f=Math.round(f).toString(16);c=Math.round(c).toString(16);e=Math.round(e).toString(16);2>f.length&&(f="0"+f);2>c.length&&(c="0"+c);2>e.length&&(e="0"+e);e="0x"+f+c+e;b=weightedRoll({male:{light:[.25,
.3,.1,.05,.3,.1],black:[.05,.05,.2,.4,.1,.4],tanned:[.35,.2,.1,.05,.3,.1],dark:[.15,.1,.2,.3,.25,.3],darkelf:[.3,.1,0,0,0,.8],red_orc:[.15,0,.3,.05,.1,.5]},female:{light:[.3,.05,.3,.3,.2,0],black:[.1,.6,.15,.3,.3,.02],tanned:[.3,.2,.3,.3,.2,.01],dark:[.2,.3,.2,.2,.3,.02],darkelf:[.1,0,.1,.4,.3,.2],red_orc:[.1,.05,.1,.2,.3,.2]}}[d][b]);return{color:e,style:{male:"ponytail parted mohawk jewfro bedhead no_hair".split(" "),female:"long jewfro loose longknot pixie no_hair".split(" ")}[d][b]}}
function skinColor(b){var d={light:{chance:.35,tint:"0xfdd5b7"},black:{chance:.1,tint:"0x61382d"},tanned:{chance:.25,tint:"0xfdd082"},dark:{chance:.2,tint:"0xba8454"},darkelf:{chance:.05,tint:"0xaeb3ca"},red_orc:{chance:.05,tint:"0x568b33"}};if("king"==b||"queen"==b)d.darkelf.chance=0,d.red_orc.chance=0,d.light.chance=.4,d.tanned.chance=.3;b=Math.random();for(var e in d){if(b<d[e].chance)return{name:e,tint:d[e].tint};b-=d[e].chance}}
function weightedRoll(b){var d=0,e;for(e in b)d+=b[e];for(var f in b)b[f]/=d;d=Math.random();for(var c in b){if(d<b[c])return c;d-=b[c]}return-1};
