var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(c.call(b,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,c,b,e){if(c){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in b||(b[d]={});b=b[d]}a=a[a.length-1];e=b[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");var ajaxcall;
function runSimulation(a){ajaxcall&&ajaxcall.abort();var c=a.glads,b=a.savecode,e=a.single,d=a.ranked,f=a.duel;a=a.tournament;e||(e=!1);b||(b=!1);d||(d=!1);f||(f=!1);a||(a=!1);var g=$.Deferred();ajaxcall=$.post("back_simulation.php",{glads:JSON.stringify(c),savecode:b,single:e,ranked:d,duel:f,tournament:a}).done(function(a){try{JSON.parse(a)}catch(h){var b=h}if(b)return showTerminal("ERRO EM TEMPO DE EXECU\u00c7\u00c3O","Algum de seus gladiadores ocasionou um erro na simula\u00e7\u00e3o enquanto ela estava sendo executada.\nVerifique seus c\u00f3digos-fonte e tente novamente."),
console.log("ERROR: "+b),console.log("JSON: "+a),g.resolve("ERROR");if(JSON.parse(a)){a=JSON.parse(a);var e=a.simulation;b=a.error;a=a.output;if(""!=b){if("INVALID_ATTR"==b)showTerminal("ERRO DE VALIDA\u00c7\u00c3O","Os atributos de um dos gladiadores n\u00e3o s\u00e3o v\u00e1lidos ou sua pontua\u00e7\u00e3o n\u00e3o corresponde \u00e0s regras da gladCode");else{b=b.split("/usercode/").join("");for(var d in c)c[d].name?b=b.split("code"+d+".c").join("<span>"+c[d].name+"</span>"):(a=/setName\("([\w\W]*?)"\);/,
a=c[d].match(a)[1],b=b.split("code"+d+".c").join("<span>"+a+"</span>"));a=/\\n/g;b=b.replace(a,"\n");showTerminal("ERRO DE COMPILA\u00c7\u00c3O",b)}return g.resolve("ERROR")}if(0<e.length){if("CLIENT TIMEOUT"==a)return showTerminal("ERRO NA SIMULA\u00c7\u00c3O","A gladCode est\u00e1 tendo problemas entre a conex\u00e3o do simulador e os gladiadores. Por favor, reporte este problema para <a href='mailto:contato@gladcode.tk'><span>contato@gladcode.tk</span></a>"),g.resolve("ERROR");if(-1!=a.indexOf("timed out"))return d=
a.split("Gladiator ")[1].split(" timed out")[0],showTerminal("GLADIADOR EM LOOP","O c\u00f3digo do gladiador <span>"+d+"</span> est\u00e1 em uma repeti\u00e7\u00e3o da qual n\u00e3o consegue sair.\nEle foi desativado para n\u00e3o comprometer a simula\u00e7\u00e3o.\n\nRevise o c\u00f3digo-fonte e tente novamente."),g.resolve("ERROR");""!=a&&console.log("MENSAGEM: "+a);return g.resolve(e)}}else return g.resolve(!1)});return g.promise()}
var progressButton=function(a,c){this.oldhtml=a.html();a.html("<div id='bar'></div><div id='oldcontent'></div>");a.find("#bar").css({"background-color":"#00638d",width:"0px",height:"100%","border-radius":"3px"});a.prop("disabled","true");a.css("padding","0");a.append("<div id='oldcontent'></div>");$("#oldcontent").css({display:"flex","align-items":"center","justify-content":"center",width:"100%",height:"100%","margin-top":-1*a.outerHeight()});this.bsize=0;this.obj=a;var b=this,e=0,d=0;this.progint=
setInterval(function(){a.find("#bar").width();var f=a.width()/2E3;b.bsize+=f;a.find("#bar").width(b.bsize.toFixed(0));a.find("#oldcontent").html(c[e]);d++;0==d%200&&(e=(e+1)%c.length);a.find("#bar").width()>=a.width()&&(b.kill(),showTerminal("ERRO DE CONEX\u00c3O","Falha ao obter resposta do servidor dentro do tempo limite."),ajaxcall&&ajaxcall.abort())},10)};progressButton.prototype.kill=function(){clearInterval(this.progint);this.obj.html(this.oldhtml);this.obj.removeProp("disabled");$("#oldcontent").remove()};
progressButton.prototype.set=function(a,c){this.obj.html("<div id='bar'></div>");this.obj.find("#bar").css({"background-color":"#00638d",width:"0px",height:"100%","border-radius":"3px"});this.obj.prop("disabled","true");this.obj.css("padding","0");this.obj.append("<div id='oldcontent'>"+a+"</div>");$("#oldcontent").css({margin:this.obj.css("margin"),display:"flex","align-items":"center","justify-content":"center",position:"absolute",top:this.obj.position().top,left:this.obj.position().left,width:this.obj.width(),
height:this.obj.height()});this.bsize=this.obj.width()/100*c;this.obj.find("#bar").width(this.bsize.toFixed(0))};progressButton.prototype.isActive=function(){return 0<this.obj.find("#oldcontent").length?!0:!1};function decodeHTML(a){var c={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#x27;","`":"&#x60;"},b;for(b in c)a=a.replace(new RegExp(c[b],"g"),b);return a};
