var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,b,c){a instanceof String&&(a=String(a));for(var d=a.length,e=0;e<d;e++){var f=a[e];if(b.call(c,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,b,c){a!=Array.prototype&&a!=Object.prototype&&(a[b]=c.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,b,c,d){if(b){c=$jscomp.global;a=a.split(".");for(d=0;d<a.length-1;d++){var e=a[d];e in c||(c[e]={});c=c[e]}a=a[a.length-1];d=c[a];b=b(d);b!=d&&null!=b&&$jscomp.defineProperty(c,a,{configurable:!0,writable:!0,value:b})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,c){return $jscomp.findInternal(this,a,c).v}},"es6","es3");var block_change=!1,meta_files=[];
function switch_tab(a){block_change=!0;var b=$(".tab").index($(".tab.active").eq(0));meta_files[b].code=editor.getValue();meta_files[b].input=input;$(".tab.active").removeClass("active");a.addClass("active");a=$(".tab").index($(".tab.active").eq(0));editor.setValue(meta_files[a].code);input=meta_files[a].input;editor.clearSelection();editor.focus();""==meta_files[a].path?($("#button-csync").hide(),$("#button-csave").show()):($("#button-csync").show(),$("#button-csave").hide());resize_tabs();block_change=
!1}function close_tab(a){block_change=!0;a=$(".tab").index(a);meta_files.splice(a,1);$(".tab").eq(a).remove();0<a&&a--;0==$(".tab.active").length&&($(".tab").eq(a).addClass("active"),editor.setValue(meta_files[a].code),input=meta_files[a].input,""==meta_files[a].path?($("#button-csync").hide(),$("#button-csave").show()):($("#button-csync").show(),$("#button-csave").hide()));resize_tabs();editor.clearSelection();editor.focus();block_change=!1}
function new_tab(){if(1==arguments.length){var a="sem nome";var b=arguments[0]}else 2==arguments.length&&(a=arguments[0],b=arguments[1]);block_change=!0;meta_files.push(new file);var c=0==$(".tab").length?0:$(".tab").index($(".tab.active").eq(0));meta_files[c].code=editor.getValue();meta_files[c].input=input;$(".tab.active").removeClass("active");$("#tab-bar").append("<div class='tab active'><span class='name'>"+a+"</span><img src='icon/close_x.png'></div>");editor.setValue(b);input="";editor.clearSelection();
editor.focus();editor.gotoLine(1,0,!0);$("#button-csync").hide();$("#button-csave").show();block_change=!1;$(".tab").off();$(".tab").click(function(){switch_tab($(this))});resize_tabs();$(".tab img").off();$(".tab img").click(function(a){var c=$(this).parent().find(".name").html();a.stopPropagation();var b=$(this).parent();0!=b.find(".changed").length?(a="<div id='fog'><div class='window message'><div class='row title'>Deseja fechar o arquivo \""+c+"\"? Voc\u00ea ir\u00e1 perder todas altera\u00e7\u00f5es realizadas</div><div class='row buttons'><img class='green' src='icon/check.png'><img class='red' src='icon/close_x.png'></div></div></div>",
$("body").append(a),$("#fog").click(function(){$(this).remove();$(window).width()>window_size_threshold&&editor.focus()}),$(".window.message").click(function(a){a.stopPropagation()}),$(".window.message img.red").click(function(){$("#fog").click()}),$(".window.message img.green").click(function(){$("#fog").click();1==$(".tab").length&&new_tab("");close_tab(b)})):(1==$(".tab").length&&new_tab(""),close_tab(b))})}function file(){this.input=this.path=this.code="";this.changed=!1;this.local=!0}
function resize_tabs(){$(".tab").removeAttr("style");if($(".tab").last().position().left+$(".tab").last().width()>$("#tab-bar").width()){var a=$("#tab-bar").width(),b=$(".tab").length,c=0;$(window).width()<window_size_threshold&&(c=25);$(".tab").css("max-width",(a-c)/b)}};
