var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.arrayIteratorImpl=function(a){var c=0;return function(){return c<a.length?{done:!1,value:a[c++]}:{done:!0}}};$jscomp.arrayIterator=function(a){return{next:$jscomp.arrayIteratorImpl(a)}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,c,b){a!=Array.prototype&&a!=Object.prototype&&(a[c]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);$jscomp.SYMBOL_PREFIX="jscomp_symbol_";$jscomp.initSymbol=function(){$jscomp.initSymbol=function(){};$jscomp.global.Symbol||($jscomp.global.Symbol=$jscomp.Symbol)};
$jscomp.SymbolClass=function(a,c){this.$jscomp$symbol$id_=a;$jscomp.defineProperty(this,"description",{configurable:!0,writable:!0,value:c})};$jscomp.SymbolClass.prototype.toString=function(){return this.$jscomp$symbol$id_};$jscomp.Symbol=function(){function a(b){if(this instanceof a)throw new TypeError("Symbol is not a constructor");return new $jscomp.SymbolClass($jscomp.SYMBOL_PREFIX+(b||"")+"_"+c++,b)}var c=0;return a}();
$jscomp.initSymbolIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.iterator;a||(a=$jscomp.global.Symbol.iterator=$jscomp.global.Symbol("Symbol.iterator"));"function"!=typeof Array.prototype[a]&&$jscomp.defineProperty(Array.prototype,a,{configurable:!0,writable:!0,value:function(){return $jscomp.iteratorPrototype($jscomp.arrayIteratorImpl(this))}});$jscomp.initSymbolIterator=function(){}};
$jscomp.initSymbolAsyncIterator=function(){$jscomp.initSymbol();var a=$jscomp.global.Symbol.asyncIterator;a||(a=$jscomp.global.Symbol.asyncIterator=$jscomp.global.Symbol("Symbol.asyncIterator"));$jscomp.initSymbolAsyncIterator=function(){}};$jscomp.iteratorPrototype=function(a){$jscomp.initSymbolIterator();a={next:a};a[$jscomp.global.Symbol.iterator]=function(){return this};return a};
$jscomp.iteratorFromArray=function(a,c){$jscomp.initSymbolIterator();a instanceof String&&(a+="");var b=0,e={next:function(){if(b<a.length){var d=b++;return{value:c(d,a[d]),done:!1}}e.next=function(){return{done:!0,value:void 0}};return e.next()}};e[Symbol.iterator]=function(){return e};return e};
$jscomp.polyfill=function(a,c,b,e){if(c){b=$jscomp.global;a=a.split(".");for(e=0;e<a.length-1;e++){var d=a[e];d in b||(b[d]={});b=b[d]}a=a[a.length-1];e=b[a];c=c(e);c!=e&&null!=c&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:c})}};$jscomp.polyfill("Array.prototype.keys",function(a){return a?a:function(){return $jscomp.iteratorFromArray(this,function(a){return a})}},"es6","es3");
$jscomp.findInternal=function(a,c,b){a instanceof String&&(a=String(a));for(var e=a.length,d=0;d<e;d++){var f=a[d];if(c.call(b,f,d,a))return{i:d,v:f}}return{i:-1,v:void 0}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");var tier_select=0,tiers=[],rounds=[],teamTimeGlad,winners=[],exportjson,tournHash;
$(document).ready(function(){0<$("#get-tour").html().length&&(tournHash=$("#get-tour").html(),getTournment());$("#get-tour").remove();$("#t-start").click(function(){var a=Math.ceil(Object.keys(teams).length/5);for(d=0;d<a;d++)tiers[d]={},tiers[d].bnum=d+1,tiers[d].teams={};var c=0;do{var b=Math.ceil(Object.keys(teams).length),e=getRandom(0,b-1),d=0;for(t in teams){if(d==e){tiers[c].teams[t]={};tiers[c].teams[t].code=teams[t];tiers[c].teams[t].dead={};for(var f in tiers[c].teams[t].code)tiers[c].teams[t].dead[f]=
!1;delete teams[t];c=(c+1)%a;break}d++}}while(1<b);rounds.push(tiers);tournmentStatus();saveTournment(1)});$(window).keydown(function(a){a.ctrlKey&&a.altKey&&74==a.keyCode&&(teams={"Unbiased Thugs":code,"Ceaseless Power":code,"Mute Noobs":code,"Funny Antagonists":code,"Halting Slayers":code,"Clever Superpower":code,"Tranquil Tyranny":code,"Fearless Hooligans":code,"Elite Warriors":code,"Dear Strategy":code,"Godly Squad":code,"Learned Exterminators":code,"Five Mafia":code},$("#t-start").removeProp("disabled"),
console.log("JUMP START"));a.ctrlKey&&a.altKey&&68==a.keyCode&&$.post("back_log.php",{action:"GET",loghash:"5e0d6737353d47af3abe76fa52280d86"}).done(function(a){orderDeaths(JSON.parse(a));console.log("BATTLE TEST")})})});
function saveTournment(a){var c=tiers[0].bnum,b=tiers[tiers.length-1].bnum;a>b&&(b=b-c+a,c=a);a={bnum:a,bstart:c,bend:b};tournHash?$.post("back_tournment.php",{round:JSON.stringify(teamTimeGlad),bnum:JSON.stringify(a),winners:JSON.stringify(winners),hash:tournHash,action:"save"}).done(function(a){}):$.post("back_tournment.php",{round:JSON.stringify(teamTimeGlad),bnum:JSON.stringify(a),winners:JSON.stringify(winners),action:"save"}).done(function(a){tournHash=a})}
function getTournment(){$.post("back_tournment.php",{hash:tournHash,action:"get"}).done(function(a){a=JSON.parse(a);var c=JSON.parse(a.bnum).bnum,b=JSON.parse(a.bnum).bstart,e=JSON.parse(a.bnum).bend;teamTimeGlad=JSON.parse(a.round);winners=JSON.parse(a.winners);tier_select=(c-b)%(e-b+1);tiers=Array({bnum:b-1});a=remakeTiers();1<a?tournmentStatus():tournmentEnd(a)})}
function tournmentStatus(){function a(b,c){$("#tiers-container .tier").eq(b).find(".team").eq(c).length?setTimeout(function(){$("#tiers-container .tier").eq(b).find(".team").eq(c).fadeIn(200,function(){b<tiers.length-1?a(b+1,c):c<$("#tiers-container .tier").eq(0).find(".team").length-1?a(0,c+1):$("#b-continue").removeProp("disabled")})},300):$("#b-continue").removeProp("disabled")}if(teamTimeGlad){var c=[];for(var b=0;b<teamTimeGlad.length;b++)c[teamTimeGlad[b].team]=teamTimeGlad[b].time;var e=teamTimeGlad;
e.find=function(a){for(var b in e)if(e[b].team==a)return e[b];return!1}}teamTimeGlad=[];teamTimeGlad.find=function(a){for(var b in teamTimeGlad)if(teamTimeGlad[b].team==a)return teamTimeGlad[b];return!1};$("#code-selection").html("<p id='text-intro'>As equipes foram organizadas nos seguintes grupos</p><div id='tiers-container'></div><div id='button-container'><button id='t-link' class='button' title='Mostra o link para continuar o torneio mais tarde'>LINK</button><button id='b-continue' class='button' title='Continuar as batalhas do torneio' disabled>CONTINUAR</button></div>");
for(b in tiers)for(t in $("#tiers-container").append("<div class='tier'><div class='title'><span>Batalha "+tiers[b].bnum+"</span><div class='icons'><div class='glad'><img src='icon/gladcode_icon.png' title='Gladiadores vivos da equipe'></div><div class='time'><img src='icon/clock-icon.png' title='Tempo que sobreviveu na \u00faltima batalha'></div></div></div></div>"),tiers[b].teams){var d=3;$("#tiers-container .tier").last().append("<div class='team'><div class='icon'><img src='icon/check.png'></div><span>"+
t+"</span><div class='info'><div class='glad'><div class='g-bar'></div><div class='g-bar'></div><div class='g-bar'></div></div><div class='time'><span></span> s</div></div></div>");$("#tiers-container .tier .team").last().hide();var f={team:t,time:null,glads:{}};for(g in tiers[b].teams[t].code)f.glads[tiers[b].teams[t].code[g].name]={},f.glads[tiers[b].teams[t].code[g].name].code=tiers[b].teams[t].code[g],tiers[b].teams[t].dead[g]&&(f.glads[tiers[b].teams[t].code[g].name].dead=!0,d--);$("#tiers-container .info .glad").last().addClass(["",
"one","two","three"][d]);c&&null!=c[t]?1E3<=c[t]?$("#tiers-container .info .time").last().html("<img class='winner' src='icon/winner-icon.png'>"):$("#tiers-container .info .time span").last().html(c[t].toFixed(1)):$("#tiers-container .info .time").last().html("-");teamTimeGlad.push(f)}if(0!=tier_select%tiers.length&&e)for(b in teamTimeGlad)c=teamTimeGlad[b].team,null==teamTimeGlad[b].time&&null!=e.find(c).time&&(teamTimeGlad[b]=e.find(c));a(0,0);if(0<winners.length)for($("#tiers-container").append("<div class='tier defeated'><div class='title'><span>Equipes derrotadas</span><div class='icons'><img src='icon/gladcode_icon.png' title='Gladiadores vivos da equipe'></div></div></div>"),
b=winners.length-1;0<=b;b--)$("#tiers-container .tier").last().append("<div class='team'><div class='icon'><img src='icon/close_x.png'></div><span>"+winners[b]+"</span><div class='info'><div class='glad'><div class='g-bar'></div><div class='g-bar'></div><div class='g-bar'></div></div></div></div>");$("#b-continue").click(function(){chooseGlads()});$("#t-link").click(function(){$("body").append("<div id='fog'><div id='url'><span id='site'>https://gladcode.tk/tournment.php?t=</span><span id='hash'>"+
tournHash+"</span></div></div>");$("#url").click(function(){copyToClipboard("https://gladcode.tk/tournment.php?t="+$("#url #hash").html());$("#url").html("Link copiado");$("#url").addClass("clicked");setTimeout(function(){$("#fog").remove()},1E3)})})}
function chooseGlads(){function a(){$("#team-container #name span").html(b[c]);$("#team-container #glad-selection").html("");for(id in tiers[tier_select].teams[b[c]].code){var a=tiers[tier_select].teams[b[c]].code[id],d=tiers[tier_select].teams[b[c]].dead[id];$("#team-container #glad-selection").append("<div class='glad-box'><div class='canvas'></div><div class='name'></div></div>");$("#team-container #glad-selection .name").last().html(a.name);$("#team-container #glad-selection .glad-box").last().data("id",
id);d?($("#team-container #glad-selection .glad-box").last().addClass("dead"),appendCanvas($("#team-container #glad-selection .canvas").last(),a.code,"dead")):appendCanvas($("#team-container #glad-selection .canvas").last(),a.code)}$("#glad-selection .glad-box").not(".dead").click(function(){$("#glad-selection .glad-box").removeClass("selected");$(this).addClass("selected");0<$("#glad-selection .glad-box.selected").length&&$("#b-select").removeProp("disabled")})}var c=0;$("#code-selection").html("<div id='pre-battle-container'><div id='title'>Batalha "+
tiers[tier_select].bnum+"</div><div id='glad-showcase'></div><div id='team-container'><div id='name'><span></span>, selecione um gladiador para fazer parte da batalha</div><div id='glad-selection'></div></div></div><div id='button-container'><button id='b-select' class='button' title='Selecionar o gladiador escolhido para a equipe' disabled>SELECIONAR</button></div>");for(t in tiers[tier_select].teams)$("#glad-showcase").append("<div class='glad-box empty'><div class='canvas'></div><div class='name'>XXXXXXX</div></div>");
var b=[],e=[];for(t in tiers[tier_select].teams)b.push(t);a();var d=!1;$("#b-select").click(function(){if(d)istep&&(clearInterval(istep),istep=null),startBattle(e);else{var f=$("#glad-showcase .glad-box.empty").first();f.removeClass("empty");var h=$("#glad-selection .glad-box.selected").data("id");h=tiers[tier_select].teams[b[c]].code[h];appendCanvas(f.find(".canvas"),h.code);f.find(".name").html(h.name);e.push({team:b[c],file:h.file,code:h.code});c++;c<b.length?($("#b-select").prop("disabled",!0),
a()):($(this).html("INICIAR BATALHA"),$("#team-container").remove(),d=!0)}})}
function remakeTiers(){var a=!0,c=0,b;for(b in teamTimeGlad){var e=0;for(d in teamTimeGlad[b].glads)teamTimeGlad[b].glads[d].dead||e++;0<e?c++:teamTimeGlad[b].inactive=!0;null==teamTimeGlad[b].time&&"find"!=b&&(a=!1)}a?setWinners():c=teamTimeGlad.length;var d=tiers[tiers.length-1].bnum;tiers=[];e=Math.ceil(c/5);for(b=0;b<e;b++)tiers[b]=[],tiers[b].bnum=d+b+1,tiers[b].teams=[];var f=c,h=e,l=0;for(d=0;d<e;d++){var p=Math.ceil(f/h);for(b=0;b<p;){var m=c-f,n=teamTimeGlad[m+b+l].team;if(teamTimeGlad[m+
b+l].inactive&&a)l++;else{tiers[d].teams[n]=[];tiers[d].teams[n].code=[];tiers[d].teams[n].dead=[];for(k in teamTimeGlad[m+b+l].glads){var q=teamTimeGlad[m+b+l].glads[k].code.file.upload.uuid;tiers[d].teams[n].code[q]=teamTimeGlad[m+b+l].glads[k].code;tiers[d].teams[n].dead[q]=teamTimeGlad[m+b+l].glads[k].dead}b++}}f-=p;h--}rounds.push(tiers);return c}function getRandom(a,c){return Math.floor(Math.random()*(c-a+1))+a}
function startBattle(a,c){var b=["Executando simula\u00e7\u00e3o...","Aguardando resposta do servidor"];c&&(b=["Erro dos dados recebidos","Realizando nova tentativa..."]);var e=new progressButton($("#b-select"),b),d=[],f=0,h;for(h in a)getGladFromCode(a[h].code,a[h].team).then(function(a){d.push(a);f++});var l=setInterval(function(){f==Object.keys(a).length&&(clearInterval(l),runSimulation(d).then(function(a){"ERROR"==a?e.kill():$.post("back_log.php",{action:"SAVE",log:JSON.stringify(a),single:!0}).done(function(b){showMessage("Batalha conclu\u00edda. Clique para visualizar").then(function(){window.location.href=
"https://gladcode.tk/playback.php?log="+b+"&t="+tournHash;$("#b-continue").click()});e.kill();startloop=!0;orderDeaths(a);tier_select++})}))},10)}
function orderDeaths(a){var c=[];for(d in a)$.extend(!0,json,a[d]),c.push(JSON.parse(JSON.stringify(json)));json=c;for(var b in json[0].glads){c=json[0].glads[b].user.replace(/#/g," ");var e=json[0].glads[b].name.replace(/#/g," ");teamTimeGlad.find(c).glads[e].dead=!0}for(d in json)for(b in json[d].glads)c=json[d].glads[b].user.replace(/#/g," "),0<json[d].glads[b].hp&&(teamTimeGlad.find(c).time=json[d].simtime);var d=json.length-1;a="tie";e=0;for(b in json[d].glads){var f=json[d].simtime;c=json[d].glads[b].user.replace(/#/g,
" ");c=teamTimeGlad.find(c).time;f==c&&0<json[d].glads[b].hp&&(!a||e<json[d].glads[b].hp?(a=b,e=json[d].glads[b].hp):a="tie")}if("tie"!=a)for(b in json[d].glads)c=json[d].glads[b].user.replace(/#/g," "),b==a&&(teamTimeGlad.find(c).time+=1E3,e=json[d].glads[b].name.replace(/#/g," "),delete teamTimeGlad.find(c).glads[e].dead);0==(tier_select+1)%tiers.length&&teamTimeGlad.sort(function(a,b){return null==a.time?-1:null==b.time?1:a.time>b.time?-1:1});saveTournment(tiers[tier_select].bnum+1)}
function tournmentEnd(a){function c(a){$("#tiers-container .tier .team").eq(a).length&&setTimeout(function(){$("#tiers-container .tier .team").eq(a).fadeIn(1E3,function(){a<$("#tiers-container .tier .team").length-1&&c(a+1)})},1E3)}$("#code-selection").html("<p id='text-intro'>O torneio chegou ao fim e temos os seguintes vencedores</p><div id='tiers-container'><div class='tier'><div class='title'><span>Classifica\u00e7\u00e3o</span></div></div></div>");winners.reverse();for(var b=0;b<winners.length;b++)$("#tiers-container .tier").last().append("<div class='team win'><div class='icon'></div><span>"+
winners[b]+"</span></div>"),$("#tiers-container .tier .team").last().hide(),0==b||1==b&&0==a?($("#tiers-container .tier .team").last().addClass("gold"),$("#tiers-container .tier .team.gold .icon").append("<img src='icon/gold-medal.png'>")):1==b||2==b&&0==a?($("#tiers-container .tier .team").last().addClass("silver"),$("#tiers-container .tier .team.silver .icon").append("<img src='icon/silver-medal.png'>")):2==b||3==b&&0==a?($("#tiers-container .tier .team").last().addClass("bronze"),$("#tiers-container .tier .team.bronze .icon").append("<img src='icon/bronze-medal.png'>")):
($("#tiers-container .tier .team").last().addClass("none"),$("#tiers-container .tier .team.none .icon").last().html(b+1+"\u00ba"));c(0)}function setWinners(){for(var a=0,c,b=teamTimeGlad.length-1;0<=b;b--)teamTimeGlad[b].inactive&&-1==winners.indexOf(teamTimeGlad[b].team)?winners.push(teamTimeGlad[b].team):(a++,c=teamTimeGlad[b].team);1==a&&winners.push(c)};
