var $jscomp=$jscomp||{};$jscomp.scope={};$jscomp.findInternal=function(a,d,b){a instanceof String&&(a=String(a));for(var c=a.length,e=0;e<c;e++){var f=a[e];if(d.call(b,f,e,a))return{i:e,v:f}}return{i:-1,v:void 0}};$jscomp.ASSUME_ES5=!1;$jscomp.ASSUME_NO_NATIVE_MAP=!1;$jscomp.ASSUME_NO_NATIVE_SET=!1;$jscomp.SIMPLE_FROUND_POLYFILL=!1;
$jscomp.defineProperty=$jscomp.ASSUME_ES5||"function"==typeof Object.defineProperties?Object.defineProperty:function(a,d,b){a!=Array.prototype&&a!=Object.prototype&&(a[d]=b.value)};$jscomp.getGlobal=function(a){return"undefined"!=typeof window&&window===a?a:"undefined"!=typeof global&&null!=global?global:a};$jscomp.global=$jscomp.getGlobal(this);
$jscomp.polyfill=function(a,d,b,c){if(d){b=$jscomp.global;a=a.split(".");for(c=0;c<a.length-1;c++){var e=a[c];e in b||(b[e]={});b=b[e]}a=a[a.length-1];c=b[a];d=d(c);d!=c&&null!=d&&$jscomp.defineProperty(b,a,{configurable:!0,writable:!0,value:d})}};$jscomp.polyfill("Array.prototype.find",function(a){return a?a:function(a,b){return $jscomp.findInternal(this,a,b).v}},"es6","es3");var count_refresh=0,hash,round;
$(document).ready(function(){hash=$("#hash").html();round=$("#round").html();$("#hash, #round").remove();$.post("back_tournament_run.php",{action:"GET",hash:hash,round:round}).done(function(a){a=JSON.parse(a);if("REDIRECT"==a.status)window.location.href="tourn/"+hash+"/"+a.round;else if("NOTFOUND"==a.status)window.location.href="index";else if("END"==a.status){$("#content-box").html("<h1>Classifica\u00e7\u00e3o final</h1><h3>O torneio <span id='tourn-name'>"+a.tournament+"</span> chegou ao fim e esta foi a classifica\u00e7\u00e3o obtida pelas equipes</h3><div id='ranking-container'></div><div id='button-container'><button id='back-round' class='button'>RODADA ANTERIOR</button></div>");
for(var d in a.ranking){var b=parseInt(d)+1;$("#content-box #ranking-container").append("<div class='team'><div class='ordinal'>"+b+"\u00ba</div><div class='name'>"+a.ranking[d]+"</div></div>");1==b?$("#content-box #ranking-container .team").last().addClass("gold"):2==b?$("#content-box #ranking-container .team").last().addClass("silver"):3==b&&$("#content-box #ranking-container .team").last().addClass("bronze")}$("#content-box #ranking-container .team.gold .ordinal").html("<img class='icon' src='icon/gold-medal.png'>");
$("#content-box #ranking-container .team.silver .ordinal").html("<img class='icon' src='icon/silver-medal.png'>");$("#content-box #ranking-container .team.bronze .ordinal").html("<img class='icon' src='icon/bronze-medal.png'>");$("#content-box #back-round").click(function(){window.location.href="tourn/"+hash+"/"+a.maxround})}else{var c=function(){setTimeout(function(){var a=msToTime(l-new Date);$("#timeleft .numbers").each(function(b,c){parseInt(a[b])!=parseInt($(c).text())&&($(c).find("span").eq(0).html(a[b].toString()[0]),
$(c).find("span").eq(1).html(a[b].toString()[1]))});1==$("#group-container .team.myteam .icon.green").length?$("#timeleft").addClass("green"):0==parseInt(a[0])&&(10>parseInt(a[1])?$("#timeleft").addClass("red"):$("#timeleft").addClass("yellow"));$("#group-container .team .icon.green").length==$("#group-container .team").length&&$("#timeleft .numbers span").html("0");"00:00:00"!=$("#timeleft #time").text()&&c()},1E3)};$("#content-box").html("<h1>Torneio <span id='tourn-name'>"+a.tournament.name+"</span></h1><h3 id='tourn-desc'>"+
a.tournament.description+"</h3><div id='group-container'></div>");d=!1;var e=0,f={};for(b in a.teams){var g=a.teams[b].group;a.teams[b].group in f||(f[g]=e,$("#content-box #group-container").append("<div class='group'><div class='head'><div class='title'>Grupo "+parseInt(e+1)+" - <span>Rodada "+a.tournament.round+"</span></div><div class='icons'><div class='glad' title='Quantos gladiadores da equipe ainda restam'><img src='icon/gladcode_icon.png'></div><div class='time' title='Quantos segundos o gladiador da equipe sobreviveu'><img src='icon/clock-icon.png'></div></div></div><div class='teams-container'></div><div class='foot'><button class='button' disabled>Aguardando <span class='number'></span> mestre<span class='plural'>s</span></button></div></div>"),
$("#content-box #group-container .group").eq(e).data("id",g),e++);var h="";if(1==a.teams[b].myteam){h="myteam";d=!0;var m=a.teams[b].name}$("#content-box #group-container .group .teams-container").eq(f[g]).append("<div class='team "+h+"'><div class='icon'><i class='material-icons'>hourglass_empty</i></div><div class='name'>"+a.teams[b].name+"</div><div class='info'><div class='glad'><div class='g-bar'></div><div class='g-bar'></div><div class='g-bar'></div></div><div class='time'>-</div></div></div>");
$("#content-box #group-container .group").eq(f[g]).find(".team").last().data("id",a.teams[b].id)}$("#content-box").append("<div id='timeleft' title='Tempo m\u00e1ximo restante at\u00e9 o fim da rodada'><div id='time'><div class='numbers'><span>0</span><span>0</span></div>:<div class='numbers'><span>0</span><span>0</span></div>:<div class='numbers'><span>0</span><span>0</span></div></div><div id='text'><span>HRS</span><span>MIN</span><span>SEG</span></div></div><div id='button-container'><button class='arrow' id='back-round' title='Rodada anterior' disabled><i class='material-icons'>navigate_before</i></button><button id='prepare' class='button' disabled>PREPARAR-SE</button><button class='arrow' id='next-round' title='Pr\u00f3xima rodada' disabled><i class='material-icons'>navigate_next</i></button></div>");
refresh_round();var k=a.tournament.round;1<k&&($("#content-box #back-round").removeProp("disabled"),$("#content-box #back-round").click(function(){window.location.href="tourn/"+hash+"/"+parseInt(k-1)}));if(d){$("#content-box #prepare").html("PREPARAR-SE").removeProp("disabled");a.locked&&$("#content-box #prepare").prop("disabled",!0).html("Aguarde a nova rodada");k=a.tournament.round;var n=a.nick;$("#content-box #prepare").off().click(function(){$.post("back_tournament_run.php",{action:"GLADS",hash:hash,
round:k}).done(function(a){a=JSON.parse(a);"LOCK"==a.status?(showMessage("Tarde demais. Seu grupo j\u00e1 encerrou as inscri\u00e7\u00f5es"),$("#content-box #prepare").prop("disabled",!0).html("Aguarde a nova rodada")):"NOTFOUND"==a.status?showMessage("Lista de gladiadores n\u00e3o encontrada"):($("body").append("<div id='fog'><div class='float-box'><div id='text'>Ol\u00e1 <span class='highlight'>"+n+"</span>, voc\u00ea precisa escolher um gladiador para representar a equipe <span class='highlight'>"+
m+"</span> na rodada <span class='highlight'>"+k+"</span> do torneio</div><div class='glad-card-container'></div><div id='button-container'><button id='cancel' class='button'>AINDA N\u00c3O</button><button id='choose' class='button' disabled>ESCOLHER</button></div></div></div>"),$(".float-box #cancel").click(function(){$("#fog").remove()}),$(".float-box #choose").click(function(){var a=$(".float-box .glad-preview.selected").data("id"),b=$(".float-box .glad-preview.selected .info .glad span").html();
$.post("back_tournament_run.php",{action:"CHOOSE",id:a,hash:hash}).done(function(a){a=JSON.parse(a);"DEAD"==a.status?showMessage("Este gladiador est\u00e1 gravemente ferido e n\u00e3o poder\u00e1 mais participar deste torneio"):"OLD"==a.status?showMessage("Este gladiador est\u00e1 desatualizado e n\u00e3o pode ser escolhido. Para atualiz\u00e1-lo, altere ele no editor e salve-o"):"SUCCESS"==a.status&&($("#fog").remove(),showMessage("Sua equipe escolheu o gladiador <span class='highlight'>"+b+"</span> para participar desta rodada. Assim que todas equipes escolherem seus representantes a batalha iniciar\u00e1."))})}),
load_glad_cards($(".float-box .glad-card-container"),{customLoad:a.glads,code:!0,master:!0,dead:!0,clickHandler:function(){$(this).hasClass("dead")||$(this).hasClass("old")||($(".float-box #choose").removeProp("disabled"),$(".float-box .glad-preview").removeClass("selected"),$(this).addClass("selected"))},dblClickHandler:function(){$(this).hasClass("dead")||$(this).hasClass("old")||$(".float-box #choose").click()}}).then(function(){}))})})}else $("#content-box #prepare").remove(),$("#button-container .arrow").addClass("nobutton");
var l=new Date(a.tournament.deadline);c()}})});
function refresh_round(){$.post("back_tournament_run.php",{action:"REFRESH",hash:hash,round:round}).done(function(a){a=JSON.parse(a);$("#content-box #group-container .team").each(function(){if(!$(this).parents(".group").hasClass("hide-info")){var b=$(this).data("id"),c=a.teams[b].lasttime;c=null==c?"-":1E3<=parseFloat(c)?"<img class='win' src='icon/winner-icon.png'>":parseFloat(c).toFixed(1);var d=["","one","two","three"];d=d[a.teams[b].alive];var f="hourglass_empty",g="",h="A equipe ainda n\u00e3o escolheu seu gladiador";
a.teams[b].ready&&(f="check",g="green",h="A equipe est\u00e1 pronta para a batalha");$(this).find(".icon i").html(f);$(this).find(".icon").attr("class","icon "+g);$(this).find(".icon").attr("title",h);$(this).find(".info .glad").attr("class","glad "+d);$(this).find(".info .time").html(c)}});var d=!1;$("#content-box #group-container .group").each(function(){var b=$(this),c=$(this).data("id");if("DONE"==a.groups[c].status)$(this).find(".foot .button").removeProp("disabled").html("VISUALIZAR BATALHA"),
$(this).find(".foot .button").click(function(){window.open("play/"+a.groups[c].hash);$(this).parents(".group").removeClass("hide-info")});else if("LOCK"==a.groups[c].status||"RUN"==a.groups[c].status){var e=function(){d?setTimeout(function(){e()},1E3):(d=!0,b.addClass("hide-info"),b.find(".foot .button").html("Grupo pronto. Organizando batalha..."),0<b.find(".team.myteam").length&&$("#content-box #prepare").prop("disabled",!0).html("Aguarde a nova rodada"),"RUN"==a.groups[c].status&&runSimulation({tournament:c}).then(function(a){"ERROR"!=
a&&$.post("back_tournament_run.php",{action:"UPDATE",hash:hash}).done(function(a){d=!1;a=JSON.parse(a);"NEXT"==a.status&&$.post("back_sendmail.php",{action:"TOURNAMENT",hash:hash}).done(function(a){console.log(a)})})}))};e()}else"WAIT"==a.groups[c].status&&($(this).find(".foot .button .number").html(a.groups[c].value),1==a.groups[c].value&&$(this).find(".foot .button").addClass("one"))});if("NEXT"==a.status||"END"==a.status)$("#content-box #next-round").removeProp("disabled"),$("#content-box #prepare").remove(),
$("#button-container .arrow").addClass("nobutton"),$("#content-box #next-round").off().click(function(){if("END"==a.status)window.location.href="tourn/"+hash+"/0";else{var b=parseInt(round)+1;window.location.href="tourn/"+hash+"/"+b}})});count_refresh++;setTimeout(function(){count_refresh--;0==count_refresh&&refresh_round()},5E3)}function msToTime(a){a=Math.floor(a/1E3);var d=Math.floor(a/60);a%=60;var b=Math.floor(d/60);d%=60;10>b&&(b="0"+b);10>d&&(d="0"+d);10>a&&(a="0"+a);return[b,d,a]};
